### ISSUE TITLE
End Portal spawns you in too high

### ISSUE THREAD

**Issue by VallenFrostweaver** [Johni0702/BetterPortals#101]
Minecraft 1.12.2
Forge: 14.23.5.2836
BetterPortals: 0.1.6

When creating an end portal it is hovering above the main End island so high up that you die from the fall on going through.

**Comment by Johni0702** [comment]
Have you actually tried going though and got killed? The portal position is intentional (looks way cooler) and lying portals are supposed to cancel the next fall damage after one passes through them.
Any other mods? SP/MP? Logs?

**Comment by VallenFrostweaver** [comment]
My apologies as I had the configs of another mod changed that messed with the values.

**Comment by VallenFrostweaver** [comment]
My apologies as I had the configs of another mod changed that messed with the values.
