### ISSUE TITLE
Night Vision Rendering Through Portal

### ISSUE THREAD

**Issue by BerNo434** [Johni0702/BetterPortals#106]
When you have the Night Vision effect the rendering that you see through the portal isn't affected by it, so that once you go through everything turns bright

**Comment by AlienXtream** [comment]
this does not currently seem to be working as of the time of this posting BP 0.3.7.5
OF is installed fyi (i seriously need it, game unplayable without for me :/)

**Comment by Johni0702** [comment]
@AlienXtream You're right. I've opened a new issue for it: #473 
I'm not entirely sure if this is a regression or if I just never looked at the block light level cause the sky is still changing for me when night vision is active (so I might have just looked only at the sky when initially implementing this and never noticed the lack of block light).
