### ISSUE TITLE
Crash when entering/leaving Weedwood Boat in the Betweenlands

### ISSUE THREAD

**Issue by Slavic-Squat** [Johni0702/BetterPortals#108]
When entering/leaving the Weedwood Rowboats in The Betweenlands mod, the game will crash.
This is easily repeatable, and happens in the overworld and the betweenland own dimension.

**Comment by Johni0702** [comment]
Crash Report?

**Comment by Slavic-Squat** [comment]
Here the crash report: 
https://pastebin.com/VFgeWwZr
