### ISSUE TITLE
Sound is played at correct coordinates but wrong dimension.

### ISSUE THREAD

**Issue by davidthehat** [Johni0702/BetterPortals#115]
For example, if there is a sound in the nether being played at nether coordinates (100, 50, 100), the sound can be heard if a portal is open and the player stands at (100, 50, 100) in the overworld.  Essentially, the check for if a sound can be heard ignores dimension and only considers coordinates.  This effect can easily be seen if a portal to the nether is open nearby, as you should hear fire sounds as you walk around the overworld.

**Comment by Johni0702** [comment]
The near-term solution for this will be disabling sound in all but the main world.
For having sound be properly played through portals, see #107.
