### ISSUE TITLE
Spawners don't render correctly through portals

### ISSUE THREAD

**Issue by davidthehat** [Johni0702/BetterPortals#118]
The tiny mob appears in a strange location and the flame particles are not created.  The tiny mob seems to be rendered where the spawner is but in the overworld and only when looking through the portal.  [Video](https://youtu.be/MdZ8s7-rH_s).

**Comment by Johni0702** [comment]
IIRC the flames only appear when the spawner is active and, when you're in the overworld, you're not close enough to the spawner for it to be active. So, that would be working as intended.

Entities get special treatment during rendering (to prevent them from showing on the wrong side of the portal). This special treatment is dependent on the entity's position and probably doesn't account for entities rendered as part of tile entities.
