### ISSUE TITLE
Hats mod duplication

### ISSUE THREAD

**Issue by SnaveSutit** [Johni0702/BetterPortals#119]
Whenever you travel though a portal, all the players in the world leave behind a ghost hat. It still follows their rotation and Y position, but ignores their x and z position. This causes random floating hats to appear everywhere after traveling though the portal a few times with a friend nearby. Super funny for the first 5 minutes, but gets in the way after a while xD

**Comment by Johni0702** [comment]
Hats or heads?
In case of the former, from which mod?
In case of the latter, I'll need more info to reproduce that.

**Comment by SnaveSutit** [comment]
The player's hats.
[this](https://www.curseforge.com/minecraft/mc-mods/hats) hats mod

**Comment by Johni0702** [comment]
After some research, I've come to the conclusion that this needs to be fixed in the Hats mod itself. I've reported it on their issue tracker (see reference above) with required details, so I'll close this issue now.
