### ISSUE TITLE
Not compatible with Vivecraft

### ISSUE THREAD

**Issue by Johni0702** [Johni0702/BetterPortals#122]
[someone said on CF](https://www.curseforge.com/minecraft/mc-mods/betterportals?comment=188)

**Comment by Johni0702** [comment]
Vivecraft is a jar mod and by far more invasive than OF with its patches.
I don't see that happening any time soon (not before vivecraft switches to mixins and becomes less invasive anyway).

**Comment by Techjar** [comment]
I should note that our changes are necessarily invasive, and using mixins wouldn't make things any easier (probably harder actually). Also, if you want to test this on Vivecraft yourself, you can install SteamVR and configure it to use the null driver with this `steamvr.vrsettings` file: https://gist.github.com/Techjar/4b5990abce6f3b155f6d8364bb1818b0

Anyways, someone tested it and this is happening:
![](https://cdn.discordapp.com/attachments/195502278508150784/631563838353047562/20191009125635_1_vr.jpg)

I haven't had time to test it myself yet.

**Comment by Johni0702** [comment]
> I should note that our changes are necessarily invasive, and using mixins wouldn't make things any easier (probably harder actually).

I understand that VC has to make some invasive changes. The main reason I strongly dislike the .patch way of doing that though, is that it makes it too easy to do changes. That leads to lots of changes which aren't actually changes:
https://github.com/jrbudda/Vivecraft_112/blob/d994f51126271afbcca213f8ac776febeddedcfd/patches/net/minecraft/client/renderer/EntityRenderer.java.patch#L860-L941
https://github.com/jrbudda/Vivecraft_112/blob/d994f51126271afbcca213f8ac776febeddedcfd/patches/net/minecraft/client/renderer/EntityRenderer.java.patch#L1094-L1101

Yet, they're still part of the diff and the only way for me to differentiate these non-changes from the important stuff is to go through line by line and carefully compare them (cause some do actually change things). Mixin on the other hand makes it very clear exactly what/where code was changed and (even though you end up modifying the same class) provides a clear distinction between mod and minecraft code (unless you use @Overwrite, but don't do that).

I also do realize that there's practically zero chance of VC switching to mixin given the amount of work involved. I meant that more along the lines of "If VC patches get easier to read, I'll immediately do it".

> you can install SteamVR and configure it to use the null driver

The null driver doesn't appear to have any tracking which is why I've instead ported [this](https://github.com/r57zone/OpenVR-OpenTrack) OpenVR driver to work on linux and have been using it with the FreePIE android app to get at least rotational tracking (and opentrack itself to get manual positional tracking).

> Also, if you want to test this on Vivecraft yourself, 

You seem to be under the impression that I've never run it. I've spent about 30 hours parsing through VC patches, figuring out why certain things don't quite work, fixing that and testing it.

> Anyways, someone tested it and this is happening

Under which circumstances? Only in the world or in the main menu as well?
Portal nearby? (the obsidian would indicate so)
Portal in view? (I don't see it)
Is it always the same part of the screen? (looks like a bit more than half of the screen, no idea what might cause that)
How about with see-through portals disabled?
Would be great if that someone could open a separate issue for this and answer above questions. I've never seen something like that during testing.
Also please enable the Debug View option and take a screenshot of how that looks (I'd prefer a screenshot of the mirror in the minecraft window for this one, if it looks any different than in the headset).

**Comment by Techjar** [comment]
The issue was reported by Beige#8743 in our Discord server, but they didn't provide any details yet. They said they'll open up a proper issue after doing more testing.

>That leads to lots of changes which aren't actually changes:

Yeah we haven't done that intentionally, and there isn't one single cause of it. We've been trying to clean up the superfluous patches, but it takes a lot of time.
