### ISSUE TITLE
Game not Rendering in ver 2.0

### ISSUE THREAD

**Issue by Warrof** [Johni0702/BetterPortals#124]
![2019-07-15](https://user-images.githubusercontent.com/21962742/61258074-a88f3a00-a728-11e9-820f-74069a18145a.png)
Minecraft 1.12.2
Forge Ver 14.23.5.2838
Windows 10, GeForce 980m, i7 cpu, 16 gB of ram

Yeah... installed BetterPortals 2.0 to see if the flickering was fixed...  Game save loaded, but no world rendering.  Aside from Hwyla info box, Minimap, Belt, etc...  

Could walk around and everything.

**Comment by Johni0702** [comment]
I need more info on which mods you've got installed, one of them is probably conflicting with the way BP 0.2 does its rendering now.

**Comment by Warrof** [comment]
As I was reading your response, I realized that I had KUDA shaders installed...  *facepalm*

Definitely #125.
