### ISSUE TITLE
better portals doesn't work with Aroma1997s Dimensional World.

### ISSUE THREAD

**Issue by nintysw** [Johni0702/BetterPortals#127]
It just crashes as soon as you enter the portal, confirmed that it is better portals.

crash log:
[crash-2019-07-16_12.04.16-server.txt](https://github.com/Johni0702/BetterPortals/files/3396682/crash-2019-07-16_12.04.16-server.txt)

**Comment by Johni0702** [comment]
Could you please check if that's still an issue when using BP 0.2?

**Comment by ThatHuman** [comment]
Its still a issue? And thank you, this mod is amazing. <3

**Comment by ThatHuman** [comment]
Nop, still crashes. Both mods have the most recent update, minecraft 1.12.2.

**Comment by Johni0702** [comment]
@ThatHuman please be specific with versions. Phrasings like "most recent" may be ambiguous (e.g. BP's most recent version on CF is 0.2.3 but you can get more recent stuff from git) and will be useless when one looks at them in a few weeks.

**Comment by ThatHuman** [comment]
Ah, sorry.

- MC **1.12.2**

- Forge **1.12.2 - 14.23.5.2838**

- Bether Portals **0.1.6** (CF's new look (twitch) only shows me beta versions and only now did I see an alpha down here, tomorrow morning I'll test this one.)

- Aroma1997Core **1.12.2-2.0.0.2.b165**

- Aroma1997s-Dimensional-World-**1.12.2-2.0.0.2.b89**

**Comment by Automatizer** [comment]
This is not an issue for me.

- MC 1.12.2

- Forge 1.12.2 - 14.23.5.2847

- BP 0.3.7.3

- Aroma1997Core 1.12.2-2.0.0.2.b166

- Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b96

**Comment by spiro-angelakis** [comment]
It is still not working, please fix this issue I love the mod.
Server also refuses to render blocks/entities/players for anyone that uses a /spawn command to leave the nether, then crashes their game if they die while stuck in that condition (there is no way to prevent/reverse it that I know of).
Server DOES crash anytime someone walks through an Aroma Mining Dimension Portal, they DO get teleported to the proper dimension, but everyone has to wait to server to reboot before they can even see that.

Aroma1997Core-1.12.2-2.0.0.2
Aroma1997s-Dimensional-World-1.12.2-2.0.0.2
betterportals-0.3.7.7
FTBUtilities-5.4.1.130
