### ISSUE TITLE
No instructions

### ISSUE THREAD

**Issue by Swoboderz** [Johni0702/BetterPortals#135]
there arent any instructions on how to compile this mod, nor is it obvious. always errors, furthest ive gotten is `e: /Users/dots/Desktop/BetterPortals/build/sources/main/kotlin/de/johni0702/minecraft/betterportals/common/Extensions.kt: (231, 47): Type mismatch: inferred type is Any? but IBlockState! was expected
e: /Users/dots/Desktop/BetterPortals/build/sources/main/kotlin/de/johni0702/minecraft/betterportals/common/Extensions.kt: (231, 61): Type mismatch: inferred type is Any? but IBlockState? was expected
:compileKotlin FAILED
`

**Comment by Johni0702** [comment]
There aren't any instructions because it should compile just like any other mod which is using ForgeGradle (or when FG is behaving, then like any other Gradle project).
Which commit are you trying to build?

**Comment by Johni0702** [comment]
Looks like [this](https://github.com/MinecraftForge/ForgeGradle/issues/538) bug in ForgeGradle to me.
Try running `./gradlew setupDecompWorkspace` before `./gradlew build`.

**Comment by Swoboderz** [comment]
Looks like that bug indeed was it.
