### ISSUE TITLE
Consider Atum 2 portal compatability.

### ISSUE THREAD

**Issue by SpGilbert** [Johni0702/BetterPortals#137]
https://www.curseforge.com/minecraft/mc-mods/atum

**Comment by Johni0702** [comment]
The mod's license is "All Rights Reserved" and as such does not allow me to support it in BP.

**Comment by Redd56** [comment]
Idea: ask the mod authors. Just a random thought.
Maybe theybwill say sure

**Comment by Johni0702** [comment]
@Redd56 feel free to ask them, I'd be happy if they do.

The specific thing I would require is for them to provide their mod under a GPLv3-compatible license (e.g. one of [these](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses)).

Once they've updated the license listed on CF and in their source repository, please re-open this issue.

**Comment by SpGilbert** [comment]
well im a meber of both discords so i can ask them

**Comment by SpGilbert** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/42950385/61495086-f785db00-a985-11e9-87ca-f35ee861f536.png)
here

**Comment by Johni0702** [comment]
I don't yet know what needs to be done as I'm not familiar with the Atum mod (so I may very well have to duplicate some of its code).
Chances are that I'll at least have to subclass its portal Block (or TileEntity whichever it is) class and as per https://www.gnu.org/licenses/gpl-faq.html#OOPLang the Atum mod has to be GPL-compatible for me to be able to do that.

**Comment by SpGilbert** [comment]
OK

**Comment by GirafiStudios** [comment]
Hey @Johni0702.
When you have time at some point, could I get you to DM me on Discord so we can have a chat about this? :)
Invite link to server: https://discordapp.com/invite/TuJXw7V

**Comment by Johni0702** [comment]
@GirafiStudios I'd rather not because I don't regularly use discord and don't see why this could not be discussed here.

**Comment by GirafiStudios** [comment]
Fair enough.
We're not going to change our license to GPL, since that allows for our entire mod to be redistributed (Although have to be a different name, and changes made since the original source have to be stated).
But you're very welcome to copy whatever you need from any of our portal code :)
