### ISSUE TITLE
Portals lit in the nether can generate portals in lava lakes in the overworld

### ISSUE THREAD

**Issue by Hudeler** [Johni0702/BetterPortals#14]
![2019-05-29_19 01 39](https://user-images.githubusercontent.com/16482071/58576308-519ad780-8244-11e9-91b8-c3cc40a12ba8.png)

**Comment by T145** [comment]
This is default MC portal gen though.

**Comment by Hudeler** [comment]
I have never seen this behavior in vanilla, which is why I assumed it might be related to the mod.  It seems like I was wrong.
