### ISSUE TITLE
autoreglib compatibilty problem

### ISSUE THREAD

**Issue by SpGilbert** [Johni0702/BetterPortals#140]
https://paste.dimdev.org/lipexevahi.mccrash

**Comment by Johni0702** [comment]
When does this happen (i.e. how do I reproduce this)?
I've looked at autoreglib's code and it looks like this is an error in one of the mods which is using it (probably Quark or Akashic Tome). Are you able to reproduce this with just BP + autoreglib + one of those two?

**Comment by Johni0702** [comment]
This is an issue with Autoreglib, see my (updated) comment in: https://github.com/Vazkii/AutoRegLib/issues/33
