### ISSUE TITLE
Better portals made customnpcs look like pong paddles! Forge 2838, 1.12.2 

### ISSUE THREAD

**Issue by Sageking10** [Johni0702/BetterPortals#146]
![2019-07-19_11 06 02](https://user-images.githubusercontent.com/48606472/61545467-8c83e500-aa15-11e9-812a-c99b42faa6d3.png)
This happens when i go back and forth between dimensions, with the customnpcs mod installed.

**Comment by Johni0702** [comment]
Which version of BP / CustomNPCs?

**Comment by Sageking10** [comment]
CustomNPCs_1.12.2(30Jan19)
betterportals-0.1.6

**Comment by Johni0702** [comment]
Duplicate of #42
