### ISSUE TITLE
Compatability issue with LiteLoader

### ISSUE THREAD

**Issue by lol123406** [Johni0702/BetterPortals#156]
Nether portal just shows up as a missing texture, nether never loads, and trying to go through it causes a crash, end portal just gives a seemingly fallback animation and doesn't do a seamless transition

Here's a crash log https://pastebin.com/apEVqNMD

**Comment by Johni0702** [comment]
This seems to be a bug in liteloader, see: https://www.curseforge.com/minecraft/mc-mods/extra-foam-for-liteloader
