### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Khodyn** [Johni0702/BetterPortals#157]
I only have this mod installed, and I am crashing on startup.

[crash-2019-07-21_08.35.12-client.txt](https://github.com/Johni0702/BetterPortals/files/3414037/crash-2019-07-21_08.35.12-client.txt)

**Comment by Johni0702** [comment]
You're missing Forgelin, see https://www.curseforge.com/minecraft/mc-mods/betterportals/relations/dependencies
