### ISSUE TITLE
Multimine causes crashes

### ISSUE THREAD

**Issue by XKane55** [Johni0702/BetterPortals#158]
When I use Multimine, it crashes when I go in the nether and break a block. I thought I'd say it so that you know it happens. It's a really amazing mod and I needed that! I would've liked to use it with shaders though, but oh well.

**Comment by Johni0702** [comment]
Crash Report?

**Comment by Johni0702** [comment]
Upon taking a close look, I've come to the conclusion that this needs to be fixed in MultiMine.
I've reported it on their issue tracker with an explanation for what went wrong and suggestions on how to fix it: https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/279
