### ISSUE TITLE
"Better Portals ran into an issue"

### ISSUE THREAD

**Issue by Recorpse** [Johni0702/BetterPortals#163]
I was trying to use this mod on my server but every time I tried loading into the server it crashes the server and I get "Better Portals ran into an issue". I can't post a log because It never makes a log for this for some reason.

**Comment by Johni0702** [comment]
Make sure you've got Forgelin installed.
I doubt there isn't more info than just that one sentences. Reading [this](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html) might help.

**Comment by Recorpse** [comment]
I do. my game works perfectly fine in single player buy as soon as I try to join multiplayer it says that and the server crashes although it happens even when the mod isn't installed and other mods run into issues instead so im really not sure

**Comment by Johni0702** [comment]
> it says that

Who says that? I don't recall ever reading such a sentence in that context.

> the server crashes

So, if the server crashes, then there must be some kind of crash report, how else would you know that it crashes?!

> it happens even when the mod isn't installed

Then why ask here? Maybe try the [Forge Forum](https://www.minecraftforge.net/forum/) instead?

**Comment by Recorpse** [comment]
ok, I'll just ask on the  forum
