### ISSUE TITLE
Crash With Mekanism Better Portal

### ISSUE THREAD

**Issue by TheMCSpacePro** [Johni0702/BetterPortals#165]
When launching the game with the Mekanism Teleporter, it crashes with this message:
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2019-07-22 17:12:34 EDT
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Better Portals (betterportals)
Caused by: java.lang.NoSuchFieldError: tileEntitySupplier
    at de.johni0702.minecraft.betterportals.impl.mekanism.common.ExtensionsKt$initMekanism$1.invoke(Extensions.kt:42)
    at de.johni0702.minecraft.betterportals.impl.mekanism.common.ExtensionsKt$initMekanism$1.invoke(Extensions.kt)
    at de.johni0702.minecraft.betterportals.impl.BetterPortalsMod$CommonProxy.postInit(BetterPortalsMod.kt:147)
    at de.johni0702.minecraft.betterportals.impl.BetterPortalsMod$ClientProxy.postInit(BetterPortalsMod.kt:179)
    at de.johni0702.minecraft.betterportals.impl.BetterPortalsMod.preInit(BetterPortalsMod.kt:130)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 543725688 bytes (518 MB) / 1610612736 bytes (1536 MB) up to 4294967296 bytes (4096 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2838 51 mods loaded, 51 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                   | Version           | Source                                        | Signature                                |
       |:----- |:-------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
       | LCHIJ | minecraft            | 1.12.2            | minecraft.jar                                 | None                                     |
       | LCHIJ | mcp                  | 9.42              | minecraft.jar                                 | None                                     |
       | LCHIJ | FML                  | 8.0.99.99         | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJ | forge                | 14.23.5.2838      | forge-1.12.2-14.23.5.2838.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJ | creativecoredummy    | 1.0.0             | minecraft.jar                                 | None                                     |
       | LCHIJ | itemphysic           | 1.4.0             | minecraft.jar                                 | None                                     |
       | LCHIJ | micdoodlecore        |                   | minecraft.jar                                 | None                                     |
       | LCHIJ | foamfixcore          | 7.7.4             | minecraft.jar                                 | None                                     |
       | LCHIJ | bspkrscore           | 7.6.0.1           | [1.12]bspkrsCore-universal-7.6.0.1.jar        | None                                     |
       | LCHIJ | treecapitator        | 1.43.0            | [1.12]TreeCapitator-client-1.43.0.jar         | None                                     |
       | LCHIJ | jei                  | 4.15.0.268        | jei_1.12.2-4.15.0.268.jar                     | None                                     |
       | LCHIJ | quark                | r1.5-167          | Quark-r1.5-167.jar                            | None                                     |
       | LCHIJ | autoreglib           | 1.3-31            | AutoRegLib-1.3-31.jar                         | None                                     |
       | LCHIJ | betaplus             | 0.4back           | betaplus-0.4.1.jar                            | None                                     |
       | LCHIJ | forgelin             | 1.8.3             | Forgelin-1.8.3.jar                            | None                                     |
       | LCHIE | betterportals        | 0.2.3             | betterportals-0.2.3.jar                       | None                                     |
       | LCHI  | buildcraftlib        | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                  | None                                     |
       | LCHI  | buildcraftcore       | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                  | None                                     |
       | LCHI  | buildcraftbuilders   | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                  | None                                     |
       | LCHI  | buildcrafttransport  | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                  | None                                     |
       | LCHI  | buildcraftsilicon    | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                  | None                                     |
       | LCHI  | buildcraftcompat     | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                  | None                                     |
       | LCHI  | buildcraftenergy     | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                  | None                                     |
       | LCHI  | buildcraftfactory    | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                  | None                                     |
       | LCHI  | buildcraftrobotics   | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                  | None                                     |
       | LCHI  | codechickenlib       | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHI  | cookingforblockheads | 6.4.70            | CookingForBlockheads_1.12.2-6.4.70.jar        | None                                     |
       | LCHI  | creativecore         | 1.9.9             | CreativeCore_v1.9.45_mc1.12.2.jar             | None                                     |
       | LCHI  | cucumber             | 1.1.3             | Cucumber-1.12.2-1.1.3.jar                     | None                                     |
       | LCHI  | foamfix              | 0.10.5-1.12.2     | foamfix-0.10.5-1.12.2.jar                     | None                                     |
       | LCHI  | furnaceoverhaul      | 1.0.3             | Furnace-Overhaul-Mod-1.12.2.jar               | None                                     |
       | LCHI  | mantle               | 1.12-1.3.3.49     | Mantle-1.12-1.3.3.49.jar                      | None                                     |
       | LCHI  | tconstruct           | 1.12.2-2.12.0.135 | TConstruct-1.12.2-2.12.0.135.jar              | None                                     |
       | LCHI  | galacticraftcore     | 4.0.2.210         | GalacticraftCore-1.12.2-4.0.2.210.jar         | None                                     |
       | LCHI  | galacticraftplanets  | 4.0.2.210         | Galacticraft-Planets-1.12.2-4.0.2.210.jar     | None                                     |
       | LCHI  | waila                | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
       | LCHI  | inspirations         | 1.12.2-0.2.4      | Inspirations-1.12.2-0.2.4.jar                 | None                                     |
       | LCHI  | ironbackpacks        | 1.12.2-3.0.8-12   | IronBackpacks-1.12.2-3.0.8-12.jar             | None                                     |
       | LCHI  | ironchest            | 1.12.2-7.0.64.843 | ironchest-1.12.2-7.0.64.843.jar               | None                                     |
       | LCHI  | earthenbounty        | 2.1.6             | just_a_few_more_ores-2.1.6.jar                | None                                     |
       | LCHI  | mekanism             | 1.12.2-9.7.2.373  | Mekanism-1.12.2-9.7.2.373.jar                 | None                                     |
       | LCHI  | mekanismgenerators   | 1.12.2-9.7.2.373  | MekanismGenerators-1.12.2-9.7.2.373.jar       | None                                     |
       | LCHI  | mekanismtools        | 1.12.2-9.7.2.373  | MekanismTools-1.12.2-9.7.2.373.jar            | None                                     |
       | LCHI  | morebuckets          | 1.0.4             | MoreBuckets-1.12.2-1.0.4.jar                  | None                                     |
       | LCHI  | oldcombat            | 1.0.0             | OldCombat-1.12.2-v1.0.0.jar                   | None                                     |
       | LCHI  | simplesteel          | 1.2               | Simple+Steel+1.2+[1.12.2].jar                 | None                                     |
       | LCHI  | superflatcaves       | 1.2.0             | superflatcaves-1.2.0.jar                      | None                                     |
       | LCHI  | tp                   | 3.2.32            | tinyprogressions-1.12.2-3.3.32-Release.jar    | None                                     |
       | LCHI  | vanillafix           | 1.0.10-SNAPSHOT   | VanillaFix-1.0.10-99.jar                      | None                                     |
       | LCHI  | walljump             | 1.12.2-1.2.3      | walljump-1.12.2-1.2.3.jar                     | None                                     |
       | LCHI  | xaerominimap         | 1.16.3            | Xaeros-Minimap-Mod-1.12.jar                   | None                                     |
  Loaded coremods (and transformers): ForgelinPlugin (Forgelin-1.8.3.jar)
                                        
                                      RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
                                        pw.prok.realbench.asm.RBTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      CreativePatchingLoader (CreativeCore_v1.9.45_mc1.12.2.jar)
                                        
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.210.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      Quark Plugin (Quark-r1.5-167.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      ItemPatchingLoader (ItemPhysic_Full_1.4.21_mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
  GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 24.20.100.6286' Renderer: 'Intel(R) UHD Graphics 620'
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - wailaIntegration (Enabled/Not Forced)
  Pulsar/inspirations loaded Pulses: - InspirationsShared (Enabled/Forced)
                                     - InspirationsBuilding (Enabled/Not Forced)
                                     - InspirationsUtility (Enabled/Not Forced)
                                     - InspirationsTools (Enabled/Not Forced)
                                     - InspirationsRecipes (Enabled/Not Forced)
                                     - InspirationsTweaks (Enabled/Not Forced)
                                     - InspirationsShared (Enabled/Forced)
                                     - WailaPlugin (Enabled/Not Forced)
  Suspected Mods: Better Portals (betterportals)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2838
  LWJGL: 2.9.4
  OpenGL: Intel(R) UHD Graphics 620 GL version 4.5.0 - Build 24.20.100.6286, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: SeanCraft
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz

**Comment by TheMCSpacePro** [comment]
Forgot to say, the only way to fix this is to turn off the Better Teleporter in the config!

**Comment by Johni0702** [comment]
You're using an old version of Mekanism.

**Comment by TheMCSpacePro** [comment]
Ok, thanks.
