### ISSUE TITLE
Concurrent moddification exception

### ISSUE THREAD

**Issue by Noahboy007** [Johni0702/BetterPortals#172]
World is crashing shortly after load,and as far as I can tell the crash log is pointing towards better portals. If I'm wrong could you please point me in the right direction? I've attached the crash log
[crash-2019-07-23_12.41.20-client.txt](https://github.com/Johni0702/BetterPortals/files/3423417/crash-2019-07-23_12.41.20-client.txt)

**Comment by Johni0702** [comment]
Looks very much like [this](https://github.com/p455w0rd/p455w0rds-Library/issues/37) bug in p455w0rdslib. Try using the workaround provided over there until it gets a new release.
