### ISSUE TITLE
Error: java.lang.NoSuchFieldError: portal

### ISSUE THREAD

**Issue by Noahboy007** [Johni0702/BetterPortals#174]
[crash-2019-07-23_14.10.41-client.txt](https://github.com/Johni0702/BetterPortals/files/3423729/crash-2019-07-23_14.10.41-client.txt)
Getting a crash on world load next to portal. Not sure of the cause, but could disabling the mod to break the portals, and then re-enabling solve my problem?

**Comment by Johni0702** [comment]
Crash Report?

**Comment by Johni0702** [comment]
From BP's CurseForge page:
> Twilight Forest portal (as of BP 0.2, disabled by default in 0.1, requires TF 3.8 or below / not yet compatible with TF 3.9)

**Comment by Johni0702** [comment]
If you nevertheless wish to use TF 3.9, you can disable better portals for it in BP's config.

**Comment by Noahboy007** [comment]
Ahh totally over looked that thank you.
