### ISSUE TITLE
Could You Make Your Mod Supports the Erebus and the Betweenlads Portal?

### ISSUE THREAD

**Issue by GingerMeow** [Johni0702/BetterPortals#175]
As the title suggests.

**Comment by Johni0702** [comment]
Erebus: #139 


The Betweenlands' license is "All Rights Reserved" as well and as such does not allow me to support it in BP.

Feel free to ask their developers whether they're open to re-licensing their mod, I'd be happy if they do, but I wouldn't get my hopes up.
The specific thing I would require is for them to provide their mod under a GPLv3-compatible license (e.g. one of [these](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses)).

Once they've updated the license listed on CF and in their source repository, please re-open this issue.

**Comment by GingerMeow** [comment]
OK.I Know,thanks.
