### ISSUE TITLE
game does not start

### ISSUE THREAD

**Issue by VictorGamerLOL** [Johni0702/BetterPortals#177]
I do not know what is wrong i just downloaded the mod and the client crashed, here is the crash report: WARNING, I AM USING 65 MODS:
[Manually-copied-and-pasted-crash-report.txt](https://github.com/Johni0702/BetterPortals/files/3430073/Manually-copied-and-pasted-crash-report.txt)

**Comment by Johni0702** [comment]
You're missing [Forgelin](https://www.curseforge.com/minecraft/mc-mods/betterportals/relations/dependencies).
