### ISSUE TITLE
1.12.2 Crashes Before Startup

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Johni0702/BetterPortals#18]
u-betterportals-0.1.0-b.jar

I added it to this pack 

https://github.com/P3rf3ctXZer0/Zer0Necrosis-Project-Workbench/releases/tag/mc-1.12.2-IfYouWantItWorkForIt-0010

**Comment by Johni0702** [comment]
I'll be needing more info than that (the crash log for example).
Also, could you retry with 0.1.1?

**Comment by P3rf3ctXZer0** [comment]
Yes and no. I will run a test for you just give me about 1 hour.

**Comment by P3rf3ctXZer0** [comment]
Yes it still crashes.

**Comment by P3rf3ctXZer0** [comment]
[latest.log](https://github.com/Johni0702/BetterPortals/files/3235788/latest.log)
No crash log generated.

**Comment by Johni0702** [comment]
Thanks! That should be trivial to fix.
