### ISSUE TITLE
Issue with millenaire mod

### ISSUE THREAD

**Issue by SamboyCoding** [Johni0702/BetterPortals#181]
Upon attempting to open a locked chest from the mod "millénaire", the following exception is thrown, and the GUI for the chest never opens: [Exception Report](https://paste.dimdev.org/senotaheji.mccrash). That's a VanillaFix crash report so it's possible it would hard crash the game usually.

I know this isn't exactly a clean environment, let me know if you need me to test with just these two mods or if this is enough information.

**Comment by Johni0702** [comment]
Yes, please try the same thing with just BP+Millenaire. There are quite a few mods in there which I wouldn't be surprised if they changed something relevant.
Also try using BP 0.2.x, lots of stuff has changed since 0.1.x.
Once you've done both of the above, please post an updated crash report.

**Comment by SamboyCoding** [comment]
Ah, damn. Thought I was on the latest version but I blindly installed the latest beta, not alpha.

**Comment by SamboyCoding** [comment]
Ok, seems it works on just BP 0.2 and millenaire, I'll check if it still breaks in the larger pack with BP 0.2

**Comment by SamboyCoding** [comment]
Ok, can confirm all good on 0.2. Sorry about that!
