### ISSUE TITLE
Getting occasional crashes on portal breaks

### ISSUE THREAD

**Issue by gguy825** [Johni0702/BetterPortals#184]
Sometimes if i accidentally break the portal and have to redo it the game will crash. This mainly happens with obsidian portals both when I'm in the nether and outside of it. (version 1.6) Also on 2.3 i had an issue where it crashed when i tried to set up a portal to the twilight forest. I also tried it with aether 2 and crashed on 2.3 as well.

**Comment by gguy825** [comment]
Also wanted to add that it would sometimes place me portal in the air when restarting the game like so, https://i.imgur.com/4ag2ocz.png forgot to add that.

**Comment by Johni0702** [comment]
Please open one issue per bug and provide sufficient information for each.
If you don't know what I mean by sufficient information, then give [this](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html) a read.
Also, it's 0.1.6 and 0.2.3, not 1.6 and 2.3. The difference is important once we're in the future and 1.6 actually exists.
