### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by C0LiSii0N** [Johni0702/BetterPortals#195]
Hi little problem here, I "crash" on the game launch(In fact, after I press launch it close the launcher and nothing start. There are my logs: 
[latest.log](https://github.com/Johni0702/BetterPortals/files/3455358/latest.log)

Btw I tested with 1.6 and 2.3 and both have the same issue.

**Comment by Johni0702** [comment]
Looks like the same error as #90 but in a different mod.
Hard to tell from the log which mod is causing it. Best guess would be
```
[03:04:15] [main/INFO]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [itemphysic] Patched net.minecraft.client.entity.EntityPlayerSP ...
```
Try removing third-party coremods until you find the one which is at fault, then report it to them.
