### ISSUE TITLE
portal disappears on creation

### ISSUE THREAD

**Issue by bobodoustaud** [Johni0702/BetterPortals#198]
when i create a nether portal, the portal appears during 1 second and disappears. the server doesn't crash but the console writes some errors.

https://pastebin.com/5R9vDGey

but the mekanism portal work just fine.

**Comment by Johni0702** [comment]
This appears to be an issue with (server-side) JourneyMap.
There was a significant change to the code which caused the crash in JourneyMap 1.12.2-5.5.5b9, could you try updating to that (or a more recent version) and check if it works?

**Comment by bobodoustaud** [comment]
ok sure

**Comment by bobodoustaud** [comment]
ok works. thanks !
