### ISSUE TITLE
crashes on launch.

### ISSUE THREAD

**Issue by BrianNickSundberg** [Johni0702/BetterPortals#199]
[crash-2019-08-03_16.18.59-client.txt](https://github.com/Johni0702/BetterPortals/files/3464416/crash-2019-08-03_16.18.59-client.txt)

With only betterportals installed, the game crashes on launch.

**Comment by 4Benj** [comment]
Looks like the same error i'm getting, but i do have multiple mods installed
[crash-2019-08-04_09.57.00-client.txt](https://github.com/Johni0702/BetterPortals/files/3464495/crash-2019-08-04_09.57.00-client.txt)

**Comment by Johni0702** [comment]
You need to install Forgelin:
https://www.curseforge.com/minecraft/mc-mods/betterportals/relations/dependencies
