### ISSUE TITLE
[Suggestion] Cubic Chunks compatability?

### ISSUE THREAD

**Issue by theishiopian** [Johni0702/BetterPortals#20]
I tried this mod with cubic chunks, and believe it or not, it actually loads, and you can even make a portal. But as soon as you try to pass, this gets printed in the console: https://pastebin.com/biwuMk5i (also you cant see through the portal)

The fact that this works as well as it does (loading the game and even running and making a portal) suggests it could be patched to work, just call their teleport method instead, or make sure your mixin thing has priority (assuming thats how it works). The dev team for cubic chunks is very open to working to other devs to implement cross-compatibility. 

If this interests you, check out their discord.

**Comment by Redd56** [comment]
Litteraly about to ask that

**Comment by Johni0702** [comment]
I've fixed the initial issue. Portals are now see-through but they cannot yet be used.

However, somewhere in the CubicChunks code there's the (arguably reasonable but now incorrect) assumption that only one world will be loaded at any one time. As a result it currently mixes chunks from both dimensions, so I wouldn't recommend using both mods as is.

**Comment by Redd56** [comment]
Ill relay the info to barteks
