### ISSUE TITLE
Mobs behind portals are sometimes visible through portals

### ISSUE THREAD

**Issue by rmw5601** [Johni0702/BetterPortals#204]
Two pigmen behind a portal ([as seen here](https://user-images.githubusercontent.com/21069876/62444854-aec37580-b72c-11e9-9ce8-6ec270630c15.png)) are visible from the other side of the portal ([as seen here](https://user-images.githubusercontent.com/21069876/62444966-0a8dfe80-b72d-11e9-8f06-0d1c576a8374.png)) despite the fact that they should not be in the portal's line of sight.

This is easily reproducible by setting a portal and a mob similarly to how I have pictured below.
![2019-08-05_03 05 43](https://user-images.githubusercontent.com/21069876/62445468-42497600-b72e-11e9-86ae-858ee99aa637.png)
![2019-08-05_03 05 22](https://user-images.githubusercontent.com/21069876/62445472-44133980-b72e-11e9-852e-7f7a6ffb0d32.png)

**Comment by Johni0702** [comment]
Which version of BP are you using?

**Comment by rmw5601** [comment]
This is version 0.2.4

**Comment by Johni0702** [comment]
Do you have any other mods installed?
I seem to be unable to reproduce this:
![](https://i.johni0702.de/A0QCp.png)
![](https://i.johni0702.de/AfaFw.png)

**Comment by rmw5601** [comment]
I do not have any other mods installed other than Optifine. I have been able to reproduce this on a newly created instance where the only mods installed are BP and Optifine at default settings (other than changing the FOV to 90, if that makes any difference.

The setup I'm using is like this
![2019-08-05_03 42 40](https://user-images.githubusercontent.com/21069876/62447369-3c09c880-b733-11e9-9706-bd3d6fd8fc27.png)
![2019-08-05_03 42 48](https://user-images.githubusercontent.com/21069876/62447376-3f04b900-b733-11e9-82e7-6cea6d9f1382.png)

This scenario in particular seems to consistently cause the mob to render through the portal, as I've been able to recreate it like this.

Strangely, enough. A set up like this:
![2019-08-05_03 46 02](https://user-images.githubusercontent.com/21069876/62447525-94d96100-b733-11e9-86f6-a009383154dc.png)
Results in only the villager on the right being erroneously rendered, as seen in this clip:
https://files.catbox.moe/hzlhhl.mp4

**Comment by Johni0702** [comment]
Could you please verify that this happens without OF as well?

The last screenshot suggests that this might be related in some way to the order in which entities are rendered. Could you tell me which way is north in that screenshot, so I can try to reproduce it as close as possible?

**Comment by Umitrix** [comment]
is the original portal texture supposed to show up ?

**Comment by Johni0702** [comment]
@Umitrix Yes. That doesn't seem at all related to this issue though.

**Comment by Umitrix** [comment]
well, the texture wasn't showing up in the previous version and seeing it does now made me think there was some conflict on a modpack i'm using.

**Comment by Johni0702** [comment]
@Umitrix 0.1.x didn't render the original portal texture. I added that functionality in 0.2 because of popular demand.
