### ISSUE TITLE
[Serene Seasons Compatibility] Randomly switching seasons

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [Johni0702/BetterPortals#207]
When looking/moving around a portal the screen is flickering. For some reason it only happens in the overworld for me.
Video: http://erdbeerbaerapi.tk/2019-08-05%2017-24-27.mp4

**Comment by ErdbeerbaerLP** [comment]
Just saw it is switching through all seasons. Looks like it is now incompatible with SereneSeasons (https://github.com/Glitchfiend/SereneSeasons)

**Comment by Johni0702** [comment]
Yes, it's an issue which needs to be fixed in SereneSeasons. I've already reported it to them with details but it appears like they won't have the time to fix it:
https://github.com/Glitchfiend/SereneSeasons/issues/153

**Comment by Johni0702** [comment]
Duplicate of #88

**Comment by ErdbeerbaerLP** [comment]
Well, until it is fixed, i remove the seasons from the world
