### ISSUE TITLE
Crash on start up for unknown reason (at least for me)

### ISSUE THREAD

**Issue by ShockanPlays** [Johni0702/BetterPortals#214]
I dont know why but I appreciate the help

here is the crash log
[crash-2019-08-06_19.43.22-client.txt](https://github.com/Johni0702/BetterPortals/files/3473306/crash-2019-08-06_19.43.22-client.txt)

**Comment by Johni0702** [comment]
You're missing Forgelin: https://www.curseforge.com/minecraft/mc-mods/betterportals/relations/dependencies?filter-related-dependencies=3
