### ISSUE TITLE
Better Portal - Igniting Portal cause game to crash

### ISSUE THREAD

**Issue by VayneAlvaldi** [Johni0702/BetterPortals#215]
So I'm trying to figure of there's a compatibility issue with the mods I have for my server.

Every time I make the nether portal (whether its the standard size or custom size) the portal ignites before crashing my game outright with the log of (Error: java.lang.NullPointerException: The validated object is null) on my minecraft launcher. Not sure what could be crashing and been looking around to see if someone have similar cases.

[crash-2019-08-06_13.11.07-client.txt](https://github.com/Johni0702/BetterPortals/files/3474223/crash-2019-08-06_13.11.07-client.txt)

**Comment by SalTeyJek004** [comment]
it crashes when igniting for me as well but i only have these mods installed
chisels & bits
extra bit manipulation
creative core
little tiles
shadowfacts forgelin
and of course better portals

**Comment by Panduso** [comment]
same issue with me sometimes

**Comment by Panduso** [comment]
and i have the exact same mods as you sal

**Comment by Johni0702** [comment]
This looks like a known issue with StellarSky: #85 

@SalTeyJek004 @Panduso Since you do not have StellarSky installed, you cannot have the same issue as OP. Please open a separate issue each (I'll simply close one if they turn out to be the same) and include the crash report in those.
