### ISSUE TITLE
Incompatible with VanillaFix

### ISSUE THREAD

**Issue by VoidFyre** [Johni0702/BetterPortals#218]
I wanted to put this into my twitch modpack, but optifine cannot be included in the pack according to the twitch and optifine licencing rules. As soon as I take optifine out of the mods folder and attempt to run the game, it crashes before the game even opens the forge visual loading screen.  After I press play, the launcher vanishes, then 5-6 seconds later, it reappears with an error. 
[crash-2019-08-07_11.27.43-client.txt](https://github.com/Johni0702/BetterPortals/files/3477758/crash-2019-08-07_11.27.43-client.txt)

**Comment by Johni0702** [comment]
You're missing Forgelin: https://www.curseforge.com/minecraft/mc-mods/betterportals/relations/dependencies?filter-related-dependencies=3
OF is a red herring (and tbh I cannot possibly imagine it having worked with OF but without Forgelin).

**Comment by VoidFyre** [comment]
Nope, I do have forgelin installed. Just double and triple checked and even reinstalled it. It still crashes before launching with BetterPortals installed

**Comment by Johni0702** [comment]
You must have gotten the incorrect crash report then because it unambiguously states that Forgelin is not installed.

**Comment by VoidFyre** [comment]
Im not sure why the log said that at all, every time I got this issue I had forgelin installed. When I can, ill try and check to see if it is a certain mod messing up the loading process between BP and forgelin, or if there are simply too many mods.

**Comment by Johni0702** [comment]
No, that can't be it either. I've added explicit support for one of VanillaFix's issues in 0.2.4 which involved quite a bit of running it alongside BP. I just tried BP 0.2.6 as well and it loads to Main Menu with no issues.

**Comment by Johni0702** [comment]
I'm not up for installing random packs.
The correct crash report and/or log file is what I'm looking for (preferably the log). Chances are it'll already have enough information to tell which mod's causing it.

Also, in general, be more deliberate with your statements. Saying "It was VanillaFix." sounds like you tested just Forgelin + BP + VanillaFix and it broken, then you removed VanillaFix and it worked. It does not sound like you had tons of other mods in there as well, each of which could very well change things significantly on its own.
You might want to give [this article](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html) a read.

**Comment by Johni0702** [comment]
p455w0rdlib's coremod is broken, see https://github.com/p455w0rd/p455w0rds-Library/issues/26 and https://github.com/p455w0rd/p455w0rds-Library/issues/45.
