### ISSUE TITLE
Purple nether effect, How do i make the portals not have that effect

### ISSUE THREAD

**Issue by Shrew43** [Johni0702/BetterPortals#220]
The portal when created still has the purple effect and i dont want it to have the purple effect, any fixes?

**Comment by SkullBonez2** [comment]
Got to C:\Users\(you)\AppData\Roaming\.minecraft\config\betterportals.cfg and change the value "D:Opacity=" to 0.0

**Comment by Johni0702** [comment]
Alternatively: Main Menu -> Mods -> BetterPortals -> Config -> Nether Portal -> Opacity
