### ISSUE TITLE
Multiple linked portals in Nether crashes game after entering and leaving the nether.

### ISSUE THREAD

**Issue by SkullBonez2** [Johni0702/BetterPortals#221]
This sucks. When I create 2 linked portals in the nether and enter one side from the overworld and exit the other portal in the nether, the overworld turns into a red void and subsequently crashes the game.

Sometimes this happens instantly, other times it happens 10 seconds after.

I might add that these portals (in the nether) are 15 blocks apart, and are linked using their respective overworld coordinates.

 Link to pastebin crashlog [https://pastebin.com/z9aVeSHW](url)

**Comment by Johni0702** [comment]
Please upload the world and give exact instructions on how to reliably reproduce this.

**Comment by SkullBonez2** [comment]
[BetterPortals Crash.zip](https://github.com/Johni0702/BetterPortals/files/3485171/BetterPortals.Crash.zip)
Walk through the entrance of the first portal, then come out of the second portal.

It also crashes with only one portal, but this is the first time I tried building a 'gateway' in creative with the mod.

Tested on Recommended and Latest forge builds, using default Minecraft Launcher java properties. Also tested with higher RAM allocation (8gb from 2gb). Same story for all.

**Comment by SkullBonez2** [comment]
It seems to be tied to render distance. I found that if the render distance is anywhere between 2 and 7 chunks inclusive than its fine, but when it is 8 chunks and over the crashing starts to happen.

**Comment by SkullBonez2** [comment]
Having 3 portals in the world lowers the maximum render distance to 3 chunks. with 3 nether portals active the game crashes at a 4 chunk render distance. I assume a 4th portal will make travelling to the nether and back impossible without crashing, as the max render distance then would be 1 chunk, which is impossible to set.

**Comment by Johni0702** [comment]
Can confirm, when increasing my render distance to 8, it'll crash with your test world.
