### ISSUE TITLE
freezing as soon as I light a portal

### ISSUE THREAD

**Issue by PradyunS** [Johni0702/BetterPortals#222]
log from multimc: https://paste.ee/p/AcS5W
BP version is 0.2.5

whenever i light a nether portal the game just freezes. no matter what i do. i have tried increasing the RAM, removing all mods except BP, and no matter what it freezes immediately, with no other option but to force close.

**Comment by Johni0702** [comment]
The log does not match your description. It has littletiles (and creativecore) installed and it shows you using the portal.
