### ISSUE TITLE
Game crashes when opening portal on occasion - ticking entity? 5g ram allocated

### ISSUE THREAD

**Issue by dictator135** [Johni0702/BetterPortals#234]
[crash-2019-08-10_07.24.56-server.txt](https://github.com/Johni0702/BetterPortals/files/3488782/crash-2019-08-10_07.24.56-server.txt)

**Comment by dictator135** [comment]
i thought it was a ram issue so i changed that but it continues to crash every other time i open a new portal

**Comment by dictator135** [comment]
https://prnt.sc/oqw376

**Comment by Johni0702** [comment]
This appears to be an issue with avatarmod, please report it on their issue tracker as well (and then link to it for future reference).
