### ISSUE TITLE
Twilight Forest compatability: Game crashes when entering the TF portal

### ISSUE THREAD

**Issue by Hyxaru** [Johni0702/BetterPortals#236]
With the latest official update from the twilight forest, I tried combining it with the latest version of better portals. As expected, there can be some compatibility issues.

Twilight Forest version 3.9.984
Forgelin 1.8.3
Betterportals 0.2.5

Attempting to do so got me the following crash:
[latest.log](https://github.com/Johni0702/BetterPortals/files/3489895/latest.log)

Disconnected from the issue, when trying to make the Twilight Portal render things on the other side like other portals, the Twilight Portal would have a minor issue. Unlike the other portals the Twilight Portal must always be made flat, and have a solid floor under the portal. Because of that you would never be able to see anything interesting through the portal. Maybe for the Twilight Portal specifically, it could render the other side like a mirror. Rendering things above the portal as if you were looking through it from below.

**Comment by Johni0702** [comment]
First one is https://github.com/Johni0702/BetterPortals/issues/143.

I don't quite understand the second issue. Yes, the TF portal is always on the ground but it doesn't link directly to the TF portal in the TF which would also be on the ground. Instead it links to a temporary portal placed slightly offset and significantly above the real one, so you should still be able to see other stuff through it.

**Comment by Hyxaru** [comment]
I heard from the TF team that better portals was recently compatible, but either mod updated and it broke. I expected the crash to maybe have a different root than #143
