### ISSUE TITLE
Game don't launch with BetterPortal 0.2.6

### ISSUE THREAD

**Issue by 6ix7even** [Johni0702/BetterPortals#238]
I want try your mod for see if my shader work with but the game crash with the la testes version

This is the log:
https://mega.nz/#!7hkHCYhT!AUY4o9wGJC_u_-QrS0ToMd_tvGCisLelqiQ-K187IAg

**Comment by Johni0702** [comment]
You're missing Forgelin: https://www.curseforge.com/minecraft/mc-mods/betterportals/relations/dependencies?filter-related-dependencies=3

Btw, don't use mega for log files, it's more of a hassle to open than it has to be. Use e.g. https://paste.dimdev.org/ instead.
