### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Blixtdraken** [Johni0702/BetterPortals#239]
My game just instant crash when I start the game 
[crash-2019-08-12_18.19.04-client.txt](https://github.com/Johni0702/BetterPortals/files/3493437/crash-2019-08-12_18.19.04-client.txt)
I do have other mods
![image](https://user-images.githubusercontent.com/53824895/62880935-e33bc080-bd2e-11e9-8555-60a6a3ee874c.png)
![image](https://user-images.githubusercontent.com/53824895/62880949-e8007480-bd2e-11e9-89b3-9a94249dd127.png)

**Comment by ThatDummGuy** [comment]
Im having this problem too, except the only mod I have in my mods folder is better portals

**Comment by Blixtdraken** [comment]
> Im having this problem too, except the only mod I have in my mods folder is better portals

You need go gte The ForgelIN mod
https://www.curseforge.com/minecraft/mc-mods/shadowfacts-forgelin

**Comment by ThatDummGuy** [comment]
> You need go gte The ForgelIN mod
https://www.curseforge.com/minecraft/mc-mods/shadowfacts-forgelin
 thanks a million!

**Comment by Johni0702** [comment]
@Blixtdraken There's a known issue with Valkyrien Warfare: https://github.com/Johni0702/BetterPortals/issues/179

**Comment by Blixtdraken** [comment]
ok thx
