### ISSUE TITLE
Optifine incompatible (crash on launch, mixin failure)

### ISSUE THREAD

**Issue by WenXin20** [Johni0702/BetterPortals#24]
Minecraft v1.12.2
Forge v14.23.5.2838
Better Portals v0.1.2

It crashes before the game is launched after pressing the green play button. The same happens with v0.1.1. A crash report didn't form, but here is the log:
[Crash Log](https://gist.github.com/WenXin20/b99a9eec751f55b4a0bfdc0d454da2a9)

**Comment by Johni0702** [comment]
Optifine is currently not supported, you'll have to remove it until that's fixed.
