### ISSUE TITLE
I can't see through the protals

### ISSUE THREAD

**Issue by TacoTurtlecomics** [Johni0702/BetterPortals#240]
I got the mod and tried it with the nether portal, i could not see through it, it was just the texture and the other side of the portal (over world not nether) this problem was the same with the other portals too. is optifine the problem?

**Comment by Johni0702** [comment]
> I got the mod and tried it with the nether portal, i could not see through it, it was just the texture and the other side of the portal (over world not nether) this problem was the same with the other portals too.

That sounds like you don't actually have the mod enabled. Make sure you do, e.g. try to build a flat nether portal.

> is optifine the problem?

It shouldn't but I wouldn't be surprised if some new OF version broke something. Remember that you can always just remove it to find out if it's relevant to the issue.

**Comment by TacoTurtlecomics** [comment]
I figured it out, I had the mod installed but my shaders broke it

**Comment by TacoTurtlecomics** [comment]
Apparently, Sildur's shaders is not better portals frendly.

**Comment by TacoTurtlecomics** [comment]
is there a shader pack that is better protals friendly?

**Comment by Johni0702** [comment]
No. Not with Optifine anyway. It doesn't support rendering multiple worlds and sp614x does not plan to support that any time soon. See https://github.com/sp614x/optifine/issues/2419.

**Comment by TacoTurtlecomics** [comment]
ok, thank you for helping me out! I really appreciate it!
