### ISSUE TITLE
ghost blocks

### ISSUE THREAD

**Issue by Blixtdraken** [Johni0702/BetterPortals#245]
In 0..2.6 latest version (as I write this)  there will randomly happen that when I make a portal(nether) the frame (out of obsidian) will be ghost blocks on the other dimension and not appearing until you try to do stuff in that area!
Edited*

**Comment by Johni0702** [comment]
I don't understand what you're saying.

**Comment by Blixtdraken** [comment]
> I don't understand what you're saying.

I've edit it now you may read!

**Comment by Johni0702** [comment]
What do you mean by `ghost blocks`?
The thing which is usually referred to as ghost blocks are blocks which exist on the server but not on the client or the other way around. They'll usually cause movement issues where you get stuck on seemingly nothing.

**Comment by Blixtdraken** [comment]
> What do you mean by `ghost blocks`?
> The thing which is usually referred to as ghost blocks are blocks which exist on the server but not on the client or the other way around. They'll usually cause movement issues where you get stuck on seemingly nothing.

Yes that is what happens Blocks are on the server but not on the client

**Comment by Johni0702** [comment]
I don't see any way of that happening. Are you sure that's what it is? Do you get teleported back when you try to walk into where the blocks should be? Do you have any other mods installed? Can you see any pattern to the randomness which might help reproduce the issue?

**Comment by Blixtdraken** [comment]
> I don't see any way of that happening. Are you sure that's what it is? Do you get teleported back when you try to walk into where the blocks should be? Do you have any other mods installed? Can you see any pattern to the randomness which might help reproduce the issue?

I will look into it in a short bit

**Comment by Blixtdraken** [comment]
it looks like it was casue iwas using wrong version of forge i used latest

**Comment by Johni0702** [comment]
I don't think so, I'm using 2838.

**Comment by Blixtdraken** [comment]
ok well i seems too be gone when i switched =/

**Comment by Blixtdraken** [comment]
and als ois there at the todo list to be able to make something like the glitch into a feature

**Comment by Johni0702** [comment]
I assume you're referring to https://github.com/Johni0702/BetterPortals/issues/231

**Comment by Blixtdraken** [comment]
GOOD
