### ISSUE TITLE
Portals Still Show

### ISSUE THREAD

**Issue by Spivyyy** [Johni0702/BetterPortals#250]
Got the mod working but, i could not see through the portals, i could walk through the portal with a 1 second loading screen, is this normal? or is there a setting a can change?

**Comment by Johni0702** [comment]
That sounds like the mod's not even installed.

**Comment by Johni0702** [comment]
Closing due to [lack of information](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
