### ISSUE TITLE
Twilight Forest portal doesn't work with non-grass frame

### ISSUE THREAD

**Issue by SDdevgame** [Johni0702/BetterPortals#253]
Portal shows up as the normal, non BP portal but doesn't work, it says
Couldn't find TF portal at PooledMutableBlockPos{x=-175, y=55, z=588} even though it was just created?

**Comment by Johni0702** [comment]
Please attach the full server log file.

**Comment by Dalethium** [comment]
[logs.zip](https://github.com/Johni0702/BetterPortals/files/3512610/logs.zip)
I've gotten a similar error, uploaded it for you.

**Comment by Johni0702** [comment]
Are there non-grass blocks in your portal frame? It looks like TF will form a portal with a dirt frame whereas BP currently requires grass.

**Comment by Dalethium** [comment]
I am pretty sure there was dirt, yeah
