### ISSUE TITLE
Game crashes when I add Betterportals to my mods.

### ISSUE THREAD

**Issue by ThatsFluke** [Johni0702/BetterPortals#254]
I add BetterPortals and launch forge and my game crashes. 
Forge/Minecraft version: 1.12.2
Mods:
Optifine 1.12.2 HD U E3

That's it.

**Comment by Johni0702** [comment]
You're missing Forgelin: https://www.curseforge.com/minecraft/mc-mods/betterportals/relations/dependencies?filter-related-dependencies=3

If you aren't missing Forgeline, then read this: https://www.chiark.greenend.org.uk/~sgtatham/bugs.html
