### ISSUE TITLE
Game crash while loading world

### ISSUE THREAD

**Issue by Raconteur32** [Johni0702/BetterPortals#256]
Here is my crash report. Hope you can help please :/ 

[crash-2019-08-18_01.03.55-server.txt](https://github.com/Johni0702/BetterPortals/files/3512444/crash-2019-08-18_01.03.55-server.txt)

**Comment by Johni0702** [comment]
Remove OTGCore or add OTG. See https://github.com/PG85/OpenTerrainGenerator/issues/234

**Comment by Raconteur32** [comment]
Thanks! A lot! Great mod.
