### ISSUE TITLE
better portals mod 1.12.2 entities rendered bug

### ISSUE THREAD

**Issue by CaptainPink** [Johni0702/BetterPortals#264]
[crash-2019-08-20_13.46.35-client.txt](https://github.com/Johni0702/BetterPortals/files/3522548/crash-2019-08-20_13.46.35-client.txt) there a few other mods in there but I looked into it I even just had better portals as the only mod and it did not work

**Comment by Johni0702** [comment]
You're missing Forgelin: https://www.curseforge.com/minecraft/mc-mods/betterportals/relations/dependencies?filter-related-dependencies=3
