### ISSUE TITLE
Player Model is Invisible in 3rd Person when Both Pixelmon and BetterPortals are Installed

### ISSUE THREAD

**Issue by BarbarianMatt** [Johni0702/BetterPortals#269]
When both Better Portals and Pixelmon Reforged are installed, the player is invisible in the 3rd person views.

**Comment by Johni0702** [comment]
BP changes 3rd-person mode to use a separate view entity which isn't the player. This is necessary to allow 3rd-person mode to work properly when sticking the camera through a portal.
Vanilla MC for some reason doesn't render the client player entity if it's not also the view entity and BP effectively removes that check: https://github.com/Johni0702/BetterPortals/blob/32baf18fc514d061cd63a6cc0a3846c7265e2f1f/src/view/java/de/johni0702/minecraft/view/impl/mixin/MixinRenderPlayer.java

Pixelmon Reforged does not provide any source code for me to look at ([according to their FAQ anyway](https://pixelmonmod.com/wiki/index.php?title=Frequently_asked_questions#How_do_I_access_the_Pixelmon_source_files.3F)), so I cannot check what they're doing that interferes with those changes. You'll have to open an issue on their issue tracker for them to look into it.

**Comment by BarbarianMatt** [comment]
Thanks for the helpful and quick reply!
