### ISSUE TITLE
end portal stopped working after I died in the end while fighting dragon

### ISSUE THREAD

**Issue by amplified1** [Johni0702/BetterPortals#270]

**Comment by amplified1** [comment]
relogging fixed it but it should still be looked into

**Comment by Johni0702** [comment]
Was your spawn anywhere close to the portal?

**Comment by amplified1** [comment]
no. very far. I did use waypoints to warp back though

**Comment by Johni0702** [comment]
This has a good chance of being fixed as of BP 0.3 (probably related to #281).
Please give it a try (assuming you can reliably reproduce it) and close this issue if it's indeed fixed.
If 0.3 does not fix the issue, simply reply so I know to take another look at it.
