### ISSUE TITLE
Breaks survival morph menu of metamorph mod

### ISSUE THREAD

**Issue by Asdi144** [Johni0702/BetterPortals#271]
I play with the [MetaMorph](http://www.9minecraft.net/metamorph-mod/) mod which gives me ability to change my character to other mobs, when passing a portal somehow my function to change my form disables when passing a portal, once i got stuck in enderman form.

Game log:
[launcher_log.txt](https://github.com/Johni0702/BetterPortals/files/3528776/launcher_log.txt)

**Comment by Johni0702** [comment]
Possible workaround:
- Press `N`
- Notice lack of morphs
- Use the `Show Favorites` button twice
- Notice morphs having re-appeared (`[` and `]` also start working again)

**Comment by realflow100** [comment]
Also causes glitches with changeling morph mod. Morph mod. and metamorph mod!
Metamorph and changeling mod have practically identical issues.
Some kind of incompatibility issues. could be on either mods end.
changeling mod seems to have the best features out of the three morph mod variations. but still has some issues with better portals mod for some reason.

**Comment by Johni0702** [comment]
This should be fixed as of Metamorph 1.1.9.

@realflow100 
Changeling is based on metamorph, so they can probably incorporate my fix for it without too much hassle.
iChun's morph mod is completely separate (afaik) and the issue with it is a known one: https://github.com/Johni0702/BetterPortals/issues/345. I have not yet looked into it but chances are it needs fixing in Morph, not in BP.
