### ISSUE TITLE
After Loading The World, I Am Able to See It For A Second Then The Screen Will Go Grayish Blue And Crashes The Game

### ISSUE THREAD

**Issue by Lenexus2118** [Johni0702/BetterPortals#272]
Here is my crash report.

[crash-2019-08-22_22.54.17-client.txt](https://github.com/Johni0702/BetterPortals/files/3533023/crash-2019-08-22_22.54.17-client.txt)

**Comment by Johni0702** [comment]
Update Forge.

**Comment by Lenexus2118** [comment]
Thank You. I thought I already did update forge but i guess i didn't. Love your mod.
