### ISSUE TITLE
We can use custom portals

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [Johni0702/BetterPortals#275]
![2019-08-24_12 17 39](https://user-images.githubusercontent.com/40109698/63631990-94185880-c669-11e9-9e08-f87fa7325015.png)
![2019-08-24_12 17 43](https://user-images.githubusercontent.com/40109698/63631991-94185880-c669-11e9-9297-a434c17d1fe7.png)
To make this, Create a portal(size/shape doesn't matter), then place a block inside near to portal teleportion using /setblock command, then break block(break inside portal that contains blocks and portal frame) and walia! the glitched portal! This is used as custom portals.

**Comment by Johni0702** [comment]
Beware that this is a bug and will be fixed eventually (probably in BP 0.4 or 1.0, whichever comes first). I'm keeping it alive though until there's an alternative.

Duplicated of #231

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
look, the core block got replaced with other blocks, without core block, the portal wont close up.
