### ISSUE TITLE
Consider adding Aether thing

### ISSUE THREAD

**Issue by Panduso** [Johni0702/BetterPortals#280]
You should consider adding like when you jump down from aether you fall straight down to overworld without a loading screen like when you go out of the end, so you cant go upwards to get to aether

**Comment by Johni0702** [comment]
I'd rather not introduce significant gameplay changes other than those required for the portal mechanic itself.

Also, I'd be surprised if there isn't already a mod out there which does something like that. BP tries to replace any third-party dimension change with its own loading-screen-less transition, so it might even work out of the box.
Once you've found such a mod, I may consider changing the transition for it from the current blobby thing to something better fitting with the downwards motion of the fall. In that case, open an issue specifically for that mod.
