### ISSUE TITLE
Unknown log spam issue.

### ISSUE THREAD

**Issue by border999** [Johni0702/BetterPortals#282]
MC Version: 1.12.2
BP Version:  0.2.6
It appears there is an issue between this mod, Cubic Chunks, and p455w0rdslib.
Though the issue of extreme lag was corrected by removing p455w0rdslib, the spam has only changed.
I will link a copy of the segment.
https://pastebin.com/Bdv3nR7b
Spam seems to happen in both CC worlds and vanilla, though I have not really checked the info for a vanilla variation.

**Comment by Johni0702** [comment]
The segment you posted can only happen with RandomThings installed. Please attach the full log.
I see no connection whatsoever with CC.

If the spam is different with p455w0rdslib, then please open a separate issue for it and attach the log there as well.
