### ISSUE TITLE
Game instantly closes. No crash report created.

### ISSUE THREAD

**Issue by EnderBro123** [Johni0702/BetterPortals#286]
Title says it all. Using the latest Forge along with the latest BetterPortals mod.

![image](https://user-images.githubusercontent.com/51277766/63722683-759c9380-c808-11e9-8055-988c376f3bb3.png)

![image](https://user-images.githubusercontent.com/51277766/63722720-8a792700-c808-11e9-8370-cf39b3c4cda6.png)

Mod's pretty much useless unless this is fixed.

**Comment by Johni0702** [comment]
1. You didn't attach any log
2. That's not the latest BP
3. You're missing Forgelin
4. Active Windows

**Comment by EnderBro123** [comment]
> 1. You didn't attach any log
> 2. That's not the latest BP
> 3. You're missing Forgelin
> 4. Active Windows

1. No log is given so I can't.
2. That's the latest file Curse gave me.
3. I didn't know that as the Relations tab doesn't list this.
4. No portals were created, as I can't even open my game.

**Comment by violetkitty87** [comment]
im having the same issue with betterportals version0.2.7

**Comment by Johni0702** [comment]
@violetkitty87 If you're having the same issue, then the same answer applies to you (specifically point 3). If you don't have the same issue, then read [this article](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html) and afterwards create your own ticket.
