### ISSUE TITLE
Game crashes as soon as it opens.

### ISSUE THREAD

**Issue by ThereIsNoSpoon99** [Johni0702/BetterPortals#289]
I only have the latest version of optifine and the Better Portals mod, and it crashes upon opening Minecraft.exe. Not even a world. The main menu doesn't have time to appear. I have tried it on the newest and the newest recommended versions of Forge. What is wrong?

**Comment by Johni0702** [comment]
You're missing Forgelin: https://www.curseforge.com/minecraft/mc-mods/betterportals/relations/dependencies?filter-related-dependencies=3

If that's not it, then you need to provide more information. Without the log, I can only guess.
