### ISSUE TITLE
Crash On Launch

### ISSUE THREAD

**Issue by sadaesthetic** [Johni0702/BetterPortals#292]
Made a Twitch modpack of just this mod, the most time it took to load was about 5 minutes to the title screen, and it crashes. The least time it took to load was about 10 seconds. Crash. The modpack is on the correct update of Java Edition Minecraft, Could this be a problem with Forge, Twitch, my PC, or all of the above?

**Comment by Johni0702** [comment]
You're missing Forgelin: https://www.curseforge.com/minecraft/mc-mods/betterportals/relations/dependencies?filter-related-dependencies=3
