### ISSUE TITLE
i opened a world,everything is dark (fixed)

### ISSUE THREAD

**Issue by NotDudidude** [Johni0702/BetterPortals#293]
hey, so im not new to betterportals but this new update (0.2.6) making some problems.
i opened a new world and all i saw is black.
i put optifine on the forge and still nothing.
then i turned off fast render and everything turned from black to white.
any way heres a screenie
![2019-08-28_11 26 34](https://user-images.githubusercontent.com/54620172/63838843-d0f49000-c986-11e9-9285-6e54868dc764.png)
![2019-08-28_11 26 50](https://user-images.githubusercontent.com/54620172/63838848-d3ef8080-c986-11e9-8c98-f30b5ce2e647.png)
hope you'll help me
cya

**Comment by Johni0702** [comment]
First, backup your whole .minecraft folder so you're able to reproduce the issue in case you accidentally fix it without known what you did.

Remove OF. If it happens without OF, then there's no reason to further complicate things by having it installed.
Fast Render is not supported anyway.

Which versions were previously working? Are they still working? Can you narrow down which specific version broke it for you?

**Comment by NotDudidude** [comment]
I think that was 0.1.6 somthing like that

**Comment by NotDudidude** [comment]
whelp anyway i removed optifine and now it works thenks anyway :)
