### ISSUE TITLE
abyssalcraft portals won't open

### ISSUE THREAD

**Issue by lag42** [Johni0702/BetterPortals#295]
if i use a gateway key from abyssalcraft 1.12.2-19.11 with betterportals 0.3.0 and forgelin 1.8.3 installed it just places down an empty frame, no portal

log [here](https://gist.github.com/lag42/88afa069e421754e059f316869ee2950)

**Comment by Johni0702** [comment]
Oops, looks like I left a reference to The Aether code in the AbyssalCraft code, so it'll only work if The Aether is installed as well.
I'll push out 0.3.1 in a few minutes.
