### ISSUE TITLE
Crash when moving away from portal

### ISSUE THREAD

**Issue by Pear120** [Johni0702/BetterPortals#297]
Game functions fine when in front of an active Nether portal. Was able to break a block of dirt with a torch on it and have the torch drop. Moving a few chunks away from the portal (unsure if it's still in render range or not) causes blocks to not update properly - breaking dirt with a torch on it causes the torch to remain. Around this time, the game stops responding, resulting in a "timed out" disconnect.

**Comment by Pear120** [comment]
[latest.log](https://github.com/Johni0702/BetterPortals/files/3557624/latest.log)
Log didn't attach for first post.

**Comment by Johni0702** [comment]
You've got quite a few third-party mods installed, most of which are probably unrelated to the issue but overall they cause the log to be rather noisy and make it difficult to tell what's going on.
Remove all mods which aren't required to reproduce the issue and make sure the remaining ones are up-to-date.

**Comment by Pear120** [comment]
[Here's a more trimmed log.](https://pastebin.com/RB846ddi) The portal behaved fine from the start, it rendered the Nether at 19:01, and I remained near it for about 5 minutes testing with block updates. After a time, I had moved away from it and the blocks stopped updating when I tested with a torch. At 19:10 the game stopped responding entirely. I closed it before getting the "timed out" disconnect message.

**Comment by Johni0702** [comment]
Try updating littletiles and creativecore to the versions listed here: https://github.com/CreativeMD/LittleTiles/issues/237

If that's not it, then I've got no clue and you need to start removing mods (hint: removing half of all mods at a time will get you there significantly faster than removing one at a time).

**Comment by Johni0702** [comment]
If it isn't littletiles, there's also a good chance that this has been fixed in BP 0.3, so you should give that a try as well.

If either of those fixes the issue, then please close it.

**Comment by Pear120** [comment]
Okay, I've been testing it for the past two days just to be sure, but updating those two mods fixed it, and I haven't had a single crash since. I'm experiencing some weird flicker with rain now (from Dynamic Surroundings), but it doesn't crash and there's nothing in the logs.
