### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Warrock3280** [Johni0702/BetterPortals#300]
[Minecraft crashes on startup.](https://gist.github.com/Warrock3280/57d7a2fcf01d0b3f52d8a7c2fce5b8f2)
Looks like Mekanism compatibility issue.
Better Portals: 0.3.2
Mekanism: Mekanica 1.2.0

**Comment by Warrock3280** [comment]
Switching Mekanism to 9.8.1.383 (Main fork) seems helped.

**Comment by Johni0702** [comment]
Mekanica is not Mekanism. It's based on a fairly old version of Mekanism with substantial difference to the one supported by BP.
