### ISSUE TITLE
Two screens appear

### ISSUE THREAD

**Issue by Null500zeep** [Johni0702/BetterPortals#301]
When I lit the portal, two screens appeared, the same with the portal in the end, I failed with Optifine and without
![2019-08-30_18 18 43](https://user-images.githubusercontent.com/50259711/64030515-2d5ed780-cb60-11e9-9760-02d77cdfdd38.png)
![2019-08-30_18 40 21](https://user-images.githubusercontent.com/50259711/64030518-2d5ed780-cb60-11e9-9ae8-47ed92212bb0.png)

**Comment by Johni0702** [comment]
You have debug view enabled (`Mod Options` → `BetterPortals` → `Config` → `Debug View`). Do you not remember enabling it?
