### ISSUE TITLE
Bugs I have encountered in first 5 minutes

### ISSUE THREAD

**Issue by BoobieWoobie** [Johni0702/BetterPortals#308]
My draconic reactor (Draconic Evolution mod) which was in the nether renders in the overworld with animations and sound.

Chests (Maybe also vanilla chests?) (Specifically Millenaire mod) swapped my inventory with the chests contents, chest also doesnt open. (Idk how this happened)

Optifine likes to break portal guns rendering, not your problem.

**Comment by Johni0702** [comment]
Please open a separate issue for each bug you encounter so one can deal with them separately.
I've split them into #309 and #310. Please answer my questions over there.

If you think there's any action that should be taken by BP with respect to the OF+portalgun issue, then please open a separate issue for it as well and explain it in more detail.
