### ISSUE TITLE
weiss albedo and albedo compact crashes

### ISSUE THREAD

**Issue by SpGilbert** [Johni0702/BetterPortals#314]
https://paste.dimdev.org/iqopowehux.mccrash
https://paste.dimdev.org/zozocisuce.mccrash

**Comment by SpGilbert** [comment]
Not sure if this is tied to the albedo crash from before #120 or if it is albedos end on another mod

**Comment by Johni0702** [comment]
Those look like version mismatch issues (make sure the weiss version is compatible with the albedo version you've got installed). Doesn't look at all related to BP.

I've yet to receive any feedback on the bugs I've reported to albedo back then and iirc those issues were so severe that I'm not prepared to looking into albedo-related issues until they're fixed.

**Comment by SpGilbert** [comment]
ok will check
