### ISSUE TITLE
Server crashes When a user attempts to join without a required mod

### ISSUE THREAD

**Issue by lukemeow** [Johni0702/BetterPortals#316]
I am running a spongeforge server on 1.12.2 (EDIT) but this also happens with a forge server (tested forge: 1.12.2-14.23.5.2838 and  1.12.2-14.23.5.2844)
while testing various things, I noticed that the server would crash when a player attempted to join without a required mod https://pastebin.com/Ay3AmjJM

after more testing I noticed
Without betterportals, it would kick players fine without crashing the server.

This crash is an issue for me because it means anyone could at any time crash my server by trying to connect with a missing mod

For my tests i used the TreeCapitator mod as the mod the server had which the client did not, but i would assume other required mods would also result in the same issue. (EDIT) Also tested with the Clumps mod with the same result

**Comment by Johni0702** [comment]
Is spongeforge a requirement for this crash or does it happen without it as well?

**Comment by lukemeow** [comment]
ah sorry, did more tests, without sponge

Turns out this also happens without sponge on the default forge server, so not really a sponge incompatibility, it is just something that happens on servers

**Comment by lukemeow** [comment]
I also tested with another mod instead of treecapitator.
Test mod was called clumps. did test the same way by giving it to server and not client, and resulted in the same crash when the player was rejected from joining
