### ISSUE TITLE
PortalGun Render Bug

### ISSUE THREAD

**Issue by Traincrafter111** [Johni0702/BetterPortals#318]
Hi I installed this mod  and portal gun but I have the problem that inside my portal of portal gun only a few blocks render heres a screenshot
![2019-09-05_09 55 31](https://user-images.githubusercontent.com/44734869/64353904-1981fe00-cfc4-11e9-836c-5f8dda82a6dd.png)
The only mods I have installed are BP PortalGun and optifine

**Comment by Johni0702** [comment]
Which version of BP?
Which version of PortalGun?
Remove Optifine. No need to make stuff more complicated than it has to be.

**Comment by Traincrafter111** [comment]
BP 0.2.7
PortalGun 7.1.0
But I have solved It is a optifine incompatibility with PotralGun sorry for bothering
