### ISSUE TITLE
Better Portals Launch Crash

### ISSUE THREAD

**Issue by SolSavvy** [Johni0702/BetterPortals#319]
Minecraft Version 1.12.2

Forge Version: 14.23.5.2821

Crash report:
  The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer

**Comment by Johni0702** [comment]
You're missing Forgelin: https://www.curseforge.com/minecraft/mc-mods/betterportals/relations/dependencies?filter-related-dependencies=3

**Comment by SolSavvy** [comment]
Thank You
