### ISSUE TITLE
Weird texture when looking into portals

### ISSUE THREAD

**Issue by Cooke1000** [Johni0702/BetterPortals#320]
![2019-09-05_17 27 31](https://user-images.githubusercontent.com/54952808/64360937-6afdad80-d003-11e9-8a90-3d7b238282a2.png)

**Comment by Cooke1000** [comment]
That's my screen when I look into a portal

**Comment by Cooke1000** [comment]
Also it doesn't seem like it wants to work on twilight portals
![2019-09-05_17 39 48](https://user-images.githubusercontent.com/54952808/64361248-2c1c2780-d004-11e9-8f3c-3ba6aa9ffb07.png)

**Comment by Johni0702** [comment]
You have enabled the "Debug View". Did you not configure this yourself?
Given you appear to be unaware of your config file, make sure TF portals are actually enabled.

You should also read [this article](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by Cooke1000** [comment]
ahhh

**Comment by Cooke1000** [comment]
I must have enabled that my accident 
sorry for wasting your time dude. I feel stupid now

**Comment by Johni0702** [comment]
Also, if that's a pre-existing TF portal, you must touch it once before it's converted into a BP one.

**Comment by Cooke1000** [comment]
Ah thanks :D
