### ISSUE TITLE
Jumped through TF portal now whenever i try and join game it crashes

### ISSUE THREAD

**Issue by Cooke1000** [Johni0702/BetterPortals#321]
I jumped into my twilight forest portal now it crashes me whenever I try and join my own server. Here is the crash log.

[crash-2019-09-05_23.09.18-client.txt](https://github.com/Johni0702/BetterPortals/files/3581399/crash-2019-09-05_23.09.18-client.txt)

**Comment by Cooke1000** [comment]
Just to make 100% sure that it was the TF portal I went to a perious backup where it worked and jumped into the TF portal again and it crashed

**Comment by Johni0702** [comment]
Update TF.
