### ISSUE TITLE
Portals become Non-Functional When Leaving Dimension Through other Means

### ISSUE THREAD

**Issue by Leafygreens97** [Johni0702/BetterPortals#322]
Whenever you seem to leave a dimension through non-"conventional" means - such as dying or in the case of the Aether, falling into the void - and you immediately load the portal to enter such dimension after doing so, the portal for such dimension becomes non-functional entirely. The portal blocks are solid and no longer transparent, as shown here:
![2019-09-05_17 54 34](https://user-images.githubusercontent.com/26660001/64391912-bd40cd80-d007-11e9-878d-1b555f5311aa.png)

![2019-09-05_18 08 22](https://user-images.githubusercontent.com/26660001/64392035-3e986000-d008-11e9-967f-d48c30a0f424.png)

 In one case I even managed to somehow make the Aether portal open in the Aether facing a different compass direction than it should have, and it caused this to happen:
![2019-09-05_17 29 34](https://user-images.githubusercontent.com/26660001/64391917-c6ca3580-d007-11e9-8e14-c3e862a00ed0.png)

Another note - I don't know if it's just a caveat of the Aether or what, but the compass directions just don't seem to line up well when making portals to its dimensions. This may have been the cause of the previous image. You can see it in action here:
![2019-09-05_17 47 17](https://user-images.githubusercontent.com/26660001/64392070-64256980-d008-11e9-8af4-decf0ee2d2ce.png)

![2019-09-05_17 47 21](https://user-images.githubusercontent.com/26660001/64392078-6a1b4a80-d008-11e9-8426-5a207f85123f.png)

The issue was tested both with and without Quark, and with all 3 portals - Nether, Aether, and End. Logging out/logging back in seems to fix the problem, but it's kind of annoying to have to do that especially in the case of the Aether since it's so easy to accidentally leave it in the "wrong" way.

Just to make it clear, I tested this With only BP, The Aether, and Quark installed.

I do have to say though, great job with this mod, man. I never thought something like this would ever be possible in Minecraft, let alone in such a seamless and efficient way. Keep up the good work!

Edit: changed my mind, now 2 separate issues.

**Comment by Leafygreens97** [comment]
After toying around with it some more, the compass direction seems fixed. I don't know how I fixed it and I can't seem to reproduce whatever I did to make it all out of whack. Also, the portal can become functional again if you break and then reopen it rather than logging in. But, it gives a sort of rubber-banding effect when trying to enter the dimension, but not when trying to leave it. I also noticed that sounds I make seem to play over themselves while doing this. If I repeat the loop of leaving the "wrong" way and then re-entering by closing and then reopening the portal, the sounds for breaking and placing blocks seem to play over the same amount of times I've done the loop. So, if I do the loop once, it plays over twice. Loop it twice, it plays 3 times. One time for the normal behavior, another for each loop performed.

However, after attempting this loop for a 3rd time, the sounds returned to normal but then this happened...
![2019-09-05_19 06 27](https://user-images.githubusercontent.com/26660001/64393827-87541700-d010-11e9-9eb5-86c4fe5b30b9.png)

![2019-09-05_19 07 11](https://user-images.githubusercontent.com/26660001/64393831-8b803480-d010-11e9-929c-87bbcb9ed11b.png)

BUT then after relighting the portal after that, the sounds starting playing over - 4 times now. 1 for normal and 3 for 3 loops. I have no idea what is going on here. If you would like me to make a video showing the process I could do that if I didn't explain it well enough

**Comment by Johni0702** [comment]
This should have been fixed in 0.3.
Related: #281

The different compass directions are intentional. It allows a newly lit portal to find a fitting pre-built frame of any rotation (far more relevant for nether portals than for aether portals).
If there isn't any pre-built frame around, then it chooses a pseudo-random orientation based on the coordinates.

**Comment by Leafygreens97** [comment]
Ah, I wasn't trying this in 0.3. However, trying this in 0.3.2, the issue is definitely fixed when dying. However, in the case of the Aether, there is still some problem when you fall into the Aether void, thus getting teleported back to the Overworld. Often times I would be stuck at the max build limit - y 256 - unable to do anything except move my camera. Using /kill resulted in this crash: 
[crash-2019-09-06_13.05.10-server.txt](https://github.com/Johni0702/BetterPortals/files/3585406/crash-2019-09-06_13.05.10-server.txt)

Other times it would instead crash immediately after teleporting me back into the Overworld. Logging back into that world would cause me to appear below bedrock for some reason, but everything else would be back to normal. Here is the crash log for that instance, although it seems to be the same error:

[crash-2019-09-06_12.59.28-server.txt](https://github.com/Johni0702/BetterPortals/files/3585411/crash-2019-09-06_12.59.28-server.txt)

**Comment by Johni0702** [comment]
Incorrect behavior on death in the aether (or cross-world teleportation with loading screen in general) is a known issue tracked as part of #326.
