### ISSUE TITLE
Game crashes while initializing.

### ISSUE THREAD

**Issue by RadicalZoey** [Johni0702/BetterPortals#324]
> The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer

I only have this mod installed and when I launch the game it will popup, start doing the mod loading forge does, and then shut down with the crash report I have attached. Cheers!
[crash-2019-09-05_20.13.45-client.txt](https://github.com/Johni0702/BetterPortals/files/3581780/crash-2019-09-05_20.13.45-client.txt)

**Comment by PatentedSugar9** [comment]
I had the same issue. Noticed that Shadowfacts' Forgelin is a required dependency, and installing it fixed it for me.
