### ISSUE TITLE
Compatibility issues (Various mods with dimensions or cross dimension teleportation)

### ISSUE THREAD

**Issue by lukemeow** [Johni0702/BetterPortals#326]
Was testing a bunch of dimension mods to see what worked.

All mods were tested alone with only better portals and it's dependency installed
I only tested Atum on a server, the rest were in single player

Atum - Crashes when entering their portal. would crash server if done on server
     https://www.curseforge.com/minecraft/mc-mods/atum
Error Log: https://pastebin.com/aN1NT6Fn

The in betweenlands mod - Crashes when entering their portal
     https://www.curseforge.com/minecraft/mc-mods/angry-pixel-the-betweenlands-mod
Error Log: https://pastebin.com/tVeh4J2V

The Aether - Crashes when falling out of the world in the aether. also standing portals take very long to spawn compared to flat ones. https://imgur.com/a/mynDcxn (EDIT: i retested the portal taking awhile a couple time, and it seemed normal in follow up tests so i am not sure exactly what happened)
     https://www.curseforge.com/minecraft/mc-mods/the-aether
Error Log: https://pastebin.com/hk7bPhdB

The Twilight Forrest - Seems to work fine. killing myself did lock the portal for a minute, and originally the portal spawned like https://imgur.com/a/LbLpTiQ which was kinda interesting, but from what I can tell with quick tests, it seems to work fine

AbyssalCraft - All portals working fine and dying also works fine

YAMDA - rightclicking on the portal block teleports the player, but they end up in an empty world. because the player was able to teleport without crashing, i tried pregenerating the world without better portals, then retrying with better portals, but even if the world is generated, better portal still sends them to a blank world just suspended in place.
In addition, if the player exits and rejoins while in the blank world, they will spawn in the YAMDA world and it looks like it should, but attempting to leave will crash the game
Error Log: https://pastebin.com/05t5UbZf

Also tested a mod that doesn't add new dimensions, but lets people teleport to already existing ones called Telepad. teleporting between the nether and overworld results in a crash.
https://pastebin.com/AeiDqTtt

I believe this issue will occur in most things that teleport a player to another dimension.

would be cool if you could work out a way to solve this so teleports and dimensions can still handle their own teleports, without you having to officially support each individual one. especially because some don't have a portal at all

anyway i hope this list helps in some way, ill be happy to assist/give more info if required.

**Comment by Johni0702** [comment]
From looking at the crash reports, there appear to be two distinct issues:
1. Atum and Betweenlands
2. Aether, YAMDA and Telepad

Have you disabled the "Enhance third-party transfers" setting? It appears to be disabled or not working for some other reason in issue 1 (unclear for 2).

There shouldn't be any difference between flat and standing portals. If it's reproducible, please open a separate issue for it.

**Comment by lukemeow** [comment]
I set B:"Enhance third-party transfers"=false while testing atum, but it still crashed, all the rest it was set to true.

just tested with Betweenlands again both true and false, but the logs are pretty much the same  https://pastebin.com/Q6D5zWnc
https://pastebin.com/zEFiYLtd
