### ISSUE TITLE
The game crashed whilst initializing game Error

### ISSUE THREAD

**Issue by Shadowkiller324** [Johni0702/BetterPortals#328]
The game keeps crashing on launch
[crash-2019-09-06_04.54.02-client.txt](https://github.com/Johni0702/BetterPortals/files/3583395/crash-2019-09-06_04.54.02-client.txt)

**Comment by Johni0702** [comment]
You're missing Forgelin: https://www.curseforge.com/minecraft/mc-mods/betterportals/relations/dependencies?filter-related-dependencies=3
