### ISSUE TITLE
Can't see through Portals while using shaders

### ISSUE THREAD

**Issue by RANDOM800** [Johni0702/BetterPortals#329]
Can't really show it cause my computer is refusing to printscreen it but while using shaders you can't see through the portals like it's supposed.
![Captura de Ecrã (19)](https://user-images.githubusercontent.com/35608101/64425615-1bbb8980-d0a4-11e9-8dd0-1572311f660b.png)
_**LIST OF MODS**_
**_LIST OF SHADERS TESTED_**
Sildur's Enhanced Default
Sildur's Vibrant Shaders (Lite, Medium and High)
SEUS (Low and Medium)
Chocapic's Enhanced Default
Chocapic's (Low, Medium and High)

**Comment by Johni0702** [comment]
Working as intended. Optifine's Shader implementation doesn't support rendering of multiple worlds, hence BP disables its see-through portals when it detects that shaders are enabled.
