### ISSUE TITLE
Nested portal views are not rendered

### ISSUE THREAD

**Issue by InsomniaKitten** [Johni0702/BetterPortals#33]
**Better Portals version:** [0.1.3](https://minecraft.curseforge.com/projects/betterportals/files/2717887)

When portals are nested physically, the inner portal views visible through a portal view are not rendered... I'm sorry, I had to mention it; you know it was only a matter of time before someone asked for a lag machine. 😜 	

![Screenshot of nested portal view](https://i.imgur.com/6TyJ22U.png)

**Comment by UpcraftLP** [comment]
could probably have a config option for the maximum number of nested portals to render ;)

**Comment by Johni0702** [comment]
Nested portals should already work on the rendering side of things.
The main issue with them currently is that they might keep themselves loaded in subtle ways even if the player walks away. I haven't though about the details of whether that's actually the case nor how to fix it, instead I've just disabled them for now.

**Comment by Johni0702** [comment]
Well, this is your fault. BP 0.2 supports recursively rendering portals and now #123 is a thing.
