### ISSUE TITLE
Help with a crash log?

### ISSUE THREAD

**Issue by LilyArlatto** [Johni0702/BetterPortals#331]
So yes, I'm using a big modpack, and I just threw in better portals because I remembered I wanted to try it but it won't launch now (it launched before). You can go ahead and tag this with too many mods if you'd like, but I just want to see if someone can decode this crash report.
[latest.log](https://github.com/Johni0702/BetterPortals/files/3585776/latest.log)

EDIT: I also just realized I should list some other info.
I'm on Minecraft version 1.12.2, using better portals 0.2.7.
I'm using a modpack on the Twitch desktop app called Hexxit Updated by HaoShern.
I added 2 mods as well, OptiFine (HD U E3), and ImmersiveEngineering (0.12-91)

**Comment by Johni0702** [comment]
You're missing Forgelin: https://www.curseforge.com/minecraft/mc-mods/betterportals/relations/dependencies?filter-related-dependencies=3
