### ISSUE TITLE
Crash when starting Minecraft

### ISSUE THREAD

**Issue by aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaae** [Johni0702/BetterPortals#334]
[crash-2019-09-07_20.44.22-client.txt](https://github.com/Johni0702/BetterPortals/files/3587195/crash-2019-09-07_20.44.22-client.txt)

**Comment by lukemeow** [comment]
I am not the dev, but I noticed you are not using forgelin which is required by this mod to work, could try adding that and see if it solves your problem
