### ISSUE TITLE
Aether 2 portals not compatible with Enhance third-party transfers

### ISSUE THREAD

**Issue by lukemeow** [Johni0702/BetterPortals#336]
There are 2 main issues i have found with Aether 2 portals.

1) standing in a portal while it loads, can also happen if you are teleported to standiing in the portal when returning from the aether. The blue teleport effect will persist, so your screen will become more blue depending on duration inside the portal. this can be hard to replicate at times because it requires you to stand in the portal which is harder to do when using only better portals and aether 2. (is easier with many mods) the easiest way to replicate i found is to end up in the portal when leaving the aether
Also the only ways i have found to remove the blue effect is by dying, i usually use /kill or by leaving the game https://imgur.com/a/gNIaOkz

2) the aether 2 uses quick teleports with better portals this makes them nearly instant, so you can teleport between the aether and overworld very quickly. (also happens with other portals that use this like in the betweenlands mod)

however if you teleport to another dimension while the Enhance third-party transfers is active, it crashes the client this happens both entering and leaving the aether, as well as leaving and reentering.

what happens is it plays the animation, then will restart the animation while the first is still playing, then crash mid way through

https://pastebin.com/gUyy7dE9

both of these are only when Enhance third-party transfers is set to true, if it is false it isn't a problem. 1 may still be a problem if the player manages to somehow end up in a portal after teleporting, but it is a lot harder, maybe impossible when Enhance third-party transfers is false

**Comment by Johni0702** [comment]
I've split off the crash when two transitions are overlapping into #339.

Reproducing 1 is actually trivial if one has a debugger at hand and can just pause the (integrated) server while keeping the client running. I'm currently looking into whether that's BP's fault and/or where it should be fixed.

Btw, is there some way to have two aether portals link to each other or will they always link to the fireplace? (asking mainly for #235)

**Comment by lukemeow** [comment]
from what i can tell the portal will always teleport you to the building with the fire in it, and you can't create a returning portal when there, so if you wanted to make a portal which works like your other portals, you would probably have to do it similar to the end portal one, so it is one way only

another option is to spawn a working portal that overrides their default, but that may be more trouble

**Comment by Johni0702** [comment]
I'm getting the blue portal overlay even without BP:
1. Remove BP
2. Create new flat world (creative mode)
3. Build quartz portal
4. Switch to survival
5. Stand in portal for a second and leave before you're teleported
6. Overlay persists until respawn

**Comment by lukemeow** [comment]
ah cool, will have to see if they will fix it then, I let them know about it anyway so will have to wait and see.

**Comment by lukemeow** [comment]
seems they had already solved it but was only in a version on their jenkins
it is https://jenkins.gildedgames.com/blue/organizations/jenkins/The-Aether-II/detail/1.12.2/131/artifacts/ for future reference

if the link doesn't work might have to try again like i did
or can try https://jenkins.gildedgames.com/blue/organizations/jenkins/The-Aether-II/activity/

at the time of righting this it is the latest 1.12.2 version run 131
