### ISSUE TITLE
Graphical Glitch When using Better portals with Dynamic surroundings mod (incompatibility))

### ISSUE THREAD

**Issue by lukemeow** [Johni0702/BetterPortals#340]
okay this is a weird one, and really i have no idea if you will be able to solve it

in singleplayer i tested with the dynamic surroundings by itself, with a heap of other mods, then with better portals. it only does it when it is paired with better portals.

ISSUE: when both these mods are together AND it is raining AND a portal is open nearby. the rain will glitch and flash, along with distant land, it seems to be more noticeable with the end portal.

Made an unlisted video so you can see the issue first without having to create a test environment just to get an idea https://youtu.be/pZzKiVWXufo

**Comment by Johni0702** [comment]
DynamicSurroundings assumes there to only be one world on the client and gets confused when there are multiple.
I've already reported this on DS's issue tracker a few months ago but it seems like DS is currently lacking an active maintainer: https://github.com/OreCruncher/DynamicSurroundings/issues/476

**Comment by lukemeow** [comment]
yeah i noticed they haven't really been doing much, some people were saying it is dead. hope something can be worked out, but i may have to drop it if it is going to cause problems.

thanks for the heads up
