### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by thatonepuggo** [Johni0702/BetterPortals#342]
when i try to startup forge 1.12.2 (heres the entire name 
![image](https://user-images.githubusercontent.com/42193477/64498249-aad1c880-d281-11e9-8983-6f43052ae240.png) ) i get a crash like this when i have the jar file in the mods folder 
![image](https://user-images.githubusercontent.com/42193477/64498313-f7b59f00-d281-11e9-9f28-8efe736834c3.png) 
can somebody please tell me how to fix it? this only happens when i have the mod in the forge mod folder

**Comment by Johni0702** [comment]
You're missing Forgelin: https://www.curseforge.com/minecraft/mc-mods/betterportals/relations/dependencies?filter-related-dependencies=3
