### ISSUE TITLE
Crash when rendering Astral Sorcery's Custom sky (Aether)

### ISSUE THREAD

**Issue by rmrocks01** [Johni0702/BetterPortals#344]
https://pastebin.com/5VPnnaaV

optifine and aether also installed, but determined not to be the issue

**Comment by rmrocks01** [comment]
closed because i am opening a better formatted issue

**Comment by rmrocks01** [comment]
Briefly closed it as I was trying to recreated it with the Nether. (Unsuccessful)
should be noted that crash occurred within the Aether and wasn't resolved until Astral Sorcery was disabled.

**Comment by Johni0702** [comment]
The crash as shown in the crash report is literally impossible without optifine (it crashes right inside of one of OF's methods). Please remove it and post one where OF isn't installed.

**Comment by rmrocks01** [comment]
Hmm must be a weird conflict with all 3 mods because I cannot recreate it whilst missing one. I'm closing this until I am able to recreate it without OF

**Comment by rmrocks01** [comment]
also thx for being a active dev <3
