### ISSUE TITLE
The game crashed while running very fast in a portal

### ISSUE THREAD

**Issue by bobodoustaud** [Johni0702/BetterPortals#346]
simply run very fast in a portal and having a render distance of 2 (i used super lubricant boots from random thingsto go veeeery fast)

The game crashed whilst batching chunks
Error: java.lang.NullPointerException: Batching chunks

crash report : https://pastebin.com/z24zZrjT

logs : https://pastebin.com/gcz2CkPM

p.s. : German?

**Comment by bobodoustaud** [comment]
the bug re-happened but with walking normally into it. it have made a bugged chung who items and the portals aren't rendered

**Comment by Johni0702** [comment]
Based on the crash report, this looks to be a piece of vanilla code which isn't thread-safe when multiple worlds exist. I.e. there's a tiny chance of it randomly happening every tick which happens between your client using the portal and the server acknowledging that change.
The more ticks between those two things, the higher the chance of the crash happening on every portal usage (but the chance is still tiny).
The crash report should be sufficient for me to fix it, even if I'm unable to reproduce it.

Just to be sure that it's actually the same thing, could you please post the other crash report as well?

**Comment by bobodoustaud** [comment]
https://pastebin.com/gbzQ9zqa

it's looks to be the same
