### ISSUE TITLE
Optifine and Fast Render

### ISSUE THREAD

**Issue by Alifolie** [Johni0702/BetterPortals#348]
Hi, I found a bug. 

https://youtu.be/htHyVQ7g8RQ

I used Minecraft 1.12.2 Forge 14.23.5.2838

**Comment by Johni0702** [comment]
The fact that BP doesn't work with OF's "Fast Render" option is known and stated on BP's CurseForge page.

Given OF doesn't provide any source code, it's hard to say why it doesn't work.
I've previously requested more information from OF's author on what exactly the "Fast Render" does and one of the things they told me (skipping framebuffers) is fundamentally incompatible with how portals work, so I do not plan to look into this any further.
