### ISSUE TITLE
Crash on death and when clicking respawn button

### ISSUE THREAD

**Issue by alexrsagen** [Johni0702/BetterPortals#349]
Sorry in advance about there being a lot of mods here. At least I'm on the currently latest version, 0.3.4.

Issue looks related to #339 but that should have been fixed in c34a473...

Crash report: https://gist.github.com/alexrsagen/139aa3bebab64bd5d73940053d540c0e

**Comment by Johni0702** [comment]
Reproducible with just BP:
1. Create new flat world
2. `/forge setdim @p -1`
3. `/kill`
4. Click Respawn
5. Crash if 2-4 happens quick enough (easily possible when increasing transition duration to >10 seconds)
