### ISSUE TITLE
Rendering weirdness when standing between two portals in 3rd person

### ISSUE THREAD

**Issue by InsomniaKitten** [Johni0702/BetterPortals#35]
**Better Portals version:** [0.1.3](https://minecraft.curseforge.com/projects/betterportals/files/2717887)

When standing between two portals in third-person view, with the camera oriented through one of the portal frames, the view shifts and transforms in weird ways as the camera is moved around within the bounds of the frame.

![Recording of bug](https://thumbs.gfycat.com/OrnateLikelyAustraliankelpie-size_restricted.gif)

**Comment by InsomniaKitten** [comment]
More test footage: https://streamable.com/zsqo1

**Comment by Johni0702** [comment]
This should also happen with a single portal, not sticking the camera through, just whenever there's blocks which pull the third person camera closer in one world but not in the other.

There's also another bug featured in the gif: #39

**Comment by Johni0702** [comment]
Should be fixed by f6cd259216c63bfb2db944323755c969a3234324 (once 0.2 lands).
