### ISSUE TITLE
Cross Reference Crash with Enderio Telepad

### ISSUE THREAD

**Issue by tyler489** [Johni0702/BetterPortals#350]
Reported to Enderio crash when using Enderio's Teleporter to move from an overworld to the nether or end 

> #### Issue Description:
> Telepad crashes Server and Client using it.
> 
> #### What happens:
> After teleporting to the location the Server crashes and so does the Client who used the teleporter. Nobody else on the server crashes.
> 
> #### What you expected to happen:
> The Client to teleport to the location safely.
> 
> #### Steps to reproduce:
> 1. Set the coordinates to the Telepad to a different dimension.
> 2. Use the Telepad
> 3. After about 2 seconds they crash
> 
> #### Affected Versions (Do _not_ use "latest"):
> * EnderIO: 5.0.50
> * EnderCore: 0.5.69
> * Minecraft: 1.12.2
> * Forge: 1.12.2 14.23.5.2846
> * SpongeForge: spongeforge-1.12.2-2838-7.1.7-RC3910
> * Optifine: HD_U_E3
> * On a Server
> 
> #### Your most recent log file where the issue was present:
> https://pastebin.com/fURdHz3r

https://github.com/SleepyTrousers/EnderIO/issues/5243

**Comment by Johni0702** [comment]
Could you please check that this is an issue in singleplayer as well?
And that it also happens without all the other mods? (especially without Sponge)
