### ISSUE TITLE
Idea : Opposite Dimensions Portals Exist

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [Johni0702/BetterPortals#353]
yeah, Opposite Dimensions portal exist. the stupid pesky loading is unavoidable!
https://www.curseforge.com/minecraft/mc-mods/opposite-dimensions

**Comment by Johni0702** [comment]
The mod's license is "All Rights Reserved" and as such does not allow me to support it in BP. They don't even provide any source code.

For non-trivial integrations, I'll generally only consider mods which are released under a GPLv3-compatible license (e.g. one of [these](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses)).
