### ISSUE TITLE
Exception in server tick loop: using version 0.3.4 on minecraft 1.12.2

### ISSUE THREAD

**Issue by darkshadow1809** [Johni0702/BetterPortals#354]
Crash randomly happened, not sure what happened.

[crash-2019-09-15_01.21.37-server.txt](https://github.com/Johni0702/BetterPortals/files/3613622/crash-2019-09-15_01.21.37-server.txt)

**Comment by Johni0702** [comment]
Most likely caused by the same bug as #350 (can occur on any chunk load, not just with the enderio teleporter).
