### ISSUE TITLE
de.johni0702.minecraft.view.impl.server.ServerWorldsManagerImpl.tick(ServerWorldsManagerImpl.kt:410)

### ISSUE THREAD

**Issue by xamareik** [Johni0702/BetterPortals#355]
My server is crashing and someone on [r/moddedminecraft](https://www.reddit.com/r/ModdedMinecraft/comments/d4mm8k/1122_keeps_crashing_on_a_custom_modpack/) told me the title.

**Comment by Johni0702** [comment]
Thanks for the report.

Based on the crash report you posted on reddit, this is likely the same thing as #350 (EnderIO isn't a requirement for the issue, it's just one way of causing it, you seem to have discovered another one).
I'm closing this issue in favor of that other one. You can subscribe to the other issue to get notified when it's fixed.
