### ISSUE TITLE
Client thread parked after going in and out and back into the same dimension

### ISSUE THREAD

**Issue by alexrsagen** [Johni0702/BetterPortals#359]
The client threads gets parked indefinitely after going in and out and back into the same dimension (a [Compact Machines](https://curseforge.com/minecraft/mc-mods/compact-machines) "Maximum Compact Machine").

Here's a thread dump of all threads while the client thread is parked:
https://gist.github.com/alexrsagen/1c32b6d8a0524bafac1aeaf62fe862ba

The reason I'm reporting it here is because of the following line in the client thread stack trace before the park: `de.johni0702.minecraft.view.impl.client.ClientState$Companion$reuseOrCreate$1.invoke(ClientState.kt:240)`

https://github.com/Johni0702/BetterPortals/blob/a75586e8344f1d33b7170a2a9d7765255ae51a7f/src/view/kotlin/de/johni0702/minecraft/view/impl/client/ClientState.kt#L240

Mod list (ignore BetterPortals version here, it is running version 0.3.5 which is the latest at the time of writing): https://gist.github.com/alexrsagen/139aa3bebab64bd5d73940053d540c0e#file-crash-2019-09-13_21-35-18-client-txt-L94-L225

Modpack: https://www.technicpack.net/modpack/owltechs-reborn.1532204

**Comment by Johni0702** [comment]
Thanks for the thread dump.

This looks very much like this compatibility issue with LittleTiles which has been fixed but not yet published on CurseForge: https://github.com/CreativeMD/LittleTiles/issues/237
Try using the LittleTiles/CreativeCore versions linked in that issue.

**Comment by alexrsagen** [comment]
Can confirm this fixes the issue, thank you so much for looking into it! 😄
