### ISSUE TITLE
All client-side settings should be clearly labeled as such

### ISSUE THREAD

**Issue by Danickar** [Johni0702/BetterPortals#360]
Forge Version: 14.23.5.2838
Mod Version: 0.3.4

Despite setting Opacity for all portal types to 0 in the config files the purple portal texture is still rendering.

**Comment by Johni0702** [comment]
Please attach
- the BP config file
- Minecraft's log
- a screenshot of the portal texture (preferably one with the camera right in the middle of it)

**Comment by Danickar** [comment]
[debug.log](https://github.com/Johni0702/BetterPortals/files/3628158/debug.log)
[latest.log](https://github.com/Johni0702/BetterPortals/files/3628159/latest.log)


[betterportals.zip](https://github.com/Johni0702/BetterPortals/files/3628162/betterportals.zip)


Can't grab a screen shot where I am at the moment, but was able to get to the server to grab these.

**Comment by Johni0702** [comment]
Oh, did you only set them on the server-side?
All the visual settings are client-side settings. Considering I do mention it for some of them, I should probably be consistent and add it to all the others as well.

**Comment by Danickar** [comment]
I knew this but hadn't thought to double check. The cfg file in the modpack I put together had an older version of the settings. I updated that file to the one the server has and now it is working.
