### ISSUE TITLE
Crashes when Enabled

### ISSUE THREAD

**Issue by PiordaNautor** [Johni0702/BetterPortals#362]
My fear is that this is in conflict with something, but that is only a hypothesis.

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2019-09-21 00:54:25 PDT
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer
    at net.minecraftforge.client.ForgeHooksClient.shouldUseVanillaReloadableListener(ForgeHooksClient.java:959)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.notifyReloadListeners(SimpleReloadableResourceManager.java:131)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.reloadResources(SimpleReloadableResourceManager.java:112)
    at net.minecraft.client.Minecraft.refreshResources(Minecraft.java:808)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.EntityRenderer
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 831565960 bytes (793 MB) / 1672478720 bytes (1595 MB) up to 6442450944 bytes (6144 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6912m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 117 mods loaded, 116 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                            | Version                   | Source                                                       | Signature |
       |:----- |:----------------------------- |:------------------------- |:------------------------------------------------------------ |:--------- |
       | LC    | minecraft                     | 1.12.2                    | minecraft.jar                                                | None      |
       | LC    | mcp                           | 9.42                      | minecraft.jar                                                | None      |
       | LC    | FML                           | 8.0.99.99                 | forge-1.12.2-14.23.5.2847.jar                                | None      |
       | LC    | forge                         | 14.23.5.2847              | forge-1.12.2-14.23.5.2847.jar                                | None      |
       | LC    | ivtoolkit                     | 1.3.3-1.12                | minecraft.jar                                                | None      |
       | LC    | foamfixcore                   | 7.7.4                     | minecraft.jar                                                | None      |
       | LC    | obfuscate                     | 0.2.6                     | minecraft.jar                                                | None      |
       | LC    | aether_legacy                 | 1.4.4                     | aether_legacy-1.12.2-v1.4.4.jar                              | None      |
       | LC    | aether_legacy_addon           | 1.12.2-v1.2.3             | aether_continuation-1.12.2-v1.2.3.jar                        | None      |
       | LC    | aiimprovements                | 0.0.1.3                   | AIImprovements-1.12-0.0.1b3.jar                              | None      |
       | LC    | ambientsounds                 | 3.0                       | AmbientSounds_v3.0.9_mc1.12.2.jar                            | None      |
       | LC    | craftstudioapi                | 1.0.0                     | CraftStudio-1.0.0.93-mc1.12-alpha.jar                        | None      |
       | LC    | ctm                           | MC1.12.2-0.3.3.22         | CTM-MC1.12.2-0.3.3.22.jar                                    | None      |
       | LC    | baubles                       | 1.5.2                     | Baubles-1.12-1.5.2.jar                                       | None      |
       | LE    | thaumcraft                    | 6.1.BETA26                | Thaumcraft-1.12.2-6.1.BETA26.jar                             | None      |
       | L     | twilightforest                | 3.9.984                   | twilightforest-1.12.2-3.9.984-universal.jar                  | None      |
       | L     | animania                      | 1.7.1                     | animania-1.12.2-1.7.1.jar                                    | None      |
       | L     | placebo                       | 1.6.0                     | Placebo-1.12.2-1.6.0.jar                                     | None      |
       | L     | apotheosis                    | 1.10.4                    | Apotheosis-1.12.2-1.10.5.jar                                 | None      |
       | L     | jei                           | 4.15.0.289                | jei_1.12.2-4.15.0.289.jar                                    | None      |
       | L     | appleskin                     | 1.0.9                     | AppleSkin-mc1.12-1.0.9.jar                                   | None      |
       | L     | betteranimals                 | 5.2.1                     | betteranimals-5.2.1.jar                                      | None      |
       | L     | quark                         | r1.6-177                  | Quark-r1.6-177.jar                                           | None      |
       | L     | autoreglib                    | 1.3-32                    | AutoRegLib-1.3-32.jar                                        | None      |
       | L     | ichunutil                     | 7.2.1                     | iChunUtil-1.12.2-7.2.1.jar                                   | None      |
       | L     | backtools                     | 7.0.1                     | BackTools-1.12.2-7.0.1.jar                                   | None      |
       | L     | basketcase                    | 1.0.31                    | Basketcase-v1.0.31-mc1.12.2.jar                              | None      |
       | L     | betterslabsmod                | 0.0.7                     | Better+Slabs+Mod+[0.0.7].jar                                 | None      |
       | L     | betteranimalsplus             | 7.1.1                     | betteranimalsplus-1.12.2-7.1.1.jar                           | None      |
       | L     | betterbuilderswands           | 0.13.2                    | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar            | None      |
       | L     | betternether                  | 0.1.8.3                   | betternether-0.1.8.3.jar                                     | None      |
       | L     | forgelin                      | 1.8.4                     | Forgelin-1.8.4.jar                                           | None      |
       | L     | betterportals                 | 0.3.5                     | betterportals-0.3.5.jar                                      | None      |
       | L     | betterthanmending             | 1.1.2                     | BetterThanMending-1.1.2.jar                                  | None      |
       | L     | bibliocraft                   | 2.4.5                     | BiblioCraft[v2.4.5][MC1.12.2].jar                            | None      |
       | L     | byg                           | 1.6.8b2                   | BiomesYouGo1.6.8.jar                                         | None      |
       | L     | blocklings                    | 6.0.1                     | Blocklings 6.0.1 - 1.12.2.jar                                | None      |
       | L     | blur                          | 1.0.4-14                  | Blur-1.0.4-14.jar                                            | None      |
       | L     | bookshelf                     | 2.3.585                   | Bookshelf-1.12.2-2.3.585.jar                                 | None      |
       | L     | cookiesplus                   | 0.1                       | cookies-0.1.jar                                              | None      |
       | L     | corpse                        | 1.12.2-1.0.4              | corpse-1.12.2-1.0.4.jar                                      | None      |
       | L     | cosmiclib                     | 0.4.0                     | CosmicLib-1.12.2-0.4.0.BETA.jar                              | None      |
       | L     | cubicchunks                   | 1.12.2-0.0.970.0-SNAPSHOT | CubicChunks-1.12.2-0.0.970.0-SNAPSHOT-all.jar                | None      |
       | L     | cyclicmagic                   | 1.19.16                   | Cyclic-1.12.2-1.19.16.jar                                    | None      |
       | L     | orespawn                      | 3.3.1                     | OreSpawn-1.12-3.3.1.172.jar                                  | None      |
       | L     | densemetals                   | 1.2.0                     | DenseMetals-1.12-1.2.0.21.jar                                | None      |
       | L     | dimdoors                      | 3.0.9+287                 | DimensionalDoors-3.0.9-287.jar                               | None      |
       | L     | dldungeonsjbg                 | 1.12.10                   | DoomlikeDungeons-1.12.10-MC1.12.2.jar                        | None      |
       | L     | ebwizardry                    | 4.2.3                     | ElectroblobsWizardry-4.2.3-MC1.12.2.jar                      | None      |
       | L     | patchouli                     | 1.0-20                    | Patchouli-1.0-20.jar                                         | None      |
       | L     | mmorpg                        | 1.7.0                     | Mine_and_Slash-1.7.0.jar                                     | None      |
       | L     | rcraft                        | 2.0.4                     | dotHack Weapons-2.0.4.jar                                    | None      |
       | L     | gottschcore                   | 1.8.0                     | GottschCore-mc1.12.2-f14.23.5.2768-v1.8.0.jar                | None      |
       | L     | dungeons2                     | 1.7.1                     | Dungeons2-mc1.12.2-f14.23.5.2768-v1.7.1.jar                  | None      |
       | L     | dungeontactics                | DT-0.16.6                 | DungeonTactics-1.12.2-0.16.6.jar                             | None      |
       | L     | eerieentities                 | 1.0.7                     | EerieEntities-1.12.2-1.0.7.jar                               | None      |
       | L     | exoticbirds                   | 1.0                       | Exotic Birds 1.12.2-3.0.0.jar                                | None      |
       | L     | minerva                       | 1.0.13                    | minerva-library-1.0.13.jar                                   | None      |
       | L     | extraalchemy                  | 0.5.1                     | extraalchemy-0.5.1.jar                                       | None      |
       | L     | extra_spells                  | 1.1.1                     | ExtraSpells-1.12.2-1.1.1.jar                                 | None      |
       | L     | fastleafdecay                 | v14                       | FastLeafDecay-v14.jar                                        | None      |
       | L     | foamfix                       | 0.10.5-1.12.2             | foamfix-0.10.5-1.12.2.jar                                    | None      |
       | L     | googlyeyes                    | 7.1.0                     | GooglyEyes-1.12.2-7.1.0.jar                                  | None      |
       | L     | cgm                           | 0.15.2                    | guns-0.15.2-1.12.2.jar                                       | None      |
       | L     | hammercore                    | 2.0.5.0                   | HammerCore-1.12.2-2.0.5.0.jar                                | None      |
       | L     | waila                         | 1.8.26                    | Hwyla-1.8.26-B41_1.12.2.jar                                  | None      |
       | L     | llibrary                      | 1.7.19                    | llibrary-1.7.19-1.12.2.jar                                   | None      |
       | L     | iceandfire                    | 1.8.1                     | iceandfire-1.8.1.jar                                         | None      |
       | L     | inventorypets                 | 2.0.3                     | inventorypets-1.12-2.0.3.jar                                 | None      |
       | L     | inventoryspam                 | 1.0.5                     | InventorySpam-1.12.2-1.0.5.jar                               | None      |
       | L     | inventorytweaks               | 1.63+release.109.220f184  | InventoryTweaks-1.63.jar                                     | None      |
       | L     | letmesleep                    | 1.0                       | LetMeSleep-v1.0-1.12.2.jar                                   | None      |
       | L     | dogslie                       | 1.0.0                     | LetSleepingDogsLie-1.12.2-1.0.0.jar                          | None      |
       | L     | liquid_luck                   | 1.2                       | liquidluck-1.2.jar                                           | None      |
       | L     | mantle                        | 1.12-1.3.3.55             | Mantle-1.12-1.3.3.55.jar                                     | None      |
       | L     | mineralogy                    | 3.4.0                     | Mineralogy-1.12-3.4.0.29.jar                                 | None      |
       | L     | mobends                       | 0.24                      | mobends-0.24_for_MC-1.12.jar                                 | None      |
       | L     | mo_swords                     | v5                        | moSwords-1.12.2v5.jar                                        | None      |
       | L     | mousetweaks                   | 2.10                      | MouseTweaks-2.10-mc1.12.2.jar                                | None      |
       | L     | mowziesmobs                   | 1.5.4                     | mowziesmobs-1.5.4.jar                                        | None      |
       | L     | multimine                     | 1.6.1                     | MultiMine-1.12.2.jar                                         | None      |
       | L     | uteamcore                     | 2.2.4.107                 | u_team_core-1.12.2-2.2.4.107.jar                             | None      |
       | L     | musicplayer                   | 2.0.3.39                  | music_player-1.12.2-2.0.3.39.jar                             | None      |
       | L     | mysticalworld                 | 1.12.2-1.4.4              | MysticWorld-1.12.2-1.4.4.jar                                 | None      |
       | L     | recipehandler                 | 0.13                      | NoMoreRecipeConflict-0.13(1.12.2).jar                        | None      |
       | L     | guilib                        | $version                  | paintingselgui-PSG+Revamed-1.12.2-1.1.0.1.jar                | None      |
       | L     | paintingselgui                | $version                  | paintingselgui-PSG+Revamed-1.12.2-1.1.0.1.jar                | None      |
       | L     | rats                          | 2.0.0                     | rats-2.0.0.jar                                               | None      |
       | L     | reap                          | 1.5.2                     | reap-1.5.2.jar                                               | None      |
       | L     | reccomplex                    | 1.4.8.2                   | RecurrentComplex-1.4.8.2.jar                                 | None      |
       | L     | additionalstructures          | 2.2.3                     | Rex's-Additional-Structures-1.12.2-(v.2.2.3).jar             | None      |
       | L     | roguelike                     | 1.8.0                     | RoguelikeDungeons-1.12.2-1.8.0.jar                           | None      |
       | L     | ropebridge                    | 2.0.5                     | ropebridge-1.12-2.0.7.jar                                    | None      |
       | L     | ruins                         | 17.2                      | Ruins-1.12.2.jar                                             | None      |
       | L     | scp                           | 2.1.1                     | SCP Lockdown-1.12.2-2.1.1-beta.jar                           | None      |
       | L     | t3s4ebw                       | 1.0                       | SeedsForWizardry 1.0 For MC Forge 1.12.2.jar                 | None      |
       | L     | tickratechanger               | 1.0.14                    | TickrateChanger-1.0.14.jar                                   | None      |
       | L     | sleepingoverhaul              | 1.0.0                     | SleepingOverhaul-1.12.2-1.0.0.jar                            | None      |
       | L     | snowaccumulation              | 1.0.0                     | SnowAccumulation-1.12-1.0.0.jar                              | None      |
       | L     | sophisticatedwolves           | 3.13.8                    | SophisticatedWolves-1.12.2-3.13.8.jar                        | None      |
       | L     | soundfilters                  | 0.11_for_1.12             | SoundFilters-0.11_for_1.12.jar                               | None      |
       | L     | tconstruct                    | 1.12.2-2.12.0.157         | TConstruct-1.12.2-2.12.0.157.jar                             | None      |
       | L     | tektopia                      | 1.1.0                     | tektopia-1.1.0.jar                                           | None      |
       | L     | undergroundbiomes             | 1.3.7                     | UndergroundBiomesConstructs-1.12-1.3.7.jar                   | None      |
       | L     | valkyrienwarfare              | 0.9_prerelease_5          | Valkyrien+Warfare+0.9_prerelease_5+[Optimization+Update].jar | None      |
       | L     | vanillafix                    | 1.0.10-SNAPSHOT           | VanillaFix-1.0.10-99.jar                                     | None      |
       | L     | visuals                       | 7r                        | Visuals-1.12.2-7r.jar                                        | None      |
       | L     | vulcanite                     | 1.5.2                     | vulcanite-1.5.2-mc1.12.x.jar                                 | None      |
       | L     | waddles                       | 0.6.0                     | Waddles-1.12.2-0.6.0.jar                                     | None      |
       | L     | roguelike_dungeons_remastered | 1.0.0                     | Wesley's roguelike dungeons.jar                              | None      |
       | L     | wizardanimalsbeta10           | 1.0.0                     | WizardAnimalsBeta1.0.jar                                     | None      |
       | L     | worleycaves                   | 1.5.1                     | worleycaves-1.5.1.jar                                        | None      |
       | L     | wts                           | 1.1.0                     | WTS-1.1.0.jar                                                | None      |
       | L     | ladylib                       | 2.1                       | Ladylib-2.1.jar                                              | None      |
       | L     | lumen                         | 0.4.0                     | lumen-Beta 0.4.1.jar                                         | None      |
       | L     | mysticallib                   | 1.12.2-1.3.7              | mysticallib-1.12.2-1.3.7.jar                                 | None      |
       | UD    | cubicchunkscore               | @@VERSION@@               | minecraft.jar                                                | None      |
  Loaded coremods (and transformers): ApotheosisCore (Apotheosis-1.12.2-1.10.5.jar)
                                        shadows.ApotheosisTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      Quark Plugin (Quark-r1.6-177.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      MixinLoaderForge (Valkyrien+Warfare+0.9_prerelease_5+[Optimization+Update].jar)
                                        
                                      ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
                                        com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      CosmicLibFakeCoreMod (CosmicLib-1.12.2-0.4.0.BETA.jar)
                                        
                                      BlurPlugin (Blur-1.0.4-14.jar)
                                        com.tterrag.blur.BlurTransformer
                                      TickrateChanger (TickrateChanger-1.0.14.jar)
                                        me.guichaguri.tickratechanger.TickrateTransformer
                                      MMFMLCorePlugin (MultiMine-1.12.2.jar)
                                        atomicstryker.multimine.common.fmlmagic.MMTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      HCASM (HammerCore-1.12.2-2.0.5.0.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      CubicChunksCoreMod (CubicChunks-1.12.2-0.0.970.0-SNAPSHOT-all.jar)
  GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics 4000'
  Suspected Mods: Unknown
  Launched Version: forge-14.23.5.2847
  LWJGL: 2.9.4
  OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4358, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: ~~ERROR~~ NullPointerException: null
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz

**Comment by Johni0702** [comment]
Certainly looks like a compatibility issue.
The crash report doesn't tell which mod is causing it though. There will usually be other exceptions in the log which give more information.
Based on your installed mods, it's almost certainly this one: #179
