### ISSUE TITLE
Minecraft crashes in dev environments with BP as a dependency

### ISSUE THREAD

**Issue by Lumaceon** [Johni0702/BetterPortals#372]
In my development environment, the Minecraft client crashes just before it finishes loading when BetterPortals is declared as a dependency.

A new Forge project was set up and the following was added to the default gradle.build file:

```
repositories {
    mavenCentral()
    maven {
        name = "CurseForge"
        url = "https://minecraft.curseforge.com/api/maven/"
    }
    maven { url "http://maven.shadowfacts.net/" } // Forgelin
}

dependencies {
    compile group: "net.shadowfacts", name: "Forgelin", version: "1.8.4"
    deobfCompile "betterportals:BetterPortals:0.3.6"
}
```

`-Dfml.coreMods.load=de.johni0702.minecraft.betterportals.impl.MixinLoader` is added as a JVM argument.

With these settings, the Minecraft Client crashes shortly after loading.
[https://pastebin.com/5MdVTzhY](https://pastebin.com/5MdVTzhY)

**Comment by Johni0702** [comment]
Looks like we're running into https://github.com/SpongePowered/Mixin/issues/256.
Above commit works around the issue by replacing the relevant `@Overwrite` with an equivalent `@Inject`. It should be available as 0.3.6.1 from CF whenever they're done approving it.
