### ISSUE TITLE
better portals texture glitch 

### ISSUE THREAD

**Issue by fluffysnow** [Johni0702/BetterPortals#375]
https://imgur.com/yk0Vo6t There a texture glitch

**Comment by Johni0702** [comment]
This is likely caused (or at least triggered) by one of your other mods. Try removing as many as possible until you can figure out which one is relevant.

**Comment by Scifantech** [comment]
I too am having this problem. So I created a fresh install, with no other mods installed and it still does it.

**Comment by Johni0702** [comment]
This is likely caused by LiteLoader, see #495.
