### ISSUE TITLE
BP crashes if Forge fails startup due to duplicate mods

### ISSUE THREAD

**Issue by SpGilbert** [Johni0702/BetterPortals#380]
https://paste.ee/p/Cwnd9
[debug.log](https://github.com/Johni0702/BetterPortals/files/3678961/debug.log)

sound physics mod
https://github.com/djpadbit/Sound-Physics

**Comment by SpGilbert** [comment]
um i think i figured out the issue and that was that better portals gives a diffent crash report than it should when you have 2 versions of the same mod.

**Comment by Johni0702** [comment]
Ah, yes, that's what's going on.
BP properly handles the case where there's an error during mod loading  (e.g. missing dependency) but duplicate detection happens before mod loading and that's not yet handled.

**Comment by SpGilbert** [comment]
ok
