### ISSUE TITLE
Incompatible with Morpheus

### ISSUE THREAD

**Issue by C0rn3j** [Johni0702/BetterPortals#386]
```
1.12.2
Forge 14.23.5.2847
Morpheus-1.14.4-4.2.43.jar
betterportals-0.3.6
```

https://www.curseforge.com/minecraft/mc-mods/morpheus

Morpheus let's you sleep only when 50%(by default) of people on the server are sleeping.

However for every dimension you enter, there is an extra player that Morpheus sees.

**Comment by Johni0702** [comment]
The Morpheus version you listed doesn't seem right (it's 1.14.4).
The fake players which BP spawns are always in spectator mode and Morpheus should probably ignore spectators.
In fact, as of https://github.com/Quetzi/Morpheus/issues/62, it does. If you want that to happen on 1.12.2 as well, then you need to ask Morpheus' author to backport that fix.
AFAICT there's nothing BP can / should do.

**Comment by C0rn3j** [comment]
Thank you for finding out the issue, I'll try asking the Morpheus author.

>The Morpheus version you listed doesn't seem right (it's 1.14.4).

You are correct, I accidentally copy pasted from the wrong tab, sorry about that.
