### ISSUE TITLE
Rotating & Glitching Block Textures 

### ISSUE THREAD

**Issue by SomeRandomInternetGuy** [Johni0702/BetterPortals#390]
Whenever you go through a nether portal, the top and bottom of the block texture rotate, and if you look straight down it starts glitching like crazy.

[Footage](https://mega.nz/#!9McX2aaD!WIZpEX3SoctNgAiepzT2Lq0KdYMCcVbb9iyigTA-pcQ)

(Btw the texture pack i was using only affected the gui)

**Comment by Johni0702** [comment]
The flickering when looking straight down and moving is a known but low priority issue: #64

The rotation of the texture is near impossible to fix unless one's fine with forcing portals in both dimensions to look in the same direction (definitely not worth it imo) or with entities becoming half-invisible while in a portal (i.e. more extreme version of #75).
A fix for #75 could most likely also make the second option a non-issue (and thus a viable option for fixing the rotation). So I'm closing this issue in favor of #75.
