### ISSUE TITLE
Vivecraft bug, only rendering top bottom half of Vision

### ISSUE THREAD

**Issue by BeigeAnimal** [Johni0702/BetterPortals#391]
I'm the user who bought up the bug, and I've read a bit of what you said in #122
This doesn't happen on the main menu.
It happens on world load whether or not a portal is in view or nearby.
It happens whether see through portals is enabled or disabled
I'm not adjusting my render scale with Steam VR or in game settings, 
I'm using a fresh instance with no settings changed.

This is a screenshot of the the debug screen problem is it renders in game so it's hard to take a screenshot
![f6rf](https://user-images.githubusercontent.com/25735025/66592893-8f492e80-eb5b-11e9-8cd3-4c1f213f251d.png)

upon further testing I found running the game in fullscreen causes the issue to go away, I took a screenshot(it had to be ingame though) of that just in case you wanted it, the black bar and little artifact to the left doesn't appear in VR but I don't know if it'll be a problem for higher FOV VR headsets tho, I'm on Vive so my FOV is 90.
![2019-10-10_12 42 34](https://user-images.githubusercontent.com/25735025/66592904-94a67900-eb5b-11e9-886f-74c03dd03786.png)

**Comment by Johni0702** [comment]
Thanks for all the details!

Oh, I think I know what might be going on here.
Somewhere BP (or some code which BP relies on) uses the window size as opposed to the headset resolution.
I don't think I've ever tested reducing my window size below the size of my emulated headset. I'll try to look into it as soon as I find the time to do so.
While I'm at it, I'll also try different FOVs cause I've never done that either.
