### ISSUE TITLE
When I open Minecraft, it crashes almost immediately.

### ISSUE THREAD

**Issue by FgeetvDuddy098** [Johni0702/BetterPortals#392]
I have been told to update forge. I have done so and still have the same error. I am running forge 1.12.2 with only the better portals mod in the mods folder. The crash report is attached, just in case it's different.
[crash-2019-10-11_14.18.18-client.txt](https://github.com/Johni0702/BetterPortals/files/3715497/crash-2019-10-11_14.18.18-client.txt)
P.S. What happens is the forge loading screen appears for about a second, then it crashes.

**Comment by ender11hun** [comment]
You're missing forgelin, BP depends on it. Install it and you'll be good to go.

**Comment by Johni0702** [comment]
^

You're also using an old version of BP, any version after 0.3.3 even explicitly tells you when you're missing Forgelin.
