### ISSUE TITLE
Issue when going to Tropicraft dimension

### ISSUE THREAD

**Issue by flyingyalie** [Johni0702/BetterPortals#396]
With Better Portals enabled and Enhance third-party transfers = true, going to the tropicraft dimension loads too quickly. You are immediately teleported to the new dimension and it begins to load (can see the chunks loading in). You are teleported direcrly on top of the teleporter to return to the overworld. Normally not an issue becuase the nausea effect has worn off so you just are in the water. However, the world loads so fast that you still have the effect and immediately teleport back to the overworld. Disabling Better Portals fixes the problem entirely, and setting Enhance third-party transfers to false, also resolves it, but not cleanly. Makes the return trip to the overworld functional, but loads quickly. Currently running in single player but will put it on a server soon and retest. 

Versions:
MC 1.12.2
Better Portals 0.3.7
Tropicraft 7.1.9.115
Forge 14.23.5.2847

**Comment by Johni0702** [comment]
This appears to be an issue with Tropicraft. Whether I enable or disable Enhance third-party transfer or even uninstall BP, when first entering the tropics, I always get teleported right back to the overworld.

Same mod versions.
