### ISSUE TITLE
Crash issue on startup.

### ISSUE THREAD

**Issue by RedPhoenix05** [Johni0702/BetterPortals#399]
I tried downloading betterportals today and put it into my mods folder. after startup, it asked for Forgelin, which i then downloaded and restarted. It crashed. I use forgelin without betterportals, and works just fine. So why does bp want forgelin but it makes it crash??? I used the latest versions of both and even tried second latest and all combinations and it still doesn't work! Please help. Here's the crash report I got:
![image](https://user-images.githubusercontent.com/56946245/67448465-ac124700-f5dc-11e9-90b0-24e96d1d5178.png)

**Comment by Johni0702** [comment]
It doesn't crash because of Forgelin, it just doesn't even attempt to load without it. The reason it crashes is probably because you're using an ancient version of Forge.
Though I can really only guess without the crash report.
