### ISSUE TITLE
IllegalStateException crash

### ISSUE THREAD

**Issue by bobodoustaud** [Johni0702/BetterPortals#403]
this crash doesn't occurs everytime, it's a little bit random. It happened to me while using the dimension changer item from aroma's mining dimension mod but not at every try (sometimes it works and sometimes it crashes)

here is the crash report : https://pastebin.com/pHB7QcSW

i'm not sure that is your problem so i will also report it to the librarianlib mod issue tracker. https://github.com/TeamWizardry/LibrarianLib/issues/123

**Comment by Johni0702** [comment]
Closing since this is indeed a race condition in LibrarianLib.
