### ISSUE TITLE
Fatal game crash while loading minecraft

### ISSUE THREAD

**Issue by ajwiggin** [Johni0702/BetterPortals#411]
I ran just Forgelin and BetterPortals and Minecraft will not open, crashing after loading. Here is the crash report:

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   ForgelinPlugin (Forgelin-1.8.4.jar)
> Contact their authors BEFORE contacting forge
> 
> // You should try our sister game, Minceraft!
> 
> Time: 11/17/19 1:01 PM
> Description: Initializing game
> 
> java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer
> 	at net.minecraftforge.client.ForgeHooksClient.shouldUseVanillaReloadableListener(ForgeHooksClient.java:777)
> 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
> 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
> 	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:807)
> 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
> 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.EntityRenderer
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 14 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Client thread
> Stacktrace:
> 	at net.minecraftforge.client.ForgeHooksClient.shouldUseVanillaReloadableListener(ForgeHooksClient.java:777)
> 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
> 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
> 	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:807)
> 	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:247)
> 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
> 
> -- Initialization --
> Details:
> Stacktrace:
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.12.2
> 	Operating System: Mac OS X (x86_64) version 10.15
> 	Java Version: 1.8.0_74, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 180779608 bytes (172 MB) / 402653184 bytes (384 MB) up to 2147483648 bytes (2048 MB)
> 	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
> 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> 	FML: MCP 9.42 Powered by Forge 14.23.5.2768 6 mods loaded, 6 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> 	| State | ID            | Version      | Source                        | Signature                                |
> 	|:----- |:------------- |:------------ |:----------------------------- |:---------------------------------------- |
> 	| UC    | minecraft     | 1.12.2       | minecraft.jar                 | None                                     |
> 	| UC    | mcp           | 9.42         | minecraft.jar                 | None                                     |
> 	| UC    | FML           | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UC    | forge         | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UC    | forgelin      | 1.8.4        | Forgelin-1.8.4.jar            | None                                     |
> 	| U     | betterportals | 0.3.7.1      | betterportals-0.3.7.1.jar     | None                                     |
> 
> 	Loaded coremods (and transformers): 
> ForgelinPlugin (Forgelin-1.8.4.jar)
>   
> 	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-14.0.67' Renderer: 'Intel(R) HD Graphics 6000'
> 	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
> 	LWJGL: 2.9.2
> 	OpenGL: Intel(R) HD Graphics 6000 GL version 2.1 INTEL-14.0.67, Intel Inc.
> 	GL Caps: Using GL 1.3 multitexturing.
> Using GL 1.3 texture combiners.
> Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
> Shaders are available because OpenGL 2.1 is supported.
> VBOs are available because OpenGL 1.5 is supported.
> 
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'fml,forge'
> 	Type: Client (map_client.txt)
> 	Resource Packs: Faithful 1.12.2.zip
> 	Current Language: ~~ERROR~~ NullPointerException: null
> 	Profiler Position: N/A (disabled)
> 	CPU: 4x Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz

**Comment by azwiggin** [comment]
I finally got it to work by running Forgelin alone, closing Minecraft and then running BetterPortals with Forgelin. The next time I closed Minecraft and tried to reopen it, it crashed again with the same errors

**Comment by Johni0702** [comment]
Please attach the full game log. There's likely a more direct hint on the issue in it, the crash report itself unfortunately doesn't tell much.
