### ISSUE TITLE
Portal texture not removed?

### ISSUE THREAD

**Issue by PoopingPants** [Johni0702/BetterPortals#412]
The mod loads, and i can seamlessly go from the overworld to the nether, but the portal texture that is purple and spins around isnt removed, can you possible give any hints or ideas on how to fix this?
![2019-11-17_11 41 06](https://user-images.githubusercontent.com/57869939/69010620-72103880-092f-11ea-9743-c28e9133696e.png)
![2019-11-17_11 46 07](https://user-images.githubusercontent.com/57869939/69010683-02e71400-0930-11ea-8e1a-a89dde0513a8.png)

**Comment by Johni0702** [comment]
The portal texture is supposed to be there, its opacity can be configured in the mod options.
The portal should however be still see-through unless you disabled that. If you didn't disable it, please attach the game log and a screenshot showing the same as the first screenshot but with "Debug View" (you can find that in the mod options as well) and F3 enabled

**Comment by Johni0702** [comment]
Closing due to lack of reply.

For anyone seeing the same issue, make sure you've got OF's shaders disabled ("Internal" is not disabled!). OF shaders do not support rendering multiple worlds.
