### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by qmagnet** [Johni0702/BetterPortals#417]
Apologies. I do not use mods or github at all. I am getting a crash trying to run BetterPortals Mod

I just installed a fresh copy of Forge 1.12.2 also Forgelin. Minecraft loads with Forgelin installed but when i try to load it with BetterPortals I get this 

The game crashed whilst initializing game Error: java.lang.NoClassDefFoundError: net/minecraft/client/audio/SoundManager

Here's the crash report
[crash-2019-11-23_10.42.24-client.txt](https://github.com/Johni0702/BetterPortals/files/3882696/crash-2019-11-23_10.42.24-client.txt)

**Comment by Johni0702** [comment]
The version of Forge you're using is too old (released over two years ago!) and doesn't have a specific feature which BP requires.
You should update to the current Recommended or Latest version (either should work with BP).

In general, make sure your mods are all up-to-date and only get them from their official websites ([this one](https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.12.2.html) in case of Forge). Third-party sites often link to outdated versions and (in the worst case) may bundle malware with their downloads.

**Comment by qmagnet** [comment]
I grabbed that version today. Is it not the latest 1.12.2 version of Forge?

**Comment by qmagnet** [comment]
Oh actually I think I see what you mean. I think I clicked the first google link I searched. I will try the link you sent. Thanks!
