### ISSUE TITLE
Other world isnt rendering

### ISSUE THREAD

**Issue by Utoog** [Johni0702/BetterPortals#418]
portal texture opacity is 0
![Screenshot_3](https://user-images.githubusercontent.com/58138270/69494993-6820a380-0ef4-11ea-906c-378844a46ea9.png)
[latest.log](https://github.com/Johni0702/BetterPortals/files/3883568/latest.log)

![Screenshot_1](https://user-images.githubusercontent.com/58138270/69494977-41626d00-0ef4-11ea-937a-1cc709fdca62.png)
![Screenshot_2](https://user-images.githubusercontent.com/58138270/69494979-43c4c700-0ef4-11ea-9f5f-de8a92dc2ba7.png)

**Comment by Johni0702** [comment]
Looks like you've got OF's internal shaders enabled:

> [19:52:06] [Client thread/INFO] [betterportals/view]: Optifine detected. See-through portals will be disabled while Shaders are active.

> [19:51:55] [Client thread/INFO] [net.optifine.shaders.SMCLog]: [Shaders] Loaded shaderpack: (internal)
