### ISSUE TITLE
Crash with v10overlap

### ISSUE THREAD

**Issue by TheQKnight** [Johni0702/BetterPortals#420]
Here is the log https://paste.dimdev.org/aliqarofaj.mccrash . 

This happened when I went from the nether to my custom dimension (id 10).

**Comment by Johni0702** [comment]
Hmm. Looks like v10verlap tries to teleport one of BP's fake players (when BP does its enhanced third-party transfer, it leaves behind a fake player entity in the old world to prevent it from immediately unloading and thereby allow it to animate the transition).
Not yet sure how to best solve that.

Could you check if disabling the `Enhanced third-party transition` option in BP's config fixes the issue when moving up from the nether to dim 10 and also the other way around?

**Comment by TheQKnight** [comment]
Yeah, it seems to work with that disabled. I think it may have something to do with v10 teleporting every single entity though the dimension layers when possible. There seems to be no blacklist of entities it will teleport.

**Comment by Johni0702** [comment]
Alright, thanks for the report.
When I get the time to do so (probably next weekend or the week following it), I'll see if ignoring the teleports that happen to fake players does the job and if it doesn't, I'll simply add v10 to BP's "Enhanced third-party transition"-blacklist (that'll disable those transitions for v10 while still allowing them for other mods).
