### ISSUE TITLE
Make it so that chunks of the dimension beyond the portal while still in the OW are adjustable

### ISSUE THREAD

**Issue by kalizy** [Johni0702/BetterPortals#422]
Please, if possible, make it so that the rendering of chunks of the dimensions, while looking at the portal is adjustable so that multiplayer can be less laggy.

**Comment by Johni0702** [comment]
Not entirely sure what you're asking. Sounds like the "See-through portals" option to me.

Have you looked at the config file/screen? There are a few options to affect rendering of chunks through portals.
These two are global (first one is the one which I was referring to):
https://github.com/Johni0702/BetterPortals/blob/9602911e69fa121066f662bd662fef17cd5030bc/src/main/java/de/johni0702/minecraft/betterportals/impl/BPConfig.java#L68-L87
And these three can be configured per-portal (the performance relevant part being the cutoff point where the portal stops being rendered entirely, the remainder is just for seamless transitions between fully visible and totally opaque):
https://github.com/Johni0702/BetterPortals/blob/9602911e69fa121066f662bd662fef17cd5030bc/src/main/java/de/johni0702/minecraft/betterportals/impl/PortalConfig.java#L20-L53

In addition, chunks in portals will only load and render in a `viewDistanceInChunks - distanceFromYouToPortalInChunks - 1` radius (taking into account nesting; and the constant 1 may be different depending on portal type, i.e. travelhuts uses 4 iirc, everything else 1).
