### ISSUE TITLE
Crash occuring with Weeping Angels Mod

### ISSUE THREAD

**Issue by SpencerMeow** [Johni0702/BetterPortals#427]
When I have this mod installed and the Weeping Angels mod installed, (stone statues from Doctor Who which move when you aren't looking damaging and teleport you to another location,) I get a crash whenever an angel statue teleports me. The log goes as follows.

Thanks for viewing!

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2019-12-02 18:45:47 CST
Description: Ticking entity

java.lang.IllegalStateException: makeMainWorld called on main view
    at de.johni0702.minecraft.view.impl.server.ServerWorldManager.makeMainWorld$bp_master_view(ServerWorldManager.kt:135)
    at de.johni0702.minecraft.view.impl.server.ServerWorldsManagerImpl.changeDimension(ServerWorldsManagerImpl.kt:149)
    at de.johni0702.minecraft.betterportals.impl.transition.server.DimensionTransitionHandler.transferPlayerToDimension(DimensionTransitionHandler.kt:53)
    at net.minecraft.server.management.PlayerList.handler$betterPortalPlayerToDimension$zhi000(PlayerList.java:2252)
    at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java)
    at net.minecraft.entity.player.EntityPlayerMP.changeDimension(EntityPlayerMP.java:695)
    at me.suff.angels.utils.Teleporter.moveSafeAcrossDim(Teleporter.java:51)
    at me.suff.angels.common.entities.EntityWeepingAngel.teleportInteraction(EntityWeepingAngel.java:356)
    at me.suff.angels.common.entities.EntityWeepingAngel.attackEntityAsMob(EntityWeepingAngel.java:149)
    at me.suff.angels.common.entities.EntityQuantumLockBase.onLivingUpdate(EntityQuantumLockBase.java:71)
    at me.suff.angels.common.entities.EntityWeepingAngel.onLivingUpdate(EntityWeepingAngel.java:203)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:377)
    at net.minecraft.entity.monster.EntityMob.onUpdate(EntityMob.java:50)
    at me.suff.angels.common.entities.EntityWeepingAngel.onUpdate(EntityWeepingAngel.java:255)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.redirect$updateEntity$zfb000(World.java:5623)
    at net.minecraft.world.World.updateEntities(World.java:1762)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: weeping-angels:weepingangel (me.suff.angels.common.entities.EntityWeepingAngel)
  Entity ID: 5349
  Entity Name: Weeping Angel
  Entity's Exact location: 105.42, 64.00, 85.93
  Entity's Block location: World: (105,64,85), Chunk: (at 9,4,5 in 6,5; contains blocks 96,0,80 to 111,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Entity's Momentum: 0.14, -0.08, 0.04
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {HurtByTimestamp:0,ForgeData:{},timeSeen:0,Attributes:[{Base:50.0d,Name:"generic.maxHealth"},{Base:9999999.0d,Name:"generic.knockbackResistance"},{Base:0.23000000417232513d,Name:"generic.movementSpeed"},{Base:2.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:1.0d,Name:"forge.swimSpeed"},{Base:16.0d,Name:"generic.followRange"},{Base:8.0d,Name:"generic.attackDamage"}],Invulnerable:0b,FallFlying:0b,PortalCooldown:0,AbsorptionAmount:0.0f,type:0,angelChild:0b,FallDistance:0.0f,DeathTime:0s,ForgeCaps:{"dsurround:data":{a:0b,f:0b},"avp:organism":{BPM:74},"thebetweenlands:entity_gems":{gems:[]},"thebetweenlands:custom_step_sound":{},"llibrary:extendedentitydatacapability":{"mm:living":{frozenYaw:0.0f,freezeProgress:0.0f,frozenPitch:0.0f,prevHasAI:0b,frozenYawHead:0.0f,frozenEntityID:-1,frozenLimbSwingAmount:0.0f,frozenRenderYawOffset:0.0f,frozenSwingProgress:0.0f}},"thebetweenlands:puppet":{ticks:0,recruitmentCost:0,stay:0b},"thebetweenlands:equipment":{amuletSlots:1}},HandDropChances:[0.085f,0.085f],PersistenceRequired:0b,Motion:[0.13532720060378983d,-0.0784000015258789d,0.03689195081148893d],Leashed:0b,UUIDLeast:-5622091363382999291L,Health:50.0f,pose:"IDLE",hungerLevel:50,prevPos:0L,LeftHanded:0b,Air:300s,OnGround:1b,Dimension:0,Rotation:[-80.34773f,0.0f],isSeen:0b,UpdateBlocked:0b,HandItems:[{},{}],ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],UUIDMost:-4789635687373193143L,Pos:[105.42012706685301d,64.0d,85.93237101599995d],Fire:-1s,ArmorItems:[{},{},{},{}],CanPickUpLoot:0b,HurtTime:0s,SurgeAABB:[105.12012705493208d,64.0d,85.63237100407902d,105.72012707877394d,65.79999995231628d,86.23237102792088d]}

-- Affected level --
  Level name: DankRealm Testing
  All players: 1 total; [GCEntityPlayerMP['CatKrusader'/54, l='DankRealm Testing', x=107.30, y=64.00, z=86.25]]
  Chunk stats: ServerChunkCache: 702 Drop: 0
  Level seed: 8687205226535725475
  Level generator: ID 00 - default, ver 1. Features enabled: true
  Level generator options: {"diamondSize":8,"lapisCenterHeight":16,"lavaLakeChance":80,"redstoneMaxHeight":16,"diamondMaxHeight":16,"coalMaxHeight":128,"coalMinHeight":0,"seaLevel":63,"graniteCount":10,"riverSize":4,"gravelMinHeight":0,"graniteSize":33,"redstoneSize":8,"fixedBiome":-1,"waterLakeChance":4,"dioriteMinHeight":0,"andesiteCount":10,"graniteMaxHeight":80,"redstoneMinHeight":0,"lapisSize":7,"dirtCount":10,"ironMinHeight":0,"dioriteMaxHeight":80,"coalCount":20,"gravelCount":8,"coalSize":17,"gravelSize":33,"ironMaxHeight":64,"lapisSpread":16,"dioriteCount":10,"andesiteSize":33,"biomeSize":4,"graniteMinHeight":0,"goldCount":2,"diamondCount":1,"dirtSize":33,"gravelMaxHeight":256,"goldSize":9,"ironCount":20,"diamondMinHeight":0,"ironSize":9,"redstoneCount":8,"andesiteMinHeight":0,"dioriteSize":33,"goldMaxHeight":32,"dungeonChance":8,"andesiteMaxHeight":80,"dirtMinHeight":0,"lapisCount":1,"goldMinHeight":0,"dirtMaxHeight":256,"lowerLimitScale":512.0,"biomeDepthOffset":0.0,"upperLimitScale":512.0,"heightScale":684.412,"biomeScaleWeight":1.0,"biomeDepthWeight":1.0,"mainNoiseScaleZ":80.0,"mainNoiseScaleY":160.0,"depthNoiseScaleX":200.0,"mainNoiseScaleX":80.0,"baseSize":8.5,"depthNoiseScaleZ":200.0,"stretchY":12.0,"depthNoiseScaleExponent":0.5,"biomeScaleOffset":0.0,"coordinateScale":684.412,"useStrongholds":true,"useMineShafts":true,"useTemples":true,"useLavaOceans":false,"useCaves":true,"useWaterLakes":true,"useLavaLakes":true,"useMonuments":true,"useRavines":true,"useDungeons":true,"useVillages":true}
  Level spawn location: World: (248,64,104), Chunk: (at 8,4,8 in 15,6; contains blocks 240,0,96 to 255,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 800 game time, 800 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 40041 (now: false), thunder time: 52141 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 3803088976 bytes (3626 MB) / 7415529472 bytes (7072 MB) up to 7516192768 bytes (7168 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 1, tcache: 1, allocated: 14, tallocated: 94
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F4 105 mods loaded, 105 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                                           | Version               | Source                                               | Signature                                |
       |:------ |:-------------------------------------------- |:--------------------- |:---------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                                    | 1.12.2                | minecraft.jar                                        | None                                     |
       | LCHIJA | mcp                                          | 9.42                  | minecraft.jar                                        | None                                     |
       | LCHIJA | FML                                          | 8.0.99.99             | forge-1.12.2-14.23.5.2847.jar                        | None                                     |
       | LCHIJA | forge                                        | 14.23.5.2847          | forge-1.12.2-14.23.5.2847.jar                        | None                                     |
       | LCHIJA | creativecoredummy                            | 1.0.0                 | minecraft.jar                                        | None                                     |
       | LCHIJA | micdoodlecore                                |                       | minecraft.jar                                        | None                                     |
       | LCHIJA | otgcore                                      | 1.12.2 - v8.3         | minecraft.jar                                        | None                                     |
       | LCHIJA | com.elytradev.movingworld.common.asm.coremod |                       | minecraft.jar                                        | None                                     |
       | LCHIJA | foamfixcore                                  | 7.7.4                 | minecraft.jar                                        | None                                     |
       | LCHIJA | futuremccore                                 | 0.1.12                | minecraft.jar                                        | None                                     |
       | LCHIJA | replaymod                                    | 1.12.2-2.2.0-b7       | replaymod-1.12.2-2.2.0-b7.jar                        | None                                     |
       | LCHIJA | jei                                          | 4.15.0.292            | jei_1.12.2-4.15.0.292.jar                            | None                                     |
       | LCHIJA | abyssalcraft                                 | 1.9.14                | AbyssalCraft-1.12.2-1.9.14.jar                       | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCHIJA | actuallyadditions                            | 1.12.2-r151           | ActuallyAdditions-1.12.2-r151.jar                    | None                                     |
       | LCHIJA | aether_legacy                                | 1.4.4                 | aether_legacy-1.12.2-v1.4.4.jar                      | None                                     |
       | LCHIJA | mdxlib                                       | 3.0.0.22              | mdxlib-3.0.0.22.jar                                  | None                                     |
       | LCHIJA | redstoneflux                                 | 2.1.0                 | RedstoneFlux-1.12-2.1.0.6-universal.jar              | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | avp                                          | 6.0.0.51              | aliensvspredator-6.0.0.51.jar                        | None                                     |
       | LCHIJA | quark                                        | r1.6-177              | Quark-r1.6-177.jar                                   | None                                     |
       | LCHIJA | autoreglib                                   | 1.3-32                | AutoRegLib-1.3-32.jar                                | None                                     |
       | LCHIJA | forgelin                                     | 1.8.4                 | Forgelin-1.8.4.jar                                   | None                                     |
       | LCHIJA | betterportals                                | 0.3.7.3               | betterportals-0.3.7.3.jar                            | None                                     |
       | LCHIJA | bibliocraft                                  | 2.4.5                 | BiblioCraft[v2.4.5][MC1.12.2].jar                    | None                                     |
       | LCHIJA | openterraingenerator                         | v8.3                  | OpenTerrainGenerator-1.12.2+-+v8.3.jar               | None                                     |
       | LCHIJA | biomebundle                                  | 5.1                   | Biome_Bundle-1.12.2-v6.1.jar                         | None                                     |
       | LCHIJA | buildcraftlib                                | 7.99.24.3             | buildcraft-all-7.99.24.3.jar                         | None                                     |
       | LCHIJA | buildcraftcore                               | 7.99.24.3             | buildcraft-all-7.99.24.3.jar                         | None                                     |
       | LCHIJA | buildcraftbuilders                           | 7.99.24.3             | buildcraft-all-7.99.24.3.jar                         | None                                     |
       | LCHIJA | buildcrafttransport                          | 7.99.24.3             | buildcraft-all-7.99.24.3.jar                         | None                                     |
       | LCHIJA | buildcraftsilicon                            | 7.99.24.3             | buildcraft-all-7.99.24.3.jar                         | None                                     |
       | LCHIJA | buildcraftcompat                             | 7.99.24.3             | buildcraft-all-7.99.24.3.jar                         | None                                     |
       | LCHIJA | buildcraftenergy                             | 7.99.24.3             | buildcraft-all-7.99.24.3.jar                         | None                                     |
       | LCHIJA | buildcraftfactory                            | 7.99.24.3             | buildcraft-all-7.99.24.3.jar                         | None                                     |
       | LCHIJA | buildcraftrobotics                           | 7.99.24.3             | buildcraft-all-7.99.24.3.jar                         | None                                     |
       | LCHIJA | ctm                                          | MC1.12.2-0.3.3.22     | CTM-MC1.12.2-0.3.3.22.jar                            | None                                     |
       | LCHIJA | chisel                                       | MC1.12.2-1.0.1.44     | Chisel-MC1.12.2-1.0.1.44.jar                         | None                                     |
       | LCHIJA | chiselsandbits                               | 14.33                 | chiselsandbits-14.33.jar                             | None                                     |
       | LCHIJA | chunkanimator                                | 1.2                   | ChunkAnimator-MC1.12-1.2.jar                         | None                                     |
       | LCHIJA | classiccombat                                | 1.0.1                 | ClassicCombat-1.0.1.jar                              | None                                     |
       | LCHIJA | sanlib                                       | 1.5.1                 | SanLib-1.12.2-1.5.1.jar                              | df48348748b5e141b1d118e2302a8d5be930b708 |
       | LCHIJA | claysoldiers                                 | 3.0.0-beta.2          | ClaySoldiersMod-1.12.2-3.0.0-beta.2.jar              | None                                     |
       | LCHIJA | codechickenlib                               | 3.2.3.358             | CodeChickenLib-1.12.2-3.2.3.358-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | cofhcore                                     | 4.6.3                 | CoFHCore-1.12.2-4.6.3.27-universal.jar               | None                                     |
       | LCHIJA | cofhworld                                    | 1.3.1                 | CoFHWorld-1.12.2-1.3.1.7-universal.jar               | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | extendedrenderer                             | v1.0                  | coroutil-1.12.1-1.2.32.jar                           | None                                     |
       | LCHIJA | coroutil                                     | 1.12.1-1.2.32         | coroutil-1.12.1-1.2.32.jar                           | None                                     |
       | LCHIJA | configmod                                    | v1.0                  | coroutil-1.12.1-1.2.32.jar                           | None                                     |
       | LCHIJA | opframe                                      | 1.4.0                 | OnlinePicFrame_v1.4.31_mc1.12.2.jar                  | None                                     |
       | LCHIJA | creativecore                                 | 1.9.9                 | CreativeCore_v1.9.74_mc1.12.2.jar                    | None                                     |
       | LCHIJA | darknesslib                                  | 1.0.0                 | DarknessLib-1.12.2-1.0.0.jar                         | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCHIJA | movingworld                                  | 1.12-6.342            | movingworld-1.12-6.342-full.jar                      | None                                     |
       | LCHIJA | davincisvessels                              | @DVESSELSVER@         | davincisvessels-1.12-6.340-full.jar                  | None                                     |
       | LCHIJA | dimdoors                                     | 3.0.9+287             | DimensionalDoors-3.0.9-287.jar                       | None                                     |
       | LCHIJA | ic2                                          | 2.8.187-ex112         | industrialcraft-2-2.8.187-ex112.jar                  | de041f9f6187debbc77034a344134053277aa3b0 |
       | LCHIJA | mantle                                       | 1.12-1.3.3.55         | Mantle-1.12-1.3.3.55.jar                             | None                                     |
       | LCHIJA | tconstruct                                   | 1.12.2-2.13.0.171     | TConstruct-1.12.2-2.13.0.171.jar                     | None                                     |
       | LCHIJA | galacticraftcore                             | 4.0.2.238             | GalacticraftCore-1.12.2-4.0.2.238.jar                | None                                     |
       | LCHIJA | orelib                                       | 3.6.0.1               | OreLib-1.12.2-3.6.0.1.jar                            | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dsurround                                    | 3.6.0.2               | DynamicSurroundings-1.12.2-3.6.0.2.jar               | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | erebus                                       | 1.0.31                | Erebus-1.0.31.jar                                    | None                                     |
       | LCHIJA | eyesinthedarkness                            | 0.1.0                 | EyesInTheDarkness-0.1.0 (1).jar                      | None                                     |
       | LCHIJA | foamfix                                      | 0.10.9-1.12.2         | foamfix-0.10.9-1.12.2.jar                            | None                                     |
       | LCHIJA | cfm                                          | 6.3.1                 | furniture-6.3.1-1.12.2.jar                           | None                                     |
       | LCHIJA | minecraftfuture                              | 0.1.13                | future-mc-0.1.13.jar                                 | None                                     |
       | LCHIJA | galacticraftplanets                          | 4.0.2.238             | Galacticraft-Planets-1.12.2-4.0.2.238.jar            | None                                     |
       | LCHIJA | ichunutil                                    | 7.2.2                 | iChunUtil-1.12.2-7.2.2.jar                           | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | generallaymansaestheticspyingscreen          | 7.0.0                 | GeneralLaymansAestheticSpyingScreen-1.12.2-7.0.0.jar | None                                     |
       | LCHIJA | waila                                        | 1.8.26                | Hwyla-1.8.26-B41_1.12.2.jar                          | None                                     |
       | LCHIJA | infernalmobs                                 | 1.7.6                 | InfernalMobs-1.12.2.jar                              | None                                     |
       | LCHIJA | inventorytweaks                              | 1.64+dev.146.2180b27  | InventoryTweaks-1.64+dev.146.jar                     | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | ironbackpacks                                | 1.12.2-3.0.8-12       | IronBackpacks-1.12.2-3.0.8-12.jar                    | None                                     |
       | LCHIJA | libraryex                                    | 1.0.12                | LibraryEx-1.12.2-1.0.12.jar                          | None                                     |
       | LCHIJA | malisiscore                                  | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                         | None                                     |
       | LCHIJA | malisisdoors                                 | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                        | None                                     |
       | LCHIJA | stevekung's_lib                              | 1.1.5                 | SteveKunG's-Lib-1.12.2-1.1.5.jar                     | b3468b224a74e296555ad7efeb35f482e6f445de |
       | LCHIJA | moreplanets                                  | 2.1.10                | More-Planets-1.12.2-2.1.10-GC238.jar                 | b3468b224a74e296555ad7efeb35f482e6f445de |
       | LCHIJA | llibrary                                     | 1.7.19                | llibrary-1.7.19-1.12.2.jar                           | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | mowziesmobs                                  | 1.5.4                 | mowziesmobs-1.5.4.jar                                | None                                     |
       | LCHIJA | mutantbeasts                                 | 0.4.0                 | MutantBeasts-1.12.2-0.4.0.jar                        | None                                     |
       | LCHIJA | netherex                                     | 2.0.15                | NetherEx-1.12.2-2.0.15.jar                           | None                                     |
       | LCHIJA | realrender                                   | 1.2.3                 | realrender-1.2.3.jar                                 | None                                     |
       | LCHIJA | roguelike                                    | 1.8.0                 | RoguelikeDungeons-1.12.2-1.8.0.jar                   | None                                     |
       | LCHIJA | ropebridge                                   | 2.0.5                 | ropebridge-1.12-2.0.7.jar                            | None                                     |
       | LCHIJA | sanplayermodel                               | 1.1.1                 | SanLib-1.12.2-1.5.1.jar                              | None                                     |
       | LCHIJA | sekcphysics                                  | 0.1.0                 | sekcphysics-0.1.0.jar                                | None                                     |
       | LCHIJA | soundfilters                                 | 0.11_for_1.12         | SoundFilters-0.11_for_1.12.jar                       | None                                     |
       | LCHIJA | surge                                        | 2.0.77                | Surge-1.12.2-2.0.77.jar                              | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | texfix                                       | 4.0                   | TexFix+V-1.12-4.0.jar                                | None                                     |
       | LCHIJA | thermalfoundation                            | 2.6.3                 | ThermalFoundation-1.12.2-2.6.3.27-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermalexpansion                             | 5.5.4                 | ThermalExpansion-1.12.2-5.5.4.43-universal.jar       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermaldynamics                              | 2.5.5                 | ThermalDynamics-1.12.2-2.5.5.21-universal.jar        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | tp                                           | 3.2.34                | tinyprogressions-1.12.2-3.3.34-Release.jar           | None                                     |
       | LCHIJA | torohealthmod                                | 1.12.2-11             | torohealth-1.12.2-11.jar                             | None                                     |
       | LCHIJA | mysttmtgravitymod                            | 2.9.1                 | UpAndDownAndAllAround-1.12.2-2.9.1.jar               | None                                     |
       | LCHIJA | vanillafix                                   | 1.0.10-SNAPSHOT       | VanillaFix-1.0.10-99.jar                             | None                                     |
       | LCHIJA | xaerominimap                                 | 1.19.0                | Xaeros_Minimap_1.19.0_Forge_1.12.jar                 | None                                     |
       | LCHIJA | xaeroworldmap                                | 1.5.1                 | XaerosWorldMap_1.5.1_Forge_1.12.jar                  | None                                     |
       | LCHIJA | zombieawareness                              | 1.12.1-1.11.16        | zombieawareness-1.12.1-1.11.16.jar                   | None                                     |
       | LCHIJA | densemetals                                  | 2.0.0                 | DenseMetals-1.12.2-2.0.0.30.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | immersiveengineering                         | 0.12-92               | ImmersiveEngineering-0.12-92.jar                     | 4cb49fcde3b43048c9889e0a3d083225da926334 |
       | LCHIJA | structurize                                  | 1.12.2-0.10.124-ALPHA | structurize-1.12.2-0.10.124-ALPHA.jar                | None                                     |
       | LCHIJA | minecolonies                                 | 1.12.2-0.10.538-BETA  | minecolonies-1.12.2-0.10.538-BETA-universal.jar      | None                                     |
       | LCHIJA | phosphor-lighting                            | 1.12.2-0.2.6          | phosphor-1.12.2-0.2.6+build50-universal.jar          | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCHIJA | thebetweenlands                              | 3.5.3                 | TheBetweenlands-3.5.3-universal.jar                  | 38067d6878811efb38b6a045521cfd80b9b60b38 |
       | LCHIJA | weeping-angels                               | 1.12.2-37             | weeping-angels-37.jar                                | None                                     |
  Loaded coremods (and transformers): CreativePatchingLoader (CreativeCore_v1.9.74_mc1.12.2.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.9-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      Quark Plugin (Quark-r1.6-177.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      OTGCorePlugin (OTG-Core.jar)
                                        com.pg85.otg.forge.asm.excluded.OTGClassTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      FMLModule (mdxlib-3.0.0.22.jar)
                                        com.asx.mdx.AccessTransformer
                                      TransformLoader (DynamicSurroundings-1.12.2-3.6.0.2.jar)
                                        
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.3-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      LoadingPlugin (replaymod-1.12.2-2.2.0-b7.jar)
                                        
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      FutureMC (future-mc-0.1.13.jar)
                                        thedarkcolour.futuremc.asm.CoreTransformer
                                      SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.5.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
                                        
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
                                        
                                      MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.238.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      MovingWorldCore (movingworld-1.12-6.342-full.jar)
                                        
                                      mysttmtgravitymod (UpAndDownAndAllAround-1.12.2-2.9.1.jar)
                                        uk.co.mysterymayhem.gravitymod.asm.Transformer
                                      LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
                                        lumien.chunkanimator.asm.ClassTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - chiselsandbitsIntegration (Enabled/Not Forced)
                                   - wailaIntegration (Enabled/Not Forced)
                                   - quarkIntegration (Enabled/Not Forced)
  Suspected Mods: Better Portals (betterportals), Weeping Angels (weeping-angels)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [GCEntityPlayerMP['CatKrusader'/54, l='DankRealm Testing', x=107.30, y=64.00, z=86.25]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Johni0702** [comment]
Looks like the Weeping Angels mod calls `Entity.changeDimension()` with the dimension the player is already in. I didn't expect anyone to do that and quite frankly I'm surprised it didn't already blow up in vanilla.
Unless that is intentional, I'd suggest that call be skipped in Weeping Angels for same-world teleportation.

And while one's at it, setting the location in changeDimension to 0/0/0 and immediately afterwards to something else seems redundant and might cause the chunks around 0/0/0 to be sent to the client only to be dropped immediately afterwards.

**Comment by Johni0702** [comment]
Should be fixed as of Weeping Angels 1.12.2-41
