### ISSUE TITLE
With vanilla fix, pending packets trigger crash reports

### ISSUE THREAD

**Issue by Johni0702** [Johni0702/BetterPortals#433]
These are to be expected in MC pre-1.13 because MC didn't clear its task queue after disconnecting (and some mods rely on that), and packet handling code doesn't check if we're still connected before trying to access the world.
The issue here is that vanilla fix seems to generate a crash report for them (I assume they ignore the vanilla ones but not ones executed from our [ViewDemuxingTaskQueue](https://github.com/Johni0702/BetterPortals/blob/398e594e6e3bad62d52a91fd838e676dd4971f64/src/view/kotlin/de/johni0702/minecraft/view/impl/client/ViewDemuxingTaskQueue.kt)?).
https://hastebin.com/abosidakox.rb
https://hastebin.com/lunonaceqa.rb

**Comment by border999** [comment]
[debug.log](https://github.com/Johni0702/BetterPortals/files/4084381/debug.log)
[latest.log](https://github.com/Johni0702/BetterPortals/files/4084382/latest.log)

**Comment by Johni0702** [comment]
Happens without BP as well: https://github.com/DimensionalDevelopment/VanillaFix/issues/228
