### ISSUE TITLE
When near a portal terrain constantly reloads

### ISSUE THREAD

**Issue by SteveTDMiner** [Johni0702/BetterPortals#434]
This could be because of all my mods, if it is I will need to take this awesome mod out.

**Comment by Johni0702** [comment]
Given it's not supposed to do that, it almost certainly has to be one of your other mods.
Might be https://github.com/Johni0702/BetterPortals/issues/88 (I can't tell since you didn't provide any logs or anything), in which case you should update your mods.

**Comment by SteveTDMiner** [comment]
Thank you very much it is working as intended
