### ISSUE TITLE
Support for Mystcraft portals

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Johni0702/BetterPortals#447]
Mystcraft portals are a lot of fun. They also can't take you to another point within the same dimension unless you get yourself an intra-linking book, so in most cases you won't run into any recursion issues.

**Comment by Johni0702** [comment]
The mod's license is "All Rights Reserved" and as such does not allow me to support it in BP. They don't even provide any source code.

For non-trivial integrations, I'll generally only consider mods which are released under a GPLv3-compatible license (e.g. one of [these](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses)).
