### ISSUE TITLE
Crashing upon entering a Twilight Portal

### ISSUE THREAD

**Issue by Doedelsander** [Johni0702/BetterPortals#449]
Hello,

This is the third time my client crashes when I go thru a portal to the Twilight Forest, see crashlog.
[crash-2020-01-19_19.59.06-client.txt](https://github.com/Johni0702/BetterPortals/files/4083507/crash-2020-01-19_19.59.06-client.txt)

Love the mod BTW.

**Comment by Hadies-Alchemist** [comment]
i am also experiencing this same bug i hope it gets fixed soon

**Comment by Johni0702** [comment]
This looks like a combination of https://github.com/Johni0702/BetterPortals/issues/458 followed by https://github.com/Johni0702/BetterPortals/issues/432.
Should this happen again on portal usage after updating BuildCraft (once the update is available), please post an updated crash report.
