### ISSUE TITLE
Cavern II Incompatibility

### ISSUE THREAD

**Issue by Sonicx32** [Johni0702/BetterPortals#45]
The Caverns II mod portals form but no longer function with BetterPortals installed. The portal animation will display but when stepping through, no longer teleports the player to the Cavern dimension. Once BetterPortals is removed from the pack, the Cavern II portals begin to function as normal.

**Comment by Sonicx32** [comment]
After testing the latest release of this mod, it appears the bug still exists.

**Comment by Johni0702** [comment]
Last release was seven days ago. The above fix hasn't yet made it to curseforge (though it probably will today).
