### ISSUE TITLE
Serene Seasons crash

### ISSUE THREAD

**Issue by UberApril** [Johni0702/BetterPortals#451]
had a ton of mods installed, BetterPortals would work but occasionally crash on entering a portal. narrowed down all the mods to Serene Seasons. only crashes when Serene Seasons is installed.
[crash-2020-01-20_21.15.46-client.txt](https://github.com/Johni0702/BetterPortals/files/4087872/crash-2020-01-20_21.15.46-client.txt)

**Comment by Johni0702** [comment]
This needs to be fixed in Serene Seasons but they no longer support 1.12.
