### ISSUE TITLE
Entity Crash.

### ISSUE THREAD

**Issue by border999** [Johni0702/BetterPortals#453]
https://paste.dimdev.org/genugonepe.mccrash

**Comment by border999** [comment]
and this one I have no idea about but it also showed up.
https://paste.dimdev.org/atipizinez.mccrash

**Comment by Johni0702** [comment]
Known issue though not yet sure what causes it nor how to reproduce it.

**Comment by border999** [comment]
https://paste.dimdev.org/setaxifere.mccrash
Check this one out

**Comment by Johni0702** [comment]
See https://github.com/Johni0702/BetterPortals/issues/449#issuecomment-583765148
