### ISSUE TITLE
Game freezes (not CTD)

### ISSUE THREAD

**Issue by festro** [Johni0702/BetterPortals#456]
The game will freeze a short period after interacting with compact machines. After activating the personal shrinking device nothing seems to happen for a few seconds then blocks and other entities stop responding but sound and music still plays you can move around next everything just freezes.
here's the crash info from the log
[latest.log](https://github.com/Johni0702/BetterPortals/files/4120940/latest.log)

**Comment by Johni0702** [comment]
Looks like an issue with JourneyMap. They don't provide any source code for their mod, so I can't look further into this, you'll have to report it to them and hope for the best.

**Comment by festro** [comment]
ok thanks.

**Comment by Johni0702** [comment]
FYI one of the JourneyMap devs provided the relevant part of its source in https://github.com/Johni0702/BetterPortals/issues/450#issuecomment-579485347 and I'm fairly certain as to what needs changing to fix the issue. If you want to be notified when I get to it, I'd recommend subscribing over there.

**Comment by festro** [comment]
cool, great to know love journey map xaero's minimap has been making do but doesn't work as well as journey map.
