### ISSUE TITLE
[0.3.7.4] BetterPortals and New Tardis Mod Not Compatible

### ISSUE THREAD

**Issue by Alan2188** [Johni0702/BetterPortals#460]
Issue: B:"See-through portals"=true tries to make the new tardis mod tardis see through, but it already has the bigger in the inside effect and it is see through without the BetterPortals mod. But when you open the tardis door the world leaks out and burns onto my screen with bubbles. Inside the tardis and outside the tardis both do this.
![image](https://user-images.githubusercontent.com/40438709/73546272-f3457a80-440a-11ea-9695-167e003e941f.png)
![image](https://user-images.githubusercontent.com/40438709/73546297-fd677900-440a-11ea-83a0-3bbe419cd4d4.png)

**Comment by Johni0702** [comment]
Try disabling the "Enhanced third-party transition" in the BetterPortals config.
I'm unable to find source code for the New Tardis Mod, so if there are further issues with it, please report those to them first.
