### ISSUE TITLE
Rendering glitch when attempting to "get out of" the end

### ISSUE THREAD

**Issue by yezhiyi9670** [Johni0702/BetterPortals#470]
## Description

When I try to "fly out of" the end the same way I get into it, I cannot succeed (for sure), but a picture of the things near the entrace portal will appear in front of my eyes for a very short time (maybe 1 tick).

## Enabled mods

Forge Version: 2846  
Optifine Version: HD U F5

The mods causing this issue are probably: Optifine, Surge, FoamFix, VanillaFix (if this issue is caused by incompatibility). Optifine is installed with Auto-install in HMCL, not installed as a mod.

[Here](https://pastebin.ubuntu.com/p/RqhwSXSgd6/) is a complete paste of my mods.

## How to reproduce

1. Build an end portal (or fix the one in the Stronghold).
2. Fly above the portal, and sneak to sink slowly into it. Then you'll be teleported to The End.
3. Look up and continue sinking slowly until the end portal frames above you become invisible.
4. Fly up looking down. A picture of the end portal frames (and other things around the portal in overworld) will appear for about 1 tick at the moment you get to the position where you entered the end.

This also happens when attempting to get out of the Twilight Forest by flying up. Perhaps it always happen with one-way portals.

## Possible solutions

1. Fix it natively (if possible)
2. Create a invisible barrier at the place of the teleporting destination (this may be strange).

**Comment by yezhiyi9670** [comment]
I think if I leave the issue here it will 110% get a `too many mods` tag, so I tried to reproduce the issue using Minecraft 1.12.2 with only Forge, Forgelin and BP installed. The same issue still occurs.

This means it's a bug of BP instead of a compability issue.

**Comment by Johni0702** [comment]
Yeah, I already tagged it with just `bug` because I have a pretty solid idea of why that might happen (and it doesn't care about other mods): 
The portal entity is still there, even if you cannot see or use it, but the code which determines the world your camera is in doesn't handle one-way portals, so it moves the camera to the other world for a few frames right after the camera crosses the portal plane until the next tick where the player entity is actually moved to the other world (and that's what it's supposed to do, just not with inactive one-way portals).

**Comment by yezhiyi9670** [comment]
So can it be fixed natively?

**Comment by Johni0702** [comment]
Most likely.

**Comment by Johni0702** [comment]
Side note: The issue can be very nicely reproduced by going into third-person and sticking the third-person camera through the invisible portal. With BP, the third-person camera is handled by the same code as camera movement between two ticks (the latter one is what this issue is about).

**Comment by Johni0702** [comment]
This should be fixed as of 0.3.7.7 along with two other one-way portal related issues (third-person camera could collide with blocks in the remote dimension even when portal is invisible and your player becoming visually cut in half if you fly through an invisible one-way portal).
Thanks for the report!
