### ISSUE TITLE
Chunk corruption twilight forest

### ISSUE THREAD

**Issue by Quadruplay** [Johni0702/BetterPortals#479]
When I make a tf portal and start jumping in and out after about 10 Times i get teleported to y=4 in tf and when i go back to the overworld, some chunks are swapped with tf chunks, the portal is solid (i can walk over it) and there is a new portal above, that has the intended visual effects, but doesn't tp me anywhere

**Comment by Johni0702** [comment]
Please attach the full game log.

**Comment by Quadruplay** [comment]
Where can I find it?

**Comment by Johni0702** [comment]
In your `.minecraft` folder there should be a `logs` folder containing a `debug.log`. Note that it only contains data from the last time you started MC, not any previous runs.

**Comment by Quadruplay** [comment]
[dont know which one so ill send u all.zip](https://github.com/Johni0702/BetterPortals/files/4270559/dont.know.which.one.so.ill.send.u.all.zip)
![2020-02-29_17 04 13](https://user-images.githubusercontent.com/61585172/75610954-4992ff80-5b16-11ea-88f4-89e74558a10a.png)
![2020-02-29_17 04 42](https://user-images.githubusercontent.com/61585172/75610955-4bf55980-5b16-11ea-90f2-f8bb69ee07ba.png)

**Comment by Quadruplay** [comment]
this time i got tp'd very high in the overworld and also these blocks appeared

**Comment by Johni0702** [comment]
Looks like it's the same error as #356 which I've yet to do a deep dive on (wasn't able to figure out the cause from just looking at Betweenlands' source).
