### ISSUE TITLE
magma n bp no like it when you die outside of the overworld, it freeze up when respawn and crash when dissconnect

### ISSUE THREAD

**Issue by Redd56** [Johni0702/BetterPortals#480]
log as it crashes https://pastebin.com/BUgmiee1
and
crashlog https://pastebin.com/qbHyPJAF
and
debug log https://pastebin.com/Bq2fKZuU

basicly, when you die in another dim, its fine, untill you hit respawn, then the server locks up, thats the log as it crashes bit. You yourself respawn but in nothingness, as the server has no idea where to put you, the second you dissconnect tho it crashes the server and the crashlog is output as it shuts down. Wierd crash but okay

ima bat at the fences and say that its probably a mixin not working quite right but im litteraly guessing from the little stuff i know, otherwise it works fine, tho ima do more testing and see if teleprotation is also bugged. if it is ill let ya know

**Comment by Redd56** [comment]
finaly getting to it me and kyle, cant believe it took so long lmao

**Comment by Hexeption** [comment]
This can be closed fixed in https://github.com/magmafoundation/Magma/commit/db983a58fc917f5f8ea169545407198a741572d9
