### ISSUE TITLE
Texture glitch

### ISSUE THREAD

**Issue by Scifantech** [Johni0702/BetterPortals#495]
I to am having the same texture glitch that was reported in issue #375, so I started with a fresh install of minecraft 1.12.2 and put no other mods on it besides Better Portals and Shadowfacts' Forgelin, and I am still having the issue. Any idea what I may doing wrong?

**Comment by Johni0702** [comment]
Please attach the full client log (`.minecraft/logs/debug.log`) and post a screenshot of your issue, so I can be sure it's actually the same as the other one.

**Comment by Scifantech** [comment]
I am posting 2 screenshots, 1-The glitched texture and 2-what it looks like when you step through.
[debug.log](https://github.com/Johni0702/BetterPortals/files/4399309/debug.log)
![2020-03-29_11 54 33](https://user-images.githubusercontent.com/6901912/77855267-e77cf700-71b4-11ea-92dc-61e03f76809f.png)
![2020-03-29_11 54 57](https://user-images.githubusercontent.com/6901912/77855269-efd53200-71b4-11ea-9866-63325d22cd30.png)

**Comment by Scifantech** [comment]
Figured out what the problem was, I had to remove LiteLoader. Thank you for a wonderful mod.

**Comment by Johni0702** [comment]
That's weird, it looks like BP wasn't able to replace the original portal block, did you have any other mods installed (which may have overwritten the portal themselves, taking priority over BP) or was it just LiteLoader?

**Comment by Scifantech** [comment]
No other mods but I was going to use Snow!Real!Magic! in my mod pack I am building. This was causing the Ice, Snow and Torch blocks textures to be pink and black checkered when I had them in my hand. After I placed them down they look normal in world. The creator of that mod told me it was LiteLoader doing this. So I got to thinking about the glitch in Better Portals and it works great as long as LiteLoader is not installed.

**Comment by Johni0702** [comment]
Ah right, I remember now, I've looked into this quite some time ago: LiteLoader breaks registry substitution, which is how BP (prior to 0.4) replaces the vanilla portal. There's a mod which attempts to fix it: https://www.curseforge.com/minecraft/mc-mods/extra-foam-for-liteloader

**Comment by Scifantech** [comment]
Thank you again I will try it here in a little bit. Again awesome mod thank you so much.
