### ISSUE TITLE
Better Portals Crash on start up

### ISSUE THREAD

**Issue by Shadowninja397** [Johni0702/BetterPortals#500]
I just added better portals to my modpack because it is a cool mod and it tries to construct the mod and for whatever reason it crashes. I realize there are similar issues but I hadn't seen any progress made with them so i figured i might have better luck. Below is the crash report.
[crash-2020-04-06_14.47.13-client.txt](https://github.com/Johni0702/BetterPortals/files/4440733/crash-2020-04-06_14.47.13-client.txt)

**Comment by Johni0702** [comment]
It's difficult to tell from the crash report what caused the crash (all I can tell is that there's probably another mod changing something about the `net.minecraft.client.renderer.EntityRenderer` class in a way that conflicts with the changes which BP needs to make to that class, can't tell which mod or which change). There should be a more helpful error message earlier in the log.

**Comment by Shadowninja397** [comment]
I did a test with every mod going down from the top of the mod list and it appears to be overpowered armor bar mod

**Comment by Shadowninja397** [comment]
so i went through mod by mod adding them one at a time with BP in there, and now it seems to work perfectly fine, so who knows what the cause was
