### ISSUE TITLE
Crash on start up with twitch launcher

### ISSUE THREAD

**Issue by Matteo13579** [Johni0702/BetterPortals#503]
Hi, If i start the game with the mod installed it crash and return me this log
[crash-2020-04-11_08.30.49-client.txt](https://github.com/Johni0702/BetterPortals/files/4464146/crash-2020-04-11_08.30.49-client.txt)

How can i solve this problem?

**Comment by Johni0702** [comment]
You're using an old version of BP.

**Comment by Matteo13579** [comment]
In this game i tried with an old version but if i update the mod the game crash anyway
