### ISSUE TITLE
Nether portal stopped rendering overworld and became unpassable.

### ISSUE THREAD

**Issue by DestructionMaker** [Johni0702/BetterPortals#506]
For some reason nether portal randomly stopped rendering overworld inside it after working fine for several minutes and it is not possible to walk thru it anymore, its like there are unbreakable unpassable blocks filling inside of frame (no block info shows up on waila/probe when looking thru portal tho). For some reason sounds stopped working as well at same time and cant be fixed with reloading resources/rejoining. Tried breaking the frame and reactivating it but the problem stays.

This is what it looks like ingame (I use settings with complete portal transparency without vanilla wiggly-texture-thing, like on curseforge pictures):
https://i.imgur.com/DUNgVgx.png

I think those are the logs (never posted anything here sorry):
[latest.log](https://github.com/Johni0702/BetterPortals/files/4472954/latest.log)

**Comment by DestructionMaker** [comment]
update: apparently it got fixed by removing [Hated Mobs](https://www.curseforge.com/minecraft/mc-mods/hated-mobs) mod, an incompatibility perhaps?

**Comment by Johni0702** [comment]
Looks like an issue in Hated Mobs: https://github.com/FrenchUranoscopidae/Hated_Mobs/issues/21

The only thing which changes with BP is that it appears to only kill the dimension where the entity was supposed to be spawned instead of the entire game.
