### ISSUE TITLE
Game doesn't start when Smooth Entity Light, Matmos, and Better Portals is present, crashes with exit code -1

### ISSUE THREAD

**Issue by Wolframme** [Johni0702/BetterPortals#507]
Ran into this crash and narrowed it down - this crash only happens when both Smooth Entity Light AND Matmos are present with Better Portals. If either mod is present but not the other, it does not crash. Swiftly after launch crashes with exit code -1.

https://pastebin.com/nRBs6Q4j

**Comment by Johni0702** [comment]
This is caused by SEL's core mod. See https://github.com/LakMoore/Smooth-Entity-Light/issues/12.
