### ISSUE TITLE
Better Portals Crashes Server When Using Galacticraft

### ISSUE THREAD

**Issue by HarrisonReed04** [Johni0702/BetterPortals#508]
I'm hosting a heavily modded server, with Galacticraft enabled. I can go to space on single player with absolutely no issues, but when i attempt to land in any dimension (any planet), the server outputs an error, with galacticraft saying that 'a 3rd party mod changed something without them noticing', the server carries on fine, but the client is frozen and when closing the client, the server then crashes with this crash report- 
https://pastebin.com/m5UfSsTi 

Edit- galacticraft works perfectly fine on the server without BetterPortals

**Comment by Johni0702** [comment]
Know compatibility issue which needs to be fixed in Galacticraft: https://github.com/micdoodle8/Galacticraft/issues/3835
