### ISSUE TITLE
Shooting arrows through portals will cause them to emit tipped arrow particles

### ISSUE THREAD

**Issue by Hudeler** [Johni0702/BetterPortals#51]
![Tipped arrow](https://user-images.githubusercontent.com/16482071/58764849-6c36be80-856c-11e9-9c93-a9a8cfe7b180.gif)

**Comment by Johni0702** [comment]
Turns out this is a (yet to be fixed) bug in vanilla MC which has been known since 2016: [MC-107941](https://bugs.mojang.com/browse/MC-107941)

Even though it's more obvious with BP, I'm not up for fixing vanilla's bugs (unless required).
