### ISSUE TITLE
Crash on teleport with skylands mod

### ISSUE THREAD

**Issue by SylisMC** [Johni0702/BetterPortals#513]
Hey ive been using [skyland by kegare](https://kegare.github.io/skyland/) and unfortunately i get a crash when landing teleporting from the skyland to the overworld (the void in the skyland teleports you to the sky in the overworld and you fall to the ground) crashing the game when you touch the ground. the only think i reconize from the crash report is "Forgelin" so i believe the issue is with either better portals or forgelin

Here is my crash report, for the time being am i able to disable the animation on teleporting? (not sure if it will make a difference but its worth a try) thanks

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin︱v1.8.4︱1.12.2.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 4/21/20 7:48 PM
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:233)
	at net.minecraft.client.audio.SoundHandler.func_73660_a(SoundHandler.java:293)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1857)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:233)
	at net.minecraft.client.audio.SoundHandler.func_73660_a(SoundHandler.java:293)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Sylis'/155, l='MpServer', x=-388.50, y=65.00, z=-295.50]]
	Chunk stats: MultiplayerChunkCache: 599, 599
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-121,64,76), Chunk: (at 7,4,12 in -8,4; contains blocks -128,0,64 to -113,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 6080 game time, 50971 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 46 total; [EntityBat['Bat'/35200, l='MpServer', x=-431.50, y=46.00, z=-215.50], EntityBat['Bat'/35202, l='MpServer', x=-344.50, y=21.00, z=-343.50], EntityRabbit['Rabbit'/259, l='MpServer', x=-437.16, y=69.00, z=-252.00], EntityRabbit['Rabbit'/260, l='MpServer', x=-441.88, y=69.00, z=-253.47], EntitySquid['Squid'/33796, l='MpServer', x=-379.90, y=59.19, z=-313.73], EntitySquid['Squid'/33797, l='MpServer', x=-378.54, y=58.08, z=-310.19], EntitySquid['Squid'/33798, l='MpServer', x=-375.97, y=58.46, z=-308.23], EntityRabbit['Rabbit'/263, l='MpServer', x=-449.50, y=64.00, z=-310.50], EntitySquid['Squid'/33799, l='MpServer', x=-372.98, y=59.95, z=-306.76], EntityRabbit['Rabbit'/264, l='MpServer', x=-453.50, y=65.00, z=-309.50], EntityBat['Bat'/34697, l='MpServer', x=-429.37, y=43.40, z=-230.81], EntityRabbit['Rabbit'/266, l='MpServer', x=-433.50, y=62.00, z=-305.50], EntityCreeper['Creeper'/34570, l='MpServer', x=-399.50, y=49.00, z=-239.50], EntityBat['Bat'/34698, l='MpServer', x=-426.83, y=43.82, z=-228.54], EntityEnderman['Enderman'/34954, l='MpServer', x=-430.50, y=46.00, z=-216.50], EntityCreeper['Creeper'/34572, l='MpServer', x=-398.50, y=49.00, z=-239.50], EntityRabbit['Rabbit'/272, l='MpServer', x=-456.50, y=64.00, z=-286.58], EntityRabbit['Rabbit'/273, l='MpServer', x=-456.50, y=64.00, z=-286.92], EntityRabbit['Rabbit'/274, l='MpServer', x=-460.68, y=64.00, z=-283.56], EntityRabbit['Rabbit'/275, l='MpServer', x=-433.50, y=61.00, z=-302.50], EntityPlayerSP['Sylis'/155, l='MpServer', x=-388.50, y=65.00, z=-295.50], EntitySpider['Spider'/34464, l='MpServer', x=-465.50, y=53.00, z=-250.50], EntityPig['Pig'/300, l='MpServer', x=-335.40, y=63.00, z=-220.43], EntityPig['Pig'/302, l='MpServer', x=-342.29, y=63.00, z=-220.38], EntityBat['Bat'/35118, l='MpServer', x=-415.42, y=33.00, z=-328.52], EntityRabbit['Rabbit'/20655, l='MpServer', x=-378.63, y=65.00, z=-287.81], EntityBat['Bat'/34619, l='MpServer', x=-372.25, y=22.87, z=-266.25], EntitySkeleton['Skeleton'/34372, l='MpServer', x=-371.50, y=23.00, z=-268.50], EntitySkeleton['Skeleton'/34373, l='MpServer', x=-372.50, y=23.00, z=-270.50], EntityBat['Bat'/34760, l='MpServer', x=-457.34, y=29.36, z=-272.06], EntityRabbit['Rabbit'/20689, l='MpServer', x=-390.72, y=65.00, z=-283.21], EntityCreeper['Creeper'/35026, l='MpServer', x=-423.50, y=32.00, z=-318.50], EntityCreeper['Creeper'/35027, l='MpServer', x=-422.50, y=32.00, z=-318.50], EntityCreeper['Creeper'/35028, l='MpServer', x=-419.50, y=32.00, z=-323.50], EntityEnderman['Enderman'/35029, l='MpServer', x=-418.50, y=32.00, z=-317.50], EntityBat['Bat'/34529, l='MpServer', x=-423.69, y=32.99, z=-321.74], EntityRabbit['Rabbit'/233, l='MpServer', x=-406.50, y=65.00, z=-221.50], EntityRabbit['Rabbit'/234, l='MpServer', x=-396.82, y=64.00, z=-218.52], EntityRabbit['Rabbit'/235, l='MpServer', x=-398.72, y=64.00, z=-224.46], EntityPig['Pig'/20723, l='MpServer', x=-335.51, y=63.00, z=-228.29], EntityBat['Bat'/34933, l='MpServer', x=-441.30, y=48.35, z=-225.50], EntitySquid['Squid'/33782, l='MpServer', x=-394.14, y=59.86, z=-322.91], EntitySquid['Squid'/33783, l='MpServer', x=-397.01, y=60.78, z=-317.59], EntitySquid['Squid'/33784, l='MpServer', x=-390.07, y=61.26, z=-318.57], EntitySkeleton['Skeleton'/35064, l='MpServer', x=-463.50, y=28.00, z=-225.50], EntityRabbit['Rabbit'/252, l='MpServer', x=-417.37, y=66.00, z=-285.49]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3825281128 bytes (3648 MB) / 5234491392 bytes (4992 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID            | Version                 | Source                                | Signature                                |
	|:--------- |:------------- |:----------------------- |:------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft     | 1.12.2                  | minecraft.jar                         | None                                     |
	| UCHIJAAAA | mcp           | 9.42                    | minecraft.jar                         | None                                     |
	| UCHIJAAAA | FML           | 8.0.99.99               | forge-1.12.2-14.23.5.2768.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge         | 14.23.5.2768            | forge-1.12.2-14.23.5.2768.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | aether_legacy | 1.4.4                   | Aether︱v1.4.4︱MC1.12.2.jar            | None                                     |
	| UCHIJAAAA | forgelin      | 1.8.4                   | Forgelin︱v1.8.4︱1.12.2.jar            | None                                     |
	| UCHIJAAAA | betterportals | 0.3.6.1                 | betterportals-0.3.6.1.jar             | None                                     |
	| UCHIJAAAA | conquest      | 3.0.2                   | Conquest Reforged︱v3.0.2︱MC1.12.2.jar | None                                     |
	| UCHIJAAAA | blockpalette  | 1.5.0                   | Conquest Reforged︱v3.0.2︱MC1.12.2.jar | None                                     |
	| UCHIJAAAA | connect       | 1.0.3-mc1.12.2-SNAPSHOT | Conquest Reforged︱v3.0.2︱MC1.12.2.jar | None                                     |
	| UCHIJAAAA | skyland       | 1.5.3                   | Skyland︱v1.5.3︱1.12.2.jar             | None                                     |
	| UCHIJAAAA | worldedit     | 6.1.10-SNAPSHOT         | worldedit forge︱v6.1.10S︱1.12.2.jar   | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin︱v1.8.4︱1.12.2.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 445.87' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.87, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Conquest ReforgedÃƒÆ’Ã‚Â¯Ãƒâ€šÃ‚Â¸Ãƒâ€šÃ‚Â±Resource packÃƒÆ’Ã‚Â¯Ãƒâ€šÃ‚Â¸Ãƒâ€šÃ‚Â±1.12.2.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 3600X 6-Core Processor `

**Comment by Johni0702** [comment]
Looks like a bug in Skylands which for some reason only gets triggered with BP.

> for the time being am i able to disable the animation on teleporting?

"Enhance third-party transfers" in the config.

**Comment by SylisMC** [comment]
> Looks like a bug in Skylands which for some reason only gets triggered with BP.
That is unfortunate. I dont think the owner of skylands speaks any English haha xD thanks for reviewing this for me
