### ISSUE TITLE
Weird glitch with BetterPortals

### ISSUE THREAD

**Issue by SSpiritWolf** [Johni0702/BetterPortals#516]
I honestly have no idea what's happening here, please help. It was perfectly fine before I opened the portal, then it messed up. FastRender and SmoothWorld are off, if you are wondering.
![2020-04-27 (5)](https://user-images.githubusercontent.com/64447478/80434234-4e322500-88c7-11ea-865e-3f13311fd260.png)
Apparently, when I look away, that portion disappears.
![2020-04-27 (6)](https://user-images.githubusercontent.com/64447478/80434503-e9c39580-88c7-11ea-93b6-60e13a7eaf15.png)

**Comment by Johni0702** [comment]
That's because the "Debug View" in BP's config has been enabled.

Did you enable it and forgot about it or are you using a mod pack which had it enabled? I'm genuinely curious cause there have been quite a few reports about it.
