### ISSUE TITLE
Crash on startup (Twitch Launcher) - MC 1.12.2 / Forge

### ISSUE THREAD

**Issue by schnabeldoktor** [Johni0702/BetterPortals#517]
Game fails to initiate after clicking "play" on the latest launcher for MC 1.12.2.
I am suspecting one or several of my mods are interfering with it (around 40-50)

A profile with ONLY Forgelin and BP works fine. 

Crash log: 
[latest.log](https://github.com/Johni0702/BetterPortals/files/4568383/latest.log)

**Comment by Johni0702** [comment]
Same as https://github.com/Johni0702/BetterPortals/issues/499.
Though I can't tell from the crash report which mod is shipping the newer Mixin (but it definitely is there), so to workaround simply rename the betterportals jar to start with `zzz`.
