### ISSUE TITLE
Screen is blank on startup

### ISSUE THREAD

**Issue by Geezt435** [Johni0702/BetterPortals#520]
When I started BetterPortal mod in my world, my screen goes blanks all the time

**Comment by Johni0702** [comment]
If you've got Optifine installed, try disabling Anti-Aliasing. If that doesn't fix it, try resetting (by deleting) the `optionof.txt` file in your `.minecraft` folder.
If neither helps, I'll need more information.

**Comment by Geezt435** [comment]
Ok, it fixed by deleting optionsof.txt, thanks
