### ISSUE TITLE
Game crashes on start (fails to launch)

### ISSUE THREAD

**Issue by SpencerMeow** [Johni0702/BetterPortals#528]
Whenever I try to launch the game, even with Forgelin, it gives an error message "Game crashed: "An unexpected issue occurred and the game has crashed, We're sorry for the inconvenience." It doesn't generate any crash report as far as I can tell, and I'm not using any mods with it. I'm launching it from Twitch.

**Comment by Johni0702** [comment]
Will need the game log then, otherwise I can derive about as much from the error message as you can.

**Comment by Jetprism** [comment]
https://paste.ubuntu.com/p/xGfsnrkv2C/

**Comment by Jetprism** [comment]
that's my log,same issue here

**Comment by Johni0702** [comment]
Duplicate of #512
