### ISSUE TITLE
Incompatibility with Dynamic Surroundings

### ISSUE THREAD

**Issue by BlueHedgy** [Johni0702/BetterPortals#535]
So upon testing to launch my personal mod pack
I found out that better portal always exit with code -1 when launched with Dynamic surrounding
I don't think the log helps much but you can find it in attachment
[crash log BP DS.txt](https://github.com/Johni0702/BetterPortals/files/4787098/crash.log.BP.DS.txt)

**Comment by Johni0702** [comment]
Duplicate of #512
