### ISSUE TITLE
Compatability with Galacticraft

### ISSUE THREAD

**Issue by Juice420** [Johni0702/BetterPortals#540]
After launching a rocket and in the planet selector screen when you select a planet it is stuck on the loading screen. The game crashed once because of this and because I have vanilla fix it told me that betterportals created a problem. Is there a workaround to make it so it doesn't do anything with the galacticraft mod?

**Comment by Johni0702** [comment]
Known issue, there's no workaround, the way galacticraft teleports player to different dimensions is fundamentally incompatible with BP: https://github.com/micdoodle8/Galacticraft/issues/3835
