### ISSUE TITLE
Strange Screen Bug

### ISSUE THREAD

**Issue by MCSuperplayer** [Johni0702/BetterPortals#541]
I Opened a nether Portal

What I expected to happen: I can see through the Portal

What happened: See Screenshot
![2020-06-27_16 56 44](https://user-images.githubusercontent.com/53540819/85925317-f0569500-b897-11ea-94f1-70c4bdc8c209.png)

BP Version: latest MC 1.12.2 Forge 14.23.5.2847

if any information is missing inform me and i add it

**Comment by Johni0702** [comment]
You've enabled the debug view, so that's what you're seeing.

**Comment by MCSuperplayer** [comment]
And how do i disable that?

**Comment by Johni0702** [comment]
In the ingame settings (via Mods -> Better Portals -> Config) or the config file.
