### ISSUE TITLE
Crashes randomly when lighting a portal

### ISSUE THREAD

**Issue by CyberCat30** [Johni0702/BetterPortals#544]
Whenever I light the 3rd portal in my map, there's a chance the game freezes or crashes. If it doesn't happen on the 3rd portal it always happens on the 4th. When I reload the world, it freezes or crashes again and I have to disable the mod, load the world, then enable the mod and load the world again for it to be playable, and at that point, I'm back to before I lit a single portal. I can't get it to work no matter what I do. I'm also using the portal gun mod if that matters.

**Comment by Johni0702** [comment]
Please attach the crash log.

**Comment by CyberCat30** [comment]
> Please attach the crash log.

There is no crash log for some reason

**Comment by Johni0702** [comment]
I've got nothing to go on then.

**Comment by CyberCat30** [comment]
I'm trying to make it generate a crash log but can't even get it to crash anymore without my entire PC freezing before it makes one

**Comment by CyberCat30** [comment]
> I've got nothing to go on then.

I'm dumb this should help
[debug.log](https://github.com/Johni0702/BetterPortals/files/4959393/debug.log)
[latest.log](https://github.com/Johni0702/BetterPortals/files/4959396/latest.log)

**Comment by Johni0702** [comment]
Looks like it ran out of memory. You've only assigned 2GB to MC, so it running out when you open many portals seems reasonable. That would also explain why, even if it can barely handle three, it'll always crash on the fourth.

**Comment by CyberCat30** [comment]
> Looks like it ran out of memory. You've only assigned 2GB to MC, so it running out when you open many portals seems reasonable. That would also explain why, even if it can barely handle three, it'll always crash on the fourth.

I gave it 2GB to make it crash since I was trying to get a crash log because 7GB would not make it crash but instead just kill the framerate
Also, my world data corrupted because of the portals and I'm trying to recover it and I went to the nether to find where the map is but as soon as i lit the portal my entire computer froze and I was on 7GB
[2020-07-22-7.log](https://github.com/Johni0702/BetterPortals/files/4962673/2020-07-22-7.log)
[debug.log](https://github.com/Johni0702/BetterPortals/files/4962674/debug.log)
[latest.log](https://github.com/Johni0702/BetterPortals/files/4962675/latest.log)
