### ISSUE TITLE
Game crash when startup

### ISSUE THREAD

**Issue by tt36999** [Johni0702/BetterPortals#551]
MC version 1.12.2
forge:14.23.5.2825
liteloader:1.12.2-SNAPSHOT
OPTIFINE:HD_U_F5
Java 1.8.0_231
BatterPortals: 0.3.7.7
ForgeLin: 1.8.4
No other mod installed
Game will instant crash before showing load screen
here are the log 
[minecraft-exported-logs-2020-08-02T14-50-12.log](https://github.com/Johni0702/BetterPortals/files/5011750/minecraft-exported-logs-2020-08-02T14-50-12.log)

**Comment by Johni0702** [comment]
This needs fixing in LiteLoader, you can try to report it to them. There is nothing which BP can do about it.
