### ISSUE TITLE
Incompatible with Dynamic Surroundings 

### ISSUE THREAD

**Issue by R3Birth13** [Johni0702/BetterPortals#560]
I Get no crash log, but I sorted through my mods and so far Dynamic Surroundings has taken my game back to the launch menu. I Don't know if it can be patched, but it's probably good to let others know. 

tldr; the game doesn't start; it just goes right to the launcher.

Vanilla Fix and Ice & Fire crash the game as well. I Can see Dynamic Surroundings and Vanillafix crashing, but why Ice & Fire?

**Comment by Johni0702** [comment]
Duplicate of #547
