### ISSUE TITLE
Crashes With Aether Legacy Installed

### ISSUE THREAD

**Issue by vizthex123** [Johni0702/BetterPortals#562]
Title. 

I'm very glad I could disable compatibility though, was really set on using this in my modpack.

Crash report attached.

[crash-2020-09-05_13.23.07-client.txt](https://github.com/Johni0702/BetterPortals/files/5178483/crash-2020-09-05_13.23.07-client.txt)

**Comment by Johni0702** [comment]
Duplicate of #557
