### ISSUE TITLE
Doesn't seem to work with OpenJDK

### ISSUE THREAD

**Issue by KiroTheBlueFox** [Johni0702/BetterPortals#563]
I can't open portals or go/see through them.
I discussed with some people about the logs of my game, and it seems that the mod needs an Oracle Java version, but I use OpenJDK instead.
Maybe you could fix it by trying to change all the javax and other Oracle Java calls/imports into other stuff that would be compatible with other JDKs.

**Comment by Johni0702** [comment]
That can't be it. I've developed this mod on Fedora and ran it on Debian a few times, both of which use OpenJDK.

`javax` has nothing to do with Oracle and should be present in any JRE, see https://stackoverflow.com/a/727852.

**Comment by KiroTheBlueFox** [comment]
Oh okay, well here is the latest log I have
https://hastebin.com/ojaqixihoc.sql

Error :
```
[18:55:46] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class de.johni0702.minecraft.betterportals.common.FinitePortal
```

**Comment by Johni0702** [comment]
That looks like a broken coremod (probably one of ChickenASM, CreativeCore, CTM or malisiscore). Try to figure out which one by removing them all and trying to reproduce it with one at a time, then report it to that one.

FYI you're not even using OpenJDK:
```
[18:50:05] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at E:\Program Files (x86)\Minecraft Launcher\runtime\jre-x64
```

**Comment by KiroTheBlueFox** [comment]
Well I have only OpenJDK installed on my pc, I don't remember having installed Java 🤔

**Comment by KiroTheBlueFox** [comment]
Found the incompatibility : It's due to Real Train Mod, which is a japanese mod that loads models with a custom model loader iirc
Maybe that model loader destroys your class loader or something
