### ISSUE TITLE
[1.12.2] [BUG] Major crash every time anyone teleports crossdim

### ISSUE THREAD

**Issue by SlimefrogSocial** [Johni0702/BetterPortals#581]
Whenever anyone on the server uses /back /bed /tpa /spawn or any other command that teleports 
them to another dimension, the server fatally crashes.
https://github.com/ForgeEssentials/ForgeEssentials/files/5631780/modlist.txt
https://github.com/ForgeEssentials/ForgeEssentials/files/5631770/crash-2020-12-02_14.11.37-server.txt
https://github.com/ForgeEssentials/ForgeEssentials/files/5631776/2020-12-02-6.log
https://github.com/ForgeEssentials/ForgeEssentials/files/5631777/debug.log
This is a major issue on my server. Better Portals is not "critical" that it exists in the server but we all do enjoy it and I do not want to remove it.

**Comment by Johni0702** [comment]
Probably the same as https://github.com/DimensionalDevelopment/DimDoors/issues/130 and https://github.com/blay09/Waystones/issues/241 except the offending method is [here](https://github.com/ForgeEssentials/ForgeEssentials/blob/5a2ca8f51ec5c772ce4bb87f317b28b2136f6328/src/main/java/com/forgeessentials/core/misc/TeleportHelper.java#L298-L329).
I suggest you report it to ForgeEssentials and link them to this issue.

**Comment by SlimefrogSocial** [comment]
Um, they said the same thing... any way you two could co-lab a solution?
https://github.com/ForgeEssentials/ForgeEssentials/issues/2573

**Comment by Johni0702** [comment]
They didn't say the same thing.

They sent you here because they didn't know just from looking at the crash what causes it and figured I might know so they don't have to spend lots of time to figure it out.

And indeed I did (cause two other mods also had a similar issue) and sent you a link to the explanation and given that, they should now be able to fix it.

**Comment by SlimefrogSocial** [comment]
Oh I must have misread soz, thank you

**Comment by SlimefrogSocial** [comment]
Issue fixed, just forgot to close

**Comment by Vladilion90** [comment]
> Issue fixed, just forgot to close

Привет, подскажи как решил проблему? у меня такая же проблема, но ответа я так и не нашел. Я ставил даже только 1 мод Better portals и все без других  модов и плагинов, и даже это не помогло.
Так в чем же проблема?

Hi, tell me how I solved the problem? I have the same problem, but I haven't found the answer. I even put only 1 mod Better portals and all without other mods and plugins, and even this did not help.
So what's the problem?

**Comment by SlimefrogSocial** [comment]
Make sure you have updated Forge Essentials to the latest release, they put out a fix for it a while back. Unless something broke again in newer releases that should work. I am not using the latest release but I am far enough to fix this issue!

Убедитесь, что вы обновили Forge Essentials до последней версии, они исправили ее некоторое время назад. Если что-то не сломалось снова в новых выпусках, это должно сработать. Я не использую последнюю версию, но мне достаточно, чтобы исправить эту проблему!

I used google translate for this sorry if my grammar and such are off...

Я использовал Google Translate для этого, извините, если моя грамматика и тому подобное не работают ...

I just realized you said you removed all other mods, not sure this is the same crash if that is true and my only bet is to make sure you download the latest version of Better Portals from CurseForge (if you are downloading from any other site that could very well be the issue) have a good day!

Я только что понял, что вы сказали, что удалили все другие моды, не уверен, что это тот же сбой, если это правда, и моя единственная ставка - убедиться, что вы загрузили последнюю версию Better Portals с CurseForge (если вы загружаете с любого другого сайта, который вполне может быть проблема) хорошего дня!

https://www.curseforge.com/minecraft/mc-mods/betterportals
