### ISSUE TITLE
Betterportals on 1.12.2 crashes when combined with wolf armor and storage

### ISSUE THREAD

**Issue by sebastianalcala** [Johni0702/BetterPortals#590]
Whenever I try to run with curseforge my 1.12.2 minecraft installation with 42 mods, after i press play in the minecraft launcher, it shows the error 0 where it won't load the game, i started to look around and found that this error usually shows when there is a mixin between mods (or something like that) 

so... 

I started to one by one, disable every mod to find what was causing the issue, and it looks like the mod Wolf Armor and Storage
by satyrnidae was causing the problem, idk why, but when i disabled this mod, the game runs without issues.

**Comment by Johni0702** [comment]
https://github.com/Johni0702/BetterPortals/issues/547#issuecomment-681572932
