### ISSUE TITLE
Whenever I make a Portal, it Shows the Regular Portal Effect and the Nether

### ISSUE THREAD

**Issue by xXTheScribblesXx** [Johni0702/BetterPortals#591]
I was trying to do something that I recently saw in a cool video, so I decided to get the mod. When I made my first portal, I noticed that the regular portal effect was showing with the nether showing as well. I have tried to fix it but can't. Please help me.
![2021-02-27_21 22 08](https://user-images.githubusercontent.com/79775673/109405763-f67aa500-7941-11eb-8e01-44b38d018c97.png)

**Comment by Furglitch** [comment]
Go into the config file/mod options in game and look at the Nether Portal settings, then turn opacity down to 0

**Comment by xXTheScribblesXx** [comment]
Thank you!!
