### ISSUE TITLE
Constantly searching for player's [view] lagging server

### ISSUE THREAD

**Issue by snekta** [Johni0702/BetterPortals#595]
Hey Johni, really awesome mod. But unfortunately I'm having some problems with having more than 1 person online at a time. It works fine when I am on the server alone and go through both ways with no problems, but as soon as another player is around (one in another dimension, one in the overworld) it seems to be infinitely searching for their [view] which leads to lag and crashing the server. I have had a look in the mod and Gorecore to see if I could find the setting that loads/searches for these views but I am stumped and can't find anyone online having the same problem. Below is what I get in the console when I step through with another player online:

04.03 19:11:26 [Server] Server thread/INFO [betterportals/view]: Swapping main view -587.1549406154836/70.0/1447.3727698594053 with -323.5/62.0/1024.5
04.03 19:11:26 [Server] Server thread/WARN [GoreCore]: Attempted to get a UUID for player JumpinCaveDigger[view], but the response code was unexpected (404)
04.03 19:11:26 [Server] Server thread/WARN [GoreCore]: Attempted to get a UUID for player JumpinCaveDigger[view], but the response code was unexpected (404)
(repeated 30 times until I left the portal before it blew the  server up)

If you have any idea what I could do to address this I would be very grateful as this mod is one I really want to keep on the server. And any more info I can post to help I will post asap. Thanks!

**Comment by Johni0702** [comment]
The view entities are fake players spawned by BP in other worlds so they receive updates for those worlds and can forward those updates to the real player. They are an integral part of how BP works even with 3rd party mods which are unaware of it.

I'm guessing GoreCore does HTTP requests to get a player's UUID by their name on the main thread (which is an absolutely horrible idea to begin with, like really bad, like it'll probably even explode when you're playing offline or while Mojang is unavailable, and the source of your lag) and then does not even cache the result in case of failure (and ofc view entities will error cause they aren't real players and as such you cannot look up their UUID by their name), so it'll do it over and over again every time it needs the UUID.
There is nothing I can do about that, it's an issue in GoreCore.

**Comment by snekta** [comment]
That is unfortunate. I understand it is outside of your mods hands now, but I'm wondering if there's any way you know of to prevent Gorecore from searching for those UUID's, or disable it completely? Because that's the only problem your mod seems to be having.. otherwise I will just uninstall it and go back to my primitive portals.
