### ISSUE TITLE
Description: Ticking entity

### ISSUE THREAD

**Issue by NatureGecko** [Johni0702/BetterPortals#596]
This happened on my server when one of my friend exited from The Midnight. It just happened after reaching The Midnight by my friend and me for more than 10 times. After the crash, someone just entered again and everything was fine.

[crash-2021-03-14_06.35.00-server.txt](https://github.com/Johni0702/BetterPortals/files/6153654/crash-2021-03-14_06.35.00-server.txt)

**Comment by Johni0702** [comment]
According to the crash report, you don't even have BetterPortals installed.
