### ISSUE TITLE
incompatibility with tlauncher skin system

### ISSUE THREAD

**Issue by number947** [Johni0702/BetterPortals#597]
I'm currently making my modpack for 1.12.2, using tlauncher.
And i would want to include betterPortals to it, but installing it causes an issue.
When i enable it, my tl skin disappears and i appear as Steve, or Alex.
BP version is 0.3.7.7 and Forgelin version is 1.8.4
Also tested without other mods and with/without Optifine enabled

**with BP**
![image](https://user-images.githubusercontent.com/44410578/113518852-1e84a600-9589-11eb-9baa-0509d223af0b.png)
![image](https://user-images.githubusercontent.com/44410578/113518876-4a079080-9589-11eb-8fcb-e4aaca525512.png)

**without BP**
![image](https://user-images.githubusercontent.com/44410578/113518909-7cb18900-9589-11eb-97ce-4660d303ec40.png)
![image](https://user-images.githubusercontent.com/44410578/113518920-8affa500-9589-11eb-859c-a961a9518715.png)

Please help

**Comment by Johni0702** [comment]
Buy the game.
