### ISSUE TITLE
1.16.4-0.3.8 Dedicated Server Crash on Feature Placement

### ISSUE THREAD

**Issue by kreezxil** [Johni0702/BetterPortals#610]
Server Crash Report: http://paste.ubuntu.com/p/7wCbVXV2Nw/
Server Latest Log: http://paste.ubuntu.com/p/7qSbhDpR9j/

MC: 1.16.5
Forge: 36.2.4

In pack: (my pack) https://www.curseforge.com/minecraft/modpacks/world-of-dragons-ii

**Happened while exploring**

**Comment by Johni0702** [comment]
This mod is for 1.12.2 only.
Also
![](https://i.johni0702.de/n3Fz9.png)

**Comment by kreezxil** [comment]
isn't this Yung's Better Portals, if not my bad.

**Comment by Johni0702** [comment]
No, this is just "BetterPortals": https://www.curseforge.com/minecraft/mc-mods/betterportals
