### ISSUE TITLE
Hand and held items don't render correctly

### ISSUE THREAD

**Issue by Hudeler** [Johni0702/BetterPortals#62]
![2019-06-04_19 27 30](https://user-images.githubusercontent.com/16482071/58900166-eeef8300-86fe-11e9-89c4-aba8b32a1c03.png)
![2019-06-04_19 27 41](https://user-images.githubusercontent.com/16482071/58900175-f44ccd80-86fe-11e9-8e94-4320b09d7bc0.png)
This happens even if there is no portal in the current world.

**Comment by DarianLStephens** [comment]
There seemed to be a bug before where your hand, or items held by them, wouldn't render at all.
That seems to be fixed, but it looks like FOV wasn't taken in to account. This is also visible if you sprint or do anything else that changes FOV in normal gameplay.
