### ISSUE TITLE
Exit Code: 1 when this mod is added to the modpack Im using

### ISSUE THREAD

**Issue by Devilswarchild** [Johni0702/BetterPortals#623]
log that is generated when I have your mod installed: https://pastebin.com/bd19YvbQ

Log without the mod installed just so you can see which mods I have: is attached

This error occurs shortlay after hitting play on the mc launcher and the output log starts scrolling. literally just a few seconds worth. not sure which mod is causing betterportals to throw this error but its definitely not my java causing the issue cause without the mod. the game runs normally without issue

[2022-07-31-7.log.gz](https://github.com/Johni0702/BetterPortals/files/9230488/2022-07-31-7.log.gz)
.

**Comment by Johni0702** [comment]
The log that's supposed to contain the error doesn't have the full error, it's way too short.

**Comment by Devilswarchild** [comment]
Thats what I thought as well. So definitely have no way of knowing which mod is causing the conflict outside of the exit code 1. Hence Why I attached a log of a successful launch without your mod so you can have a detailed list of what mods I was using to try to narrow it down further.

**Comment by Johni0702** [comment]
No, I'm saying you didn't copy enough of it. It's not that the log itself is incomplete on both ends (that would be highly unusual), it's much more likely that you just didn't copy the whole thing.
If you send the log the same way you did for the working game, it should be complete.

**Comment by Devilswarchild** [comment]
[2022-08-02-1.log.gz](https://github.com/Johni0702/BetterPortals/files/9252802/2022-08-02-1.log.gz)

it seems you were correct...hmmm

**Comment by Devilswarchild** [comment]
oops apparently that wasnt the right one

**Comment by Devilswarchild** [comment]
heres the right one, had to run it a couple times to get it to generate the new log
[2022-08-03-1.log.gz](https://github.com/Johni0702/BetterPortals/files/9253255/2022-08-03-1.log.gz)
[latest.log](https://github.com/Johni0702/BetterPortals/files/9253256/latest.log)


and having it opened it and actually looked at the zipped text doc it shows no more than what I already showed you

**Comment by Devilswarchild** [comment]
ok so I started with all the mods off except for betterportals and went through them one by one and everything was going good until I ran into an ID problem prompting me to turn on justenoughids and then started getting an error. so I assumed it was one of the other mods I have for enhancing the nether and tried them one by one with better portals and nothing. then I got the idea that what if it was an id conflict and tried betterportals with justenoughids active and got the error code -1. im going to safely assume its justenoughids conflicting with it and will continue testing other mods and see if I get any other errors

[2022-08-03-7.log.gz](https://github.com/Johni0702/BetterPortals/files/9253440/2022-08-03-7.log.gz)
this is just with betterportals and justenoughids

**Comment by Devilswarchild** [comment]
just tried those 2 with someother mods and now its working with justenoughids so now im not sure what the problem is

**Comment by Devilswarchild** [comment]
im still looking for a conflicting mod

**Comment by Devilswarchild** [comment]
not sure what was going on but every mod in the pack is now turned on and the error is no longer presenting itself, I have no idea what happened. however just want to point out that I had to add in mixin compatibility for another mod and since adding that I have not been able to get the error occur or at the very least that the way it seems.

Does betterportals use mixin at all?

**Comment by Devilswarchild** [comment]
found one with the aether mod though (just installed it)
"The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: de/johni0702/minecraft/betterportals/impl/aether/common/blocks/BlockBetterAetherPortal
Exit Code: -1"

[2022-08-03-7.log.gz](https://github.com/Johni0702/BetterPortals/files/9255538/2022-08-03-7.log.gz)

**Comment by Devilswarchild** [comment]
now im getting this whether betterportals is either turned on or disabled
[2022-08-03-7.log.gz](https://github.com/Johni0702/BetterPortals/files/9255778/2022-08-03-7.log.gz)

**Comment by Devilswarchild** [comment]
ive deleted the entire modpack and all its backups and am starting fresh and going from there, I will let you know how it goes

**Comment by Devilswarchild** [comment]
and now it all works flawlessly.... I have no idea what happened. but if something breaks i'll let you know in a new ticket or something
