### ISSUE TITLE
Mod pack not loading into my minecraft

### ISSUE THREAD

**Issue by Shadowboi96** [Johni0702/BetterPortals#624]
I downloaded the mod pack with the hopes of playing the game with the mods and when I downloaded the mod pack and extracted it to the mod folder for my minecraft game it doesn't load the mods into my mod pack. Is there a specific way you need to install each mod?
![unknown (3)](https://user-images.githubusercontent.com/111997715/186452974-9b2f1a51-595c-450e-92b8-b6f6adf2baff.png)

**Comment by Johni0702** [comment]
BetterPortals works on Minecraft 1.12.2 and 1.12.2 only.
