### ISSUE TITLE
Game doesn't start

### ISSUE THREAD

**Issue by Maks7594** [Johni0702/BetterPortals#627]
I use a modified by me version of RLcraft with more mods. when i launch the game the launcher disappears but the game is not launching. the game process is nowhere to be seen.
However, latest.log appears, so I sent it here.

OS info:
Windows 11 22H2,
NVIDIA Geforce RTX 3050 Laptop,
11th Gen Intel Core i5 (4 cores).

[latest.log](https://github.com/Johni0702/BetterPortals/files/9742319/latest.log)

**Comment by Johni0702** [comment]
Duplicate of #593
