### ISSUE TITLE
Mod crashes with the Aether

### ISSUE THREAD

**Issue by Maks7594** [Johni0702/BetterPortals#628]
Just tried loading up my modpack. I don't know if there are any incompatibilities with Betterportals but it only showed an error about some betterportals aether class. I attached the log btw

OS: Win11 22H2
CPU and GPU and RAM: why do you need those ¯\_(ツ)_/¯

[latest.log](https://github.com/Johni0702/BetterPortals/files/10247298/latest.log)

**Comment by Johni0702** [comment]
Duplicate of #593

**Comment by Maks7594** [comment]
> Duplicate of #593
searched the entire issues page, and i DIDNT FIND IT SOMEHOW???
