### ISSUE TITLE
[Bug] Tails mod doesn't display extra limbs when transferring dimensions

### ISSUE THREAD

**Issue by Inonedn** [Johni0702/BetterPortals#77]

**Comment by Johni0702** [comment]
You can try force-enabling Tails' legacy rendering, that should fix it (assuming it's not broken in another way).

Properly fixing this in BP requires non-trivial changes and since I don't like to make those on 0.1.x, I'll be postponing the fix to 0.2.

**Comment by Inonedn** [comment]
doesn't work, even if forced legacy
