### ISSUE TITLE
Steve's Carts 2 incompatibility

### ISSUE THREAD

**Issue by Mattwenty** [Johni0702/BetterPortals#86]
When I interact with this mod, the game crashes. Without BetterPortals mod, it works
I have crash logs
[crash-2019-06-16_21.59.35-client.txt](https://github.com/Johni0702/BetterPortals/files/3294534/crash-2019-06-16_21.59.35-client.txt)

**Comment by Johni0702** [comment]
This has been fixed in Steve's Carts 2 with version 1.12.2-2.4.31.135 (see https://github.com/TechReborn/StevesCarts/commit/127b022b85f48c3d7a167f6c158005cde0dec2f2).
