### ISSUE TITLE
[0.1.6] Serene Seasons glitch

### ISSUE THREAD

**Issue by ilvrak** [Johni0702/BetterPortals#88]
betterportals-0.1.6
SereneSeasons-1.12.2-1.2.16-universal

if the season changes the color of foliage and grass, then the opened betterportal provokes a constant reload of chunks between normal and seasoned

if i load my modpack 200+ - its blinking constantly. if i load clear test-mc with only that mods - blinking not so fast, but still happening

sometimes leaves patches of noncolored grass/leaves blocks

**Comment by Johni0702** [comment]
Should be fixed as of SereneSeasons 1.2.17.
