### ISSUE TITLE
Game Crashes every time I load up singleplayer (only mod installed with latest forge update [just installed it to get this mod])

### ISSUE THREAD

**Issue by StormRyder8** [Johni0702/BetterPortals#98]
Sorry for repeat of my last issue request but I just installed the latest version of the 1.12.2 forge using this link(https://www.minecraft-downloads.com/minecraft-forge-mod-for-windows-and-mac/) and even uninstalled and reinstalled the 1.12.2 forge but it still doesn't work, I don't understand. the specific forge version I'm using is 1.12.2-forge1.12.2-14.23.0.2529

**Comment by StormRyder8** [comment]
once again sorry to repeat this issue and bother you but the update didn't work

**Comment by Johni0702** [comment]
And that is one of the reasons you're always supposed to install from the official page only. The version of forge linked there is over two years old.
Get your forge from: https://files.minecraftforge.net/

**Comment by StormRyder8** [comment]
sorry for the issue, i thought that was the official page
